import {user,json,readWorld,mutate,requireOrigin} from '@/lib/world';
import {checkMessage,weekOf} from '@/lib/chat-filter';
import {CHAT_WARNINGS,CHAT_FINE,blockedMessage,type ChatFlag} from '@/lib/chat-rules';
import {schoolLockResponse} from '@/lib/school-lock-guard';
const blocked=(f:ChatFlag)=>({blocked:{reason:f.reason,warning:f.warning,coins:f.coins,message:blockedMessage(f)}});
export async function GET(req:Request){try{const closed=schoolLockResponse();if(closed)return closed;const uid=await user(req);if(!uid)return json({error:'Sign in to read class chat.'},401);const {w}=await readWorld();if(uid!=='teacher'&&!w.players[uid])return json({error:'Class members only.'},403);const conduct=w.players[uid]?.chatConduct;
 // The teacher sees recent blocked messages; a pupil sees only how many warnings they have used this week.
 return json({messages:w.chat??[],isTeacher:uid==='teacher',userId:uid,...(uid==='teacher'?{flags:(w.chatFlags??[]).slice(-50).reverse()}:{warnings:conduct?.week===weekOf(Date.now())?conduct.count:0})});}catch{return json({error:'Chat is unavailable. Please try again.'},503)}}
export async function POST(req:Request){try{const closed=schoolLockResponse();if(closed)return closed;requireOrigin(req);const uid=await user(req);if(!uid)return json({error:'Sign in to chat.'},401);const b:any=await req.json();const result:{ok?:boolean;blocked?:unknown}=await mutate(w=>{if(uid!=='teacher'&&!w.players[uid])throw Error('Class members only.');w.chat??=[];if(b.action==='delete'){const m=w.chat.find(m=>m.id===b.id);if(!m||!(uid==='teacher'||m.owner===uid))throw Error('You cannot remove that message.');w.chat=w.chat.filter(m=>m.id!==b.id);return{ok:true};}if(b.action!=='send')throw Error('Unknown chat action.');if(typeof b.id!=='string'||!/^[a-zA-Z0-9-]{16,64}$/.test(b.id))throw Error('Refresh and try again.');if(w.chat.some(m=>m.id===b.id&&m.owner===uid))return{ok:true};
 const repeat=w.chatFlags?.find(f=>f.id===b.id&&f.owner===uid);if(repeat)return blocked(repeat);
 const text=typeof b.text==='string'?b.text.trim():'';if(!text||text.length>300)throw Error('Write 1–300 characters.');
 // Pupils' messages are checked before they are posted: two warnings a week, then a fine for each blocked message. Balances stop at zero.
 const issue=uid==='teacher'?null:checkMessage(text);if(issue){const p=w.players[uid],week=weekOf(Date.now());if(p.chatConduct?.week!==week)p.chatConduct={week,count:0};const count=++p.chatConduct.count,warning=count<=CHAT_WARNINGS?count:null,coins=warning?0:Math.min(CHAT_FINE,Math.max(0,p.coins));p.coins-=coins;const flag:ChatFlag={id:b.id,owner:uid,name:p.name,text,reason:issue,at:Date.now(),warning,coins};w.chatFlags=[...(w.chatFlags??[]),flag].slice(-200);return blocked(flag);}
 const last=w.chat.filter(m=>m.owner===uid).at(-1);if(last&&Date.now()-last.at<3000)throw Error('Wait a moment before sending again.');w.chat.push({id:b.id,owner:uid,name:uid==='teacher'?'Teacher':w.players[uid].name,text,at:Date.now()});w.chat=w.chat.slice(-200);return{ok:true};});
 return json(result,result.blocked?422:200);}catch(e){return json({error:e instanceof Error?e.message:'Could not send message.'},400)}}
