import {user,json,readWorld,mutate,requireOrigin} from '@/lib/world';
import {checkMessage,weekOf} from '@/lib/chat-filter';
import {CHAT_WARNINGS,CHAT_FINE,FREE_WORDS_PER_DAY,COINS_PER_WORD,blockedMessage,countWords,wordsToday,priceWords,chatPaywallMessage,type ChatFlag} from '@/lib/chat-rules';
const blocked=(f:ChatFlag)=>({blocked:{reason:f.reason,warning:f.warning,coins:f.coins,message:blockedMessage(f)}});
function allowance(used:number){return {used,free:FREE_WORDS_PER_DAY,left:Math.max(0,FREE_WORDS_PER_DAY-used),coinsPerWord:COINS_PER_WORD};}
export async function GET(req:Request){try{const uid=await user(req);if(!uid)return json({error:'Sign in to read class chat.'},401);const {w}=await readWorld();if(uid!=='teacher'&&!w.players[uid])return json({error:'Class members only.'},403);const conduct=w.players[uid]?.chatConduct,today=uid==='teacher'?null:wordsToday(w.players[uid]?.chatWords,Date.now());
 // The teacher sees recent blocked messages; a pupil sees only how many warnings they have used this week, plus today's word allowance. Reading stays free.
 return json({messages:w.chat??[],isTeacher:uid==='teacher',userId:uid,...(uid==='teacher'?{flags:(w.chatFlags??[]).slice(-50).reverse()}:{warnings:conduct?.week===weekOf(Date.now())?conduct.count:0,allowance:{...allowance(today!.used),unlimited:!!w.players[uid]?.unlimitedCoins}})});}catch{return json({error:'Chat is unavailable. Please try again.'},503)}}
export async function POST(req:Request){try{requireOrigin(req);const uid=await user(req);if(!uid)return json({error:'Sign in to chat.'},401);const b:any=await req.json();const result:{ok?:boolean;blocked?:unknown;paywall?:unknown}=await mutate(w=>{if(uid!=='teacher'&&!w.players[uid])throw Error('Class members only.');w.chat??=[];if(b.action==='delete'){const m=w.chat.find(m=>m.id===b.id);if(!m||!(uid==='teacher'||m.owner===uid))throw Error('You cannot remove that message.');w.chat=w.chat.filter(m=>m.id!==b.id);return{ok:true};}if(b.action!=='send')throw Error('Unknown chat action.');if(typeof b.id!=='string'||!/^[a-zA-Z0-9-]{16,64}$/.test(b.id))throw Error('Refresh and try again.');if(w.chat.some(m=>m.id===b.id&&m.owner===uid))return{ok:true};
 const repeat=w.chatFlags?.find(f=>f.id===b.id&&f.owner===uid);if(repeat)return blocked(repeat);
 const text=typeof b.text==='string'?b.text.trim():'';if(!text||text.length>300)throw Error('Write 1–300 characters.');
 // Pupils' messages are checked before they are posted: two warnings a week, then a fine for each blocked message. Balances stop at zero. A blocked message does not use free words.
 const issue=uid==='teacher'?null:checkMessage(text);if(issue){const p=w.players[uid],week=weekOf(Date.now());if(p.chatConduct?.week!==week)p.chatConduct={week,count:0};const count=++p.chatConduct.count,warning=count<=CHAT_WARNINGS?count:null,coins=warning?0:Math.min(CHAT_FINE,Math.max(0,p.coins));p.coins-=coins;const flag:ChatFlag={id:b.id,owner:uid,name:p.name,text,reason:issue,at:Date.now(),warning,coins};w.chatFlags=[...(w.chatFlags??[]),flag].slice(-200);return blocked(flag);}
 const last=w.chat.filter(m=>m.owner===uid).at(-1);if(last&&Date.now()-last.at<3000)throw Error('Wait a moment before sending again.');
 // Pupils get FREE_WORDS_PER_DAY free words, then 1 coin per extra word. A message can be partly free. The teacher is not charged. Deleting a message does not refund words.
 let charged=0;if(uid!=='teacher'){const p=w.players[uid],today=wordsToday(p.chatWords,Date.now()),quote=priceWords(FREE_WORDS_PER_DAY-today.used,countWords(text));if(quote.cost>0&&!p.unlimitedCoins&&p.coins<quote.cost)return {paywall:{message:chatPaywallMessage({...quote,freeLeft:Math.max(0,FREE_WORDS_PER_DAY-today.used),coins:p.coins}),words:quote.words,freeLeft:Math.max(0,FREE_WORDS_PER_DAY-today.used),paidWords:quote.paidWords,cost:quote.cost,coins:p.coins,...allowance(today.used)}};if(!p.unlimitedCoins){p.coins-=quote.cost;charged=quote.cost;}p.chatWords={day:today.day,used:today.used+quote.words};}
 w.chat.push({id:b.id,owner:uid,name:uid==='teacher'?'Teacher':w.players[uid].name,text,at:Date.now()});w.chat=w.chat.slice(-200);return {ok:true,charged,allowance:uid==='teacher'?undefined:allowance(w.players[uid].chatWords?.used??0)};});
 return json(result,result.blocked?422:result.paywall?402:200);}catch(e){return json({error:e instanceof Error?e.message:'Could not send message.'},400)}}
