// Run after persistence.cjs, which compiles the real modules into work/persistence.
const assert=require('node:assert/strict'),fs=require('fs'),Module=require('module');
const original=Module._load;Module._load=function(id,...args){if(id==='cloudflare:workers')return{env:{}};return original.call(this,id,...args)};
const W=require('../work/persistence/world.cjs'),B=require('../work/persistence/battle.cjs'),{mapLayout}=require('../work/persistence/map-layout.cjs'),{chapterScene}=require('../work/persistence/chapter-scenes.cjs'),{ENEMIES,enemyDamage}=require('../work/persistence/enemies.cjs'),{buildStats}=require('../work/persistence/builds.cjs');
for(const wave of [1,11,21])assert.equal(chapterScene(wave).art,'/manor-campus-v2.png');
const paths=[];for(let c=4;c<=30;c++){const wave=(c-1)*10+1,layout=mapLayout(wave);assert(fs.existsSync('public'+chapterScene(wave).art));paths.push(JSON.stringify(layout.waypoints));for(let i=1;i<layout.path.length;i++)assert.equal(Math.abs(layout.path[i].x-layout.path[i-1].x)+Math.abs(layout.path[i].y-layout.path[i-1].y),1);for(const cell of layout.cells)assert(!B.isBuildable(cell,wave));}
assert.equal(new Set(paths).size,27);assert.equal(ENEMIES.length,12);for(const e of ENEMIES)assert(fs.existsSync('public/enemies/'+e.id+'.webp'));
const tin=ENEMIES.find(e=>e.id==='tinback'),moth=ENEMIES.find(e=>e.id==='moth');assert(enemyDamage(100,tin,'physical')<enemyDamage(100,tin,'magic'));assert(enemyDamage(100,moth,'magic')<enemyDamage(100,moth,'physical'));
const cells=Array.from({length:432},(_,i)=>i).filter(c=>B.isBuildable(c,10));const defenders=cells.slice(0,40).map((cell,i)=>({id:String(i),owner:'a',type:0,cell,level:10,weapon:'standard',weapons:['standard'],weaponLevels:{standard:10}}));
const w={wave:10,players:{a:W.newPlayer('Test')},defenders,battle:null,result:null};W.beginBattle(w,0);w.battle.fighters.forEach(f=>{f.stats={...buildStats(0,10,'standard'),damage:100000,range:100,cooldown:.2};});const battle=structuredClone(w.battle);assert.deepEqual(B.simulate(battle),B.simulate(battle));const before=structuredClone(w.defenders);w.battle.start=0;W.finish(w);assert(w.result.won);assert.equal(w.wave,11);assert.deepEqual(w.defenders,before.map(d=>({...d,cell:-1})));W.beginBattle(w,w.battleVersion);assert.equal(w.battle.fighters.length,0);w.battle.start=0;W.finish(w);assert(!w.result.won);assert.equal(w.wave,11);
console.log('PASS: 27 unique routes and available scene assets, original first three backgrounds, enemy resistances, deterministic combat, chapter reserve reset preserving equipment, reserves excluded, failed wave stays.');
