// Run game-audit.cjs first. Covers the roster contract and shipped art.
const fs=require('fs'),assert=require('node:assert/strict'),ts=require('typescript');
const {HEROES,SELECTABLE_HERO_IDS,heroArchetype,WEAPONS}=require('../work/heroes.cjs');
const {HERO_TRAITS,buildStats}=require('../work/builds.cjs');
const {EXTRA_HEROES}=require('../work/hero-catalogue.cjs');
assert.equal(EXTRA_HEROES.length,100);assert.equal(HEROES.length,116);assert.equal(SELECTABLE_HERO_IDS.length,114);
assert.equal(new Set(HEROES.map(h=>h.name)).size,116);assert(!SELECTABLE_HERO_IDS.includes(7)&&!SELECTABLE_HERO_IDS.includes(8));
assert.equal(HEROES[0].name,'Bramble');assert.equal(HEROES[15].name,'Leo');
for(const hero of EXTRA_HEROES){assert.equal(hero.id,16+EXTRA_HEROES.indexOf(hero));assert.equal(HEROES[hero.id].name,hero.name);assert(HERO_TRAITS[hero.id]);assert.deepEqual(HERO_TRAITS[hero.id].mods,HERO_TRAITS[hero.traitBase].mods);assert.equal(heroArchetype(hero.id),heroArchetype(hero.traitBase));assert.deepEqual(WEAPONS[hero.id],WEAPONS[hero.traitBase]);assert(Number.isFinite(buildStats(hero.id,10,'book').damage));}
for(const [input,output] of [['lib/hero-art.ts','hero-art'],['app/hero-sprite.tsx','hero-sprite'],['app/hero-picker.tsx','hero-picker']])fs.writeFileSync(`work/${output}.cjs`,ts.transpileModule(fs.readFileSync(input,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX}}).outputText.replace(/require\("(?:@\/lib\/|\.\/)(.*?)"\)/g,'require("./$1.cjs")'));
const React=require('react'),{renderToStaticMarkup}=require('react-dom/server'),Sprite=require('../work/hero-sprite.cjs').default,Picker=require('../work/hero-picker.cjs').default;
const html=renderToStaticMarkup(React.createElement(Picker,{me:{id:'a',hero:0,heroLocked:false,coins:0},players:[{id:'b',hero:16,name:'Classmate'}],busy:false,liveBattle:false,onChoose:()=>{}}));
assert(html.includes('Chosen by Classmate'));assert(html.includes('114 heroes'));assert.equal((html.match(/class="hero-claim"/g)||[]).length,24);assert(html.includes('aria-label="Hero pages"'));
const {HERO_ART}=require('../work/hero-art.cjs');assert.equal(Object.keys(HERO_ART).length,100);
(async()=>{const sharp=require('sharp');const hashes=new Set();for(const hero of EXTRA_HEROES){const file=`public/starters/${hero.id}.webp`;assert(fs.existsSync(file),file);const meta=await sharp(file).metadata();assert(meta.hasAlpha,hero.name);const stats=await sharp(file).stats();assert.equal(stats.channels.at(-1).min,0,hero.name+' must have transparent pixels');assert(stats.channels.at(-1).max>200,hero.name+' must have visible pixels');assert.equal(meta.width,HERO_ART[hero.id].width);assert.equal(meta.height,HERO_ART[hero.id].height);hashes.add(require('crypto').createHash('sha256').update(fs.readFileSync(file)).digest('hex'));const rendered=renderToStaticMarkup(React.createElement(Sprite,{type:hero.id,clothing:{top:'shirt',feet:'school-shoes'},weapon:'frost'}));assert(rendered.includes(`/starters/${hero.id}.webp`));assert(rendered.includes('/clothes/0.png'));assert(rendered.includes('/clothes/13.png'));assert(!rendered.includes(`/uniforms/`));}assert.equal(hashes.size,100);console.log('PASS: 100 distinct transparent assets, 114 selectable heroes, stable legacy IDs, balanced profiles, paginated chooser, claim labels and clothing/weapon rendering.');})().catch(e=>{console.error(e);process.exitCode=1});
