// A hero on a ride is drawn on the 3D map and, during a wave, rides themself to a useful square
// along the same rounded route monsters use. Dearer rides are faster. Never uses live pupil data.
const fs=require('fs'),ts=require('typescript'),assert=require('node:assert/strict'),{DatabaseSync}=require('node:sqlite'),Module=require('module');
const dir='work/ride-wave';fs.mkdirSync(dir,{recursive:true});
const compile=(src,out)=>fs.writeFileSync(`${dir}/${out}`,ts.transpileModule(fs.readFileSync(src,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText.replace(/require\("(?:@\/lib\/|\.\/)(.*?)"\)/g,'require("./$1.cjs")'));
for(const f of fs.readdirSync('lib').filter(f=>f.endsWith('.ts')))compile('lib/'+f,f.replace('.ts','.cjs'));
compile('app/api/game/route.ts','game.cjs');
const lib=name=>require(`../${dir}/${name}.cjs`);
const THREE=require('three');
const B=lib('battle'),{visualPosition,visualHeading}=lib('route-visual'),{mapLayout}=lib('map-layout'),{buildStats}=lib('builds');
const {acquireHeroTemplate,releaseHeroTemplate}=lib('board-heroes'),{BoardScene}=lib('board-scene'),{boardTheme}=lib('board-theme');
const {isBuildable,cellPoint,rideCells,riderState,planRide,waveCellSpeed,autoRidePlan,simulate,COLS}=B;
const {VEHICLES,rideCellSpeed}=lib('vehicles');

const layout=mapLayout(1,5,2),pathCells=[...layout.cells];
const distToPath=cell=>{const p=cellPoint(cell);let best=Infinity;for(const c of pathCells){const q=cellPoint(c);best=Math.min(best,Math.hypot(p.x-q.x,p.y-q.y));}return best;};
const open=[];for(let c=0;c<COLS*18;c++)if(isBuildable(c,1,2))open.push(c);
const ordered=[];for(const p of layout.path){const c=Math.floor(p.y)*COLS+Math.floor(p.x);if(ordered.at(-1)!==c)ordered.push(c);}
const beside=ordered[Math.floor(ordered.length*.35)];
const near=[beside-1,beside+1,beside-COLS,beside+COLS].find(c=>isBuildable(c,1,2));
const far=open.find(c=>{const cells=rideCells(c,near);return cells&&cells.length>=3&&cells.length<ordered.length*.3&&distToPath(c)>3;});
assert(near!==undefined&&far!==undefined,'a ride needs an open square beside the path and one further away');
const steps=rideCells(far,near);
assert(steps[0]===far&&steps.at(-1)===near);
assert(steps.every((c,i)=>i===0||Math.abs(c-steps[i-1])===1||Math.abs(c-steps[i-1])===COLS));
assert.equal(rideCells(far,14*COLS+21),null,'the manor footprint is not a riding square');
assert.equal(planRide({wave:1,rideMoves:[]},'h',far,14*COLS+21,0),null);

const points=steps.map(cellPoint);
const battle={rulesVersion:5,seed:7,start:1_000_000,wave:1,route:layout.waypoints,duration:B.rules(1).duration,power:0,target:0,contributors:1,fighters:[],rideMoves:[{id:'h',at:1_000_000,points,ride:'bicycle'}]};
let slower=0;
for(const v of VEHICLES){const s=rideCellSpeed(v.id);assert(s>slower,`${v.id} should be faster than the cheaper ride`);assert(Math.abs(s-waveCellSpeed(battle))>0.05,`${v.id} does not use the monster pace`);slower=s;}
assert.equal(rideCellSpeed('no-such-ride'),0);
const speed=rideCellSpeed('bicycle'),span=points.length-1;
const still=riderState(battle,'h',far,1_000_000);
assert.equal(still.moving,false);assert.equal(still.cell,far);assert.deepEqual({x:still.x,y:still.y},cellPoint(far));
const midAt=1_000_000+span/2/speed*1000,mid=riderState(battle,'h',far,midAt),seen=visualPosition(.5,points);
assert(Math.hypot(mid.x-seen.x,mid.y-seen.y)<1e-9,'halfway along, the hero sits on the same rounded route monsters use');
assert(Math.abs(mid.yaw-visualHeading(.5,points))<1e-9);
const done=riderState(battle,'h',far,midAt+span/2/speed*1000+20);
assert.equal(done.moving,false);assert.equal(done.cell,near);assert(Math.hypot(done.x-cellPoint(near).x,done.y-cellPoint(near).y)<1e-9);
assert.equal(riderState({...battle,rideMoves:[]},'h',far,midAt+99999).cell,far,'without an order the hero stays on their square');
// A new order starts where they are and a one-point order stops them.
const stop=planRide(battle,'h',far,mid.cell,midAt);
assert.deepEqual(stop,[cellPoint(mid.cell)]);
const engineTime=span/rideCellSpeed('fire-engine'),boardTime=span/rideCellSpeed('skateboard');
assert(engineTime<boardTime-1,'a dearer ride finishes the same route sooner');
const atEngine=battle.start+engineTime*1000+40;
assert.equal(riderState({...battle,rideMoves:[{id:'h',at:battle.start,points,ride:'fire-engine'}]},'h',far,atEngine).moving,false);
assert.equal(riderState({...battle,rideMoves:[{id:'h',at:battle.start,points,ride:'skateboard'}]},'h',far,atEngine).moving,true);
console.log(`PASS: rides follow the monster route at their own pace (bicycle ${speed.toFixed(2)} cells/s, ${span} squares from ${far} to ${near}).`);
const quietBattle={...battle,fighters:[],rideMoves:[]};
const rowOf=cell=>Math.floor(cell/COLS),pathIndex=cell=>{const p=cellPoint(cell);let best=0,bd=1e9;layout.path.forEach((q,i)=>{const d=Math.hypot(q.x-p.x,q.y-p.y);if(d<bd){bd=d;best=i;}});return best;};
const upper=open.find(c=>rowOf(c)<=4&&distToPath(c)>1.2&&distToPath(c)<4);
assert(upper!==undefined,'need a square near the top of the route');
const plans=autoRidePlan(quietBattle,[{id:'h',cell:upper,owner:'a'},{id:'stand',cell:near,owner:'b'}],owner=>owner==='a'?'fire-engine':undefined,()=>2.4,2);
assert(plans.length>=4,'a riding hero keeps taking new squares through the wave');
assert.equal(plans[0].move.ride,'fire-engine');assert.equal(plans[0].move.at,quietBattle.start);
assert(plans.at(-1).move.at>quietBattle.start+15000,'the journey is still going well after the opening ride');
assert.notEqual(plans[0].to,upper);assert.notEqual(plans[0].to,near);assert(isBuildable(plans[0].to,1,2));
assert(rowOf(plans[0].to)<12,`the first square is row ${rowOf(plans[0].to)}, not the bottom of the map`);
assert(pathIndex(plans[0].to)<layout.path.length*.55,'the first square meets the monsters near the start of the route');
const later=plans[Math.min(3,plans.length-1)];
assert(pathIndex(later.to)>pathIndex(plans[0].to),'later hops follow the monsters further along the route');
const positions=plans.map(p=>p.to);assert(new Set(positions).size>=3,'they do not park on one square');
const besidePlans=autoRidePlan(quietBattle,[{id:'h',cell:near,owner:'a'}],()=>'car',()=>1.8,2);
assert(besidePlans.length>=3);assert.notEqual(besidePlans[0].to,near);
const other=open.find(c=>c!==upper&&c!==near&&rowOf(c)>=8);
const pair=autoRidePlan(quietBattle,[{id:'a1',cell:upper,owner:'a'},{id:'b1',cell:other,owner:'b'}],()=>'scooter',()=>2.2,2);
const firstA=pair.find(p=>p.id==='a1'),firstB=pair.find(p=>p.id==='b1');
assert(firstA&&firstB&&firstA.to!==firstB.to,'two riders do not claim the same first square');
console.log(`PASS: from row ${rowOf(upper)} the first hop is row ${rowOf(plans[0].to)} (path square ${pathIndex(plans[0].to)}), then ${plans.length} hops follow the monsters.`);

const stats={...buildStats(2,1,'standard',{}),damage:50000,range:1.2,cooldown:.2,critChance:0};
const fighter={id:'h',type:2,level:1,weapon:'standard',cell:far,owner:'a',name:'Ada',stats};
const quiet={...battle,fighters:[fighter],rideMoves:undefined};
const riding={...battle,fighters:[fighter],rideMoves:[{id:'h',at:battle.start,points,ride:'bicycle'}]};
const quietSim=simulate(quiet),rideSim=simulate(riding);
assert.equal(quietSim.events.length,0,'a short-range hero far from the path does not hit anyone');
assert(rideSim.events.length>0,'the same hero hits monsters after riding up to the path');
assert(rideSim.events.every(e=>e.fighter===0));
const arrive=span/speed;
const parked={...riding,rideMoves:[{id:'h',at:battle.start+battle.duration,points,ride:'bicycle'}]};
assert.equal(JSON.stringify(simulate(parked).events),JSON.stringify(quietSim.events),'an order that has not begun leaves the fight unchanged');
console.log(`PASS: riding into range deals ${rideSim.events.length} hits; standing still deals none.`);

const plain=acquireHeroTemplate({type:0,weapon:'standard'}),ridden=acquireHeroTemplate({type:0,weapon:'standard',ride:{id:'bicycle',paint:'green'}});
assert(ridden.template.triangles>plain.template.triangles,'the bicycle is part of the hero mesh, in the same bake as other map heroes');
releaseHeroTemplate(plain.key);releaseHeroTemplate(ridden.key);
const scene=new BoardScene(),camera=new THREE.PerspectiveCamera(36,2,.5,260);
camera.position.set(12,20,30);camera.lookAt(12,0,9);camera.updateMatrixWorld();
scene.setHeroes([{id:'h',type:0,cell:far,level:1,weapon:'standard',name:'Ada',ride:{id:'bicycle',paint:'green'}}]);
scene.setBattle(riding);
scene.frame({time:0,battleNow:battle.start,camera,motion:true,labels:false});
const home=cellPoint(far),there=cellPoint(near);
const over=p=>scene.pick(new THREE.Ray(new THREE.Vector3(p.x,30,p.y),new THREE.Vector3(0,-1,0)));
assert.deepEqual(over(home),{kind:'hero',id:'h'});
scene.frame({time:arrive+1,battleNow:battle.start+(arrive+1)*1000,camera,motion:true,labels:false});
assert.deepEqual(over(there),{kind:'hero',id:'h'},'after the ride, the hero stands on the destination square');
assert.notDeepEqual(over(home),{kind:'hero',id:'h'});
scene.dispose();
console.log('PASS: the 3D map shows the ride and moves that hero onto the chosen square during the wave.');

const file=`${dir}/test-${Date.now()}.sqlite`,sqlite=new DatabaseSync(file);
sqlite.exec('CREATE TABLE world(id TEXT PRIMARY KEY,revision INTEGER NOT NULL,data TEXT NOT NULL); CREATE TABLE sessions(token TEXT PRIMARY KEY,user_id TEXT,expires INTEGER);');
const DB={prepare(sql){return {bind(...values){return {async run(){return {meta:{changes:Number(sqlite.prepare(sql).run(...values).changes)}}},async first(){return sqlite.prepare(sql).get(...values)??null}}}}}};
const original=Module._load;Module._load=function(id,...args){if(id==='cloudflare:workers')return{env:{DB}};return original.call(this,id,...args)};
const W=lib('world'),GAME=lib('game');
const post=(uid,body)=>GAME.POST(new Request('https://game.test/api/game',{method:'POST',headers:{cookie:'qg_session='+uid,origin:'https://game.test',host:'game.test','content-type':'application/json','X-Quest-Heroes':'6'},body:JSON.stringify({requestId:crypto.randomUUID(),...body})})).then(async r=>({status:r.status,body:await r.json()}));
(async()=>{
 sqlite.prepare('INSERT INTO sessions VALUES (?,?,?)').run(await W.sha('a'),'a',Date.now()+86400000);
 await W.mutate(w=>{w.players.a={...W.newPlayer('Ada'),coins:5000,hero:2,heroLocked:true,lastSeen:Date.now()};});
 let r=await post('a',{action:'recruit',type:2,cell:far});assert.equal(r.status,200);
 const defender=r.body.world.defenders.find(d=>d.owner==='a');
 r=await post('a',{action:'battle',battleVersion:r.body.world.battleVersion});assert.equal(r.status,200);assert(r.body.world.battle);
 r=await post('a',{action:'move',id:defender.id,cell:near});assert.equal(r.status,400);assert.match(r.body.error,/Wait for the shared wave/);
 assert.equal((await W.readWorld()).w.battle.rideMoves,undefined);
 r=await post('a',{action:'vehicle',item:'scooter'});assert.equal(r.status,200);assert.deepEqual(r.body.world.me.ride,{id:'scooter',paint:'red'});
 r=await post('a',{action:'move',id:defender.id,cell:beside});assert.equal(r.status,400);assert.match(r.body.error,/open square beside the path/);
 r=await post('a',{action:'move',id:defender.id,cell:near});assert.equal(r.status,200);
 const saved=(await W.readWorld()).w,fight=saved.battle,moved=saved.defenders.find(d=>d.id===defender.id),hero=fight.fighters.find(f=>f.id===defender.id);
 assert.equal(hero.cell,far,'the wave still replays from the square the hero started on');
 assert.equal(fight.rideMoves[0].id,defender.id);assert.equal(fight.rideMoves[0].ride,'scooter');assert.deepEqual(fight.rideMoves[0].points,points);
 assert(fight.rideMoves.length>1,'after the chosen square they keep riding');
 const arrived=riderState(fight,defender.id,hero.cell,fight.rideMoves[1].at);
 assert.equal(arrived.cell,near);assert.equal(arrived.moving,false);
 r=await post('a',{action:'move',id:defender.id,cell:far});assert.equal(r.status,200);
 const again=(await W.readWorld()).w.battle.rideMoves.filter(m=>m.id===defender.id);
 const hand=again.find(m=>Math.hypot(m.points.at(-1).x-cellPoint(far).x,m.points.at(-1).y-cellPoint(far).y)<1e-6);
 assert(hand&&again.some(m=>m.at>hand.at),'a manual order still uses the route, then the hero carries on');
 const version=(await W.readWorld()).w.battleVersion;
 await W.mutate(w=>{w.battle=null;w.players.a.vehicle='fire-engine';const d=w.defenders.find(d=>d.owner==='a');d.cell=far;});
 r=await post('a',{action:'battle',battleVersion:version});assert.equal(r.status,200);
 const auto=(await W.readWorld()).w,autoFight=auto.battle,autoHero=autoFight.fighters.find(f=>f.id===defender.id),autoDef=auto.defenders.find(d=>d.id===defender.id);
 assert.equal(autoHero.cell,far,'the wave still replays from the square the hero started on');
 assert.notEqual(autoDef.cell,far,'the hero leaves that square without a manual order');
 assert(autoFight.rideMoves.length>=3);assert.equal(autoFight.rideMoves[0].ride,'fire-engine');assert.equal(autoFight.rideMoves[0].at,autoFight.start);
 assert(autoFight.rideMoves.at(-1).at>autoFight.start+12000);
 const moving=riderState(autoFight,defender.id,autoHero.cell,autoFight.start+6000);
 assert.notEqual(moving.cell,far);
 const settled=riderState(autoFight,defender.id,autoHero.cell,autoFight.start+180000);
 assert.equal(settled.cell,autoDef.cell);assert.equal(settled.moving,false);
 console.log('PASS: during a wave a riding hero keeps repositioning toward the monsters, and a manual order still uses the same route.');
 sqlite.close();fs.rmSync(file,{force:true});
})().catch(e=>{console.error(e);process.exitCode=1});
