'use client';
import {useMemo} from 'react';
import {simulate,percent,pathPosition,COLS,ROWS,type Battle} from '@/lib/battle';
export default function BattleScene({battle,now}:{battle:Battle;now:number}){
 const sim=useMemo(()=>simulate(battle),[battle.start]);
 const elapsed=Math.max(0,(now-battle.start)/1000),active=sim.events.filter(e=>elapsed-e.at>=0&&elapsed-e.at<.75);
 const monsters=Array.from({length:sim.count},(_,i)=>{const progress=(elapsed-i*sim.rule.spawn)/sim.rule.travel;const hp=Math.max(0,sim.rule.hp-sim.events.filter(e=>e.monster===i&&e.at+.25<=elapsed).reduce((s,e)=>s+e.damage,0));const d=sim.deathAt[i];return{id:i,hp,progress,pos:pathPosition(progress),dead:hp===0,deathAt:d===null?null:d+.25}});
 const killed=monsters.filter(m=>m.dead).length;
 return <div className="battle-scene" aria-label={`Heroes are fighting. ${killed} of ${sim.count} monsters defeated.`}><svg className="battle-projectiles" viewBox={`0 0 ${COLS} ${ROWS}`} preserveAspectRatio="none" aria-hidden="true">{active.map((e,i)=>{const f=battle.fighters[e.fighter],p=percent(f.cell),from={x:p.x*COLS/100,y:p.y*ROWS/100},t=Math.min(1,(elapsed-e.at)/.25),x=from.x+(e.point.x-from.x)*t,y=from.y+(e.point.y-from.y)*t,colour=['#ffe396','#c6a7ff','#ffcf6b'][f.type];return <g key={`${e.at}-${i}`} opacity={t<1?1:Math.max(0,1-(elapsed-e.at-.25)*3)}>{f.type===2?<path d={`M ${from.x-.4} ${from.y-.3} Q ${x+.5} ${y-.6} ${e.point.x} ${e.point.y}`} stroke={colour} fill="none" strokeWidth=".13"/>:<><line x1={x-(e.point.x-from.x)*.13} y1={y-(e.point.y-from.y)*.13} x2={x} y2={y} stroke={colour} strokeWidth={f.type===1?.12:.065}/><circle cx={x} cy={y} r={f.type===1?.14:.06} fill={colour}/></>}{t===1&&<circle cx={x} cy={y} r={.2+(elapsed-e.at-.25)*.5} fill="none" stroke={colour} strokeWidth=".06"/>}</g>})}</svg>
 {battle.fighters.map((f,i)=>{const pos=percent(f.cell),attack=active.find(e=>e.fighter===i);return <div className={`battle-fighter type-${f.type} ${attack?'attacking':''}`} key={f.id} style={{left:`${pos.x}%`,top:`${pos.y}%`}}><span className={`sprite sprite-${f.type}`}/><span className="fighter-level">{f.level}</span>{attack&&<span className="attack-name">{['ARROW!','ZAP!','SLASH!'][f.type]}</span>}</div>})}
 {monsters.map(m=>{if(m.progress<0||m.progress>=1||m.deathAt!==null&&elapsed>m.deathAt+.75)return null;const hit=active.find(e=>e.monster===m.id&&elapsed-e.at>=.25);return <div key={m.id} className={`battle-monster ${m.dead?'vanquished':''} ${hit?'hit':''}`} style={{left:`${m.pos.x/COLS*100}%`,top:`${m.pos.y/ROWS*100}%`}}><span className="sprite sprite-3"/><span className="monster-hp-track"><span style={{width:`${m.hp/sim.rule.hp*100}%`}}/></span>{hit&&!m.dead&&<b className="damage-number">−{hit.damage}</b>}{m.dead&&<b className="poof">✦</b>}</div>})}
 <div className="battle-count"><span>MONSTERS</span><b>{killed} <i>/ {sim.count}</i></b></div>
 {elapsed>battle.duration/1000-3&&<div className="battle-finale">{sim.killed===sim.count&&battle.contributors>=4?<><b>Victory for the Manor!</b><span>The Manor House is safe.</span></>:<><b>Rally your heroes!</b><span>{battle.contributors<4?'Bring at least 4 classmates into this wave.':`${sim.count-sim.killed} monsters got through. Reposition, upgrade and try again.`}</span></>}</div>}</div>
}
