'use client';
import {useRef,useState} from 'react';
import {Coins,Lock,PackageOpen,Backpack,Trophy,ArrowRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {ITEMS,HERO_TRAITS,WEAPON_BASE,MOD_LABELS,modText,itemMods,itemUpgradeCost,slotCost,buildStats,referenceDps,type ItemLoadout} from '@/lib/builds';
import {EQUIPMENT,equipment,effectSummary,MAX_WEAPON_LEVEL} from '@/lib/equipment';
import {HEROES,upgradeCost} from '@/lib/heroes';
import {ITEM_BLURBS,ITEM_GOALS,itemArt,itemGoals} from '@/lib/item-guide';
import {Price,SaveUp,Ribbon,Stars,LevelTrack,PowerBars,ModChips,WEAPON_ICONS,WEAPON_KINDS,canAfford,celebrate} from './shop-kit';
export function StatsPanel({type,level=1,weapon='standard',loadout={},compare,stats}:{type:number;level?:number;weapon?:string;loadout?:ItemLoadout;compare?:ReturnType<typeof buildStats>;stats?:ReturnType<typeof buildStats>}){const s=stats??buildStats(type,level,weapon,loadout);const rows:[string,number,string][]=[['Damage',s.damage,''],['Attack rate',1/s.cooldown,' / sec'],['Range',s.range,' squares'],['Crit chance',s.critChance*100,'%'],['Single-target DPS',referenceDps(s),''],['AOE radius',s.splash,' squares']];const previous=compare?[compare.damage,1/compare.cooldown,compare.range,compare.critChance*100,referenceDps(compare),compare.splash]:null;return <div className="build-stats"><dl>{rows.map(([name,value,unit],i)=><div key={name}><dt>{name}</dt><dd>{previous&&Math.abs(previous[i]-value)>.001&&<small>{previous[i].toFixed(1)} → </small>}{value.toFixed(1)}{unit}</dd></div>)}</dl><p>{s.damage?effectSummary(s):'Unarmed — cannot attack until a weapon is equipped.'}</p><p>AOE is the splash radius around the impact. Actual damage depends on enemy armour and resistance.</p><details><summary>How these stats work</summary><p>{s.cooldown.toFixed(3)} seconds between attacks · ×{s.critMultiplier.toFixed(2)} critical damage · +{Math.round(s.bossDamage*100)}% Boss damage</p><p>{MOD_LABELS[s.category]} scaling: each point adds {s.scaling} damage before percentage bonuses.</p><p>Hero: {modText(HERO_TRAITS[type]?.mods??{})}</p>{(loadout.equippedItems??[]).map(id=><p key={id}>{ITEMS.find(i=>i.id===id)?.name}: {modText(itemMods(id,loadout.itemInventory?.[id]))}</p>)}<p>Reference DPS is for one target, before enemy effects. It excludes splash, chain hits, paint and help given to classmates. +25% attack speed turns a 1-second interval into 0.8 seconds.</p></details></div>}
// Weapon cards with big pictures; the chosen card opens a detail panel with simple Power / Speed / Reach bars.
// The caller performs the purchase (onAction) and, in the shop, the level-up (onUpgrade).
export function WeaponShop({selected,me,busy,liveBattle,onAction,onUpgrade,onEarn,heroLabel='your hero'}:{selected:any;me:any;busy:boolean;liveBattle:any;onAction:(data:any)=>Promise<any>;onUpgrade?:()=>Promise<any>;onEarn?:()=>void;heroLabel?:string}){
 const [preview,setPreview]=useState(selected.weapon&&selected.weapon!=='none'?selected.weapon:'standard'),detail=useRef<HTMLElement>(null);
 const owns=(id:string)=>selected.weapons?.includes(id)||(id==='standard'&&selected.level>0&&!selected.weapons);
 const item=equipment(preview),owned=owns(item.id),equipped=selected.weapon===preview&&selected.level>0,level=equipped?selected.level:selected.weaponLevels?.[preview]??1;
 const current=buildStats(selected.type,selected.level,selected.weapon,me),shown=buildStats(selected.type,level,preview,me),Effect=WEAPON_ICONS[item.id],kind=WEAPON_KINDS[WEAPON_BASE[item.id].category],cost=upgradeCost(selected.type,selected.level);
 // On narrow screens the detail sits below the cards, so bring it into view when a card is chosen.
 const pick=(id:string)=>{setPreview(id);requestAnimationFrame(()=>{const r=detail.current?.getBoundingClientRect();if(r&&(r.top<0||r.top>window.innerHeight-160))detail.current!.scrollIntoView({behavior:'smooth',block:'start'})})};
 return <div className="weapon-aisle"><div className="shop-grid weapon-grid">{EQUIPMENT.map(w=>{const Icon=WEAPON_ICONS[w.id],mine=owns(w.id),on=selected.weapon===w.id&&selected.level>0;return <button key={w.id} className={`shop-card ${preview===w.id?'chosen':''} ${on?'is-equipped':mine?'is-owned':''}`} aria-pressed={preview===w.id} onClick={()=>pick(w.id)}>{on?<Ribbon kind="equipped">Using</Ribbon>:mine&&<Ribbon kind="owned">Owned</Ribbon>}<img className="shop-art" src={`/weapons/${w.art}.png`} alt=""/><b>{w.name}</b><span className="effect-chip"><Icon aria-hidden="true"/>{w.effect}</span>{mine?<span className="card-foot">Level {on?selected.level:selected.weaponLevels?.[w.id]??1}</span>:<Price price={w.price} me={me}/>}</button>})}</div>
 <section className="shop-detail" ref={detail} aria-live="polite"><div className="detail-head"><img className="detail-art" src={`/weapons/${item.art}.png`} alt=""/><div><h3>{item.name}</h3><div className="chip-row"><span className="effect-chip"><Effect aria-hidden="true"/>{item.effect}</span><span className="effect-chip quiet"><kind.icon aria-hidden="true"/>{kind.label}</span></div></div></div><p className="detail-text">{item.description}</p>
 <h4>{equipped?`How strong it is for ${heroLabel}`:`Compared with what ${heroLabel} uses now`}</h4><PowerBars stats={shown} compare={equipped?undefined:current}/>
 {owned&&<><LevelTrack level={level}/><p className="detail-note">Level {level} of {MAX_WEAPON_LEVEL}. Special powers grow at levels 3, 6 and 10.</p></>}
 {liveBattle&&<p className="detail-note">A wave is running. You can buy and swap weapons when it ends.</p>}
 {equipped?<button className="primary" disabled>{heroLabel[0].toUpperCase()+heroLabel.slice(1)} is using this</button>:<button className="primary" disabled={busy||!!liveBattle||(!owned&&!canAfford(item.price,me))} onClick={()=>onAction({action:'weapon',id:selected.id,weapon:preview})}>{owned?<>Use {item.name} · Free</>:<>Buy for <Coins aria-hidden="true"/>{item.price}</>}</button>}
 {!owned&&<SaveUp price={item.price} me={me} onEarn={onEarn}/>}
 {equipped&&onUpgrade&&(cost===null?<p className="level-up done"><Trophy aria-hidden="true"/>Legendary! {item.name} is at the top level.</p>:<div className="level-up"><h4>Level up to {selected.level+1}</h4><PowerBars stats={buildStats(selected.type,selected.level+1,preview,me)} compare={current}/><button className="primary" disabled={busy||!!liveBattle||!canAfford(cost,me)} onClick={onUpgrade}>Level up for <Coins aria-hidden="true"/>{cost}</button><SaveUp price={cost} me={me} onEarn={onEarn}/></div>)}
 <details className="expert-stats"><summary>See all the numbers</summary><StatsPanel type={selected.type} level={level} weapon={preview} loadout={me} compare={equipped?undefined:current}/></details></section></div>}
// Items: "pockets" are the equipped slots. In the shop every item is shown; in the backpack only owned ones, with quick pocket buttons.
export default function ItemShop({me,busy,liveBattle,action,defenders=[],mode='shop',onBrowse,onEarn}:{me:any;busy:boolean;liveBattle:any;action:(data:any,message?:string)=>Promise<any>;defenders?:any[];mode?:'shop'|'backpack';onBrowse?:()=>void;onEarn?:()=>void}){
 const [open,setOpen]=useState<string|null>(null),[goal,setGoal]=useState('all');
 const inv=me.itemInventory??{},equipped:string[]=me.equippedItems??[],slots=me.itemSlots??2,slotPrice=slotCost(slots),owned=ITEMS.filter(it=>inv[it.id]);
 const shown=(mode==='shop'?ITEMS:owned).filter(it=>goal==='all'||itemGoals(it.id).includes(goal));
 const act=async(data:any,text:string,art:string)=>{const r=await action(data);if(r)celebrate(text,art);return r};
 const quick=(id:string)=>equipped.includes(id)?act({action:'item_unequip',item:id},`${ITEMS.find(i=>i.id===id)!.name} is back in your backpack.`,itemArt(id)):equipped.length<slots?act({action:'item_equip',item:id},`${ITEMS.find(i=>i.id===id)!.name} is in your pocket. All your heroes feel it!`,itemArt(id)):setOpen(id);
 return <section className="item-aisle"><div className="pockets"><div><h3><Backpack aria-hidden="true"/>Your pockets</h3><p>Items in your pockets help <b>all</b> of your heroes. Swap them for free between waves.</p></div><div className="pocket-row">{Array.from({length:slots},(_,i)=>{const it=ITEMS.find(x=>x.id===equipped[i]);return it?<button key={i} className="pocket full" onClick={()=>setOpen(it.id)}><img src={itemArt(it.id)} alt=""/><b>{it.name}</b><Stars level={inv[it.id]??1}/></button>:<div key={i} className="pocket empty"><PackageOpen aria-hidden="true"/><span>Empty pocket</span><small>{owned.length?'Choose one of your items':'Buy an item to fill it'}</small></div>})}{slotPrice!==null&&<button className="pocket locked" disabled={busy||!!liveBattle||!canAfford(slotPrice,me)} onClick={()=>act({action:'item_slot'},`Pocket ${slots+1} is open! Now you can carry ${slots+1} items.`,'/items/backpack.svg')}><Lock aria-hidden="true"/><b>Open pocket {slots+1}</b><Price price={slotPrice} me={me}/></button>}</div></div>
 {mode==='shop'&&<div className="goal-chips" role="group" aria-label="What should your heroes get better at?"><span>I want my heroes to get…</span>{[{id:'all',label:'Everything'},...ITEM_GOALS].map(g=><button key={g.id} aria-pressed={goal===g.id} className={goal===g.id?'active':''} onClick={()=>setGoal(g.id)}>{g.label}</button>)}</div>}
 {mode==='backpack'&&!owned.length&&<div className="empty-note"><img src="/items/backpack.svg" alt=""/><p>No items yet. Answer questions to earn coins, then pick one below or in the shop.</p></div>}
 {mode==='backpack'&&owned.length>0&&<div className="aisle-title"><h3>Your items · {owned.length}</h3></div>}
 <div className="shop-grid item-grid">{shown.map(it=>{const level=inv[it.id]??0,on=equipped.includes(it.id);return <article key={it.id} className={`shop-card ${on?'is-equipped':level?'is-owned':''}`}><button className="card-main" onClick={()=>setOpen(it.id)}>{on?<Ribbon kind="equipped">In pocket</Ribbon>:level>0&&<Ribbon kind="owned">Owned</Ribbon>}<img className="shop-art" src={itemArt(it.id)} alt=""/><b>{it.name}</b><span className="card-blurb">{ITEM_BLURBS[it.id]}</span>{level?<Stars level={level}/>:<Price price={it.price} me={me}/>}</button>{mode==='backpack'&&<button className="card-quick" disabled={busy||!!liveBattle} onClick={()=>quick(it.id)}>{on?'Take out':equipped.length<slots?'Put in a pocket':'Swap in…'}</button>}</article>})}</div>
 {mode==='backpack'&&owned.length<ITEMS.length&&<><div className="aisle-title"><h3>Still to collect · {ITEMS.length-owned.length}</h3>{onBrowse&&<button className="quiet-button" onClick={onBrowse}>Shop for items <ArrowRight aria-hidden="true"/></button>}</div><div className="shop-grid item-grid">{ITEMS.filter(it=>!inv[it.id]).map(it=><button key={it.id} className="shop-card locked" onClick={()=>setOpen(it.id)}><img className="shop-art" src={itemArt(it.id)} alt=""/><b>{it.name}</b><Price price={it.price} me={me}/></button>)}</div></>}
 <ItemDialog id={open} onClose={()=>setOpen(null)} me={me} busy={busy} liveBattle={liveBattle} act={act} defenders={defenders} onEarn={onEarn}/></section>}
function ItemDialog({id,onClose,me,busy,liveBattle,act,defenders,onEarn}:{id:string|null;onClose:()=>void;me:any;busy:boolean;liveBattle:any;act:(data:any,text:string,art:string)=>Promise<any>;defenders:any[];onEarn?:()=>void}){
 // The swap choice belongs to the item it was made for, so opening another item starts with none chosen.
 const [choice,setChoice]=useState({id:'',swap:''}),swap=choice.id===id?choice.swap:'',setSwap=(e:string)=>setChoice({id:id??'',swap:e});
 const item=ITEMS.find(i=>i.id===id),inv=me.itemInventory??{},equipped:string[]=me.equippedItems??[],slots=me.itemSlots??2;
 // Preview on the hero's first armed defender, so the bars match a weapon the pupil really uses.
 const sample=defenders.find(d=>d.level>0&&d.cell>=0)??defenders.find(d=>d.level>0),weapon=sample?.weapon&&sample.weapon!=='none'?sample.weapon:'standard',wl=sample?.level||1,label=sample?`${HEROES[sample.type].name} #${defenders.indexOf(sample)+1} with ${equipment(weapon).name}`:`${HEROES[me.hero]?.name??'Your hero'} with a ${equipment(weapon).name}`;
 const level=item?inv[item.id]??0:0,on=!!item&&equipped.includes(item.id),full=equipped.length>=slots,upgrade=item?itemUpgradeCost(item.id,level):null;
 // Compare today's pockets with the pockets after this item goes in (replacing the chosen swap, or as an extra when none is chosen).
 const kept=equipped.filter(x=>x!==item?.id&&x!==swap),without=on?{...me,equippedItems:kept}:me,withItem=item?{...me,itemInventory:{...inv,[item.id]:level||1},equippedItems:[item.id,...kept],itemSlots:kept.length+1}:me;
 // When the bars cannot move (a magic item on an aim weapon, or a boss or freeze bonus), say why instead of showing a puzzling "no change".
 const after=buildStats(me.hero,wl,weapon,withItem),before=buildStats(me.hero,wl,weapon,without),still=after.damage===before.damage&&Math.abs(after.cooldown-before.cooldown)<.005&&Math.abs(after.range-before.range)<.01;
 const kinds=Object.entries(item?.mods??{}).filter(([k,v])=>v!>0&&k in WEAPON_KINDS).map(([k])=>k),cat=WEAPON_BASE[weapon].category;
 const why=kinds.length&&!kinds.includes(cat)?`It powers up ${kinds.map(k=>WEAPON_KINDS[k].label).join(' and ')} weapons, and the ${equipment(weapon).name} is a${cat==='aim'?'n':''} ${WEAPON_KINDS[cat].label} weapon.`:'Its other powers, such as lucky hits, freezing, splash or boss damage, still help in battle.';
 return <Dialog open={!!item} onOpenChange={o=>!o&&onClose()}><DialogContent className="shop-dialog sm:max-w-2xl">{item&&<><div className="dialog-hero"><img className="dialog-art" src={itemArt(item.id)} alt=""/><div><DialogTitle className="modal-title">{item.name}</DialogTitle><DialogDescription>{ITEM_BLURBS[item.id]}</DialogDescription>{level>0&&<div className="dialog-level"><Stars level={level}/>Level {level} of 3{on&&<Ribbon kind="equipped">In your pocket</Ribbon>}</div>}</div></div>
 {liveBattle&&<p className="shop-note">A wave is running. You can look now and buy or swap when it ends.</p>}
 <h4>What it does{level>0?'':' at level 1'}</h4><ModChips mods={itemMods(item.id,level||1)}/>
 <h4>{on?'What it adds':'What it would add'} for {label}</h4><PowerBars stats={after} compare={before}/>{still&&<p className="detail-note">These bars stay the same here. {why}</p>}
 {!level?<><button className="primary" disabled={busy||!!liveBattle||!canAfford(item.price,me)} onClick={()=>act({action:'item_buy',item:item.id},`You bought the ${item.name}! Put it in a pocket to use it.`,itemArt(item.id))}>Buy for <Coins aria-hidden="true"/>{item.price}</button><SaveUp price={item.price} me={me} onEarn={onEarn}/></>
 :on?<button className="secondary-button" disabled={busy||!!liveBattle} onClick={()=>act({action:'item_unequip',item:item.id},`${item.name} is back in your backpack.`,itemArt(item.id))}>Take it out of your pocket · Free</button>
 :<>{full&&<><h4>Your pockets are full. Swap it with:</h4><div className="swap-row">{equipped.map(e=><button key={e} aria-pressed={swap===e} onClick={()=>setSwap(e)}><img src={itemArt(e)} alt=""/>{ITEMS.find(x=>x.id===e)?.name}</button>)}</div></>}<button className="primary" disabled={busy||!!liveBattle||(full&&!swap)} onClick={()=>act({action:'item_equip',item:item.id,replace:swap||undefined},`${item.name} is in your pocket. All your heroes feel it!`,itemArt(item.id))}>{full?'Swap it in · Free':'Put it in a pocket · Free'}</button></>}
 {level>0&&(upgrade===null?<p className="level-up done"><Trophy aria-hidden="true"/>Top level! This item is as strong as it gets.</p>:<div className="level-up"><h4>Level up to <Stars level={level+1}/></h4><ModChips mods={itemMods(item.id,level+1)} good/><button className="primary" disabled={busy||!!liveBattle||!canAfford(upgrade,me)} onClick={()=>act({action:'item_upgrade',item:item.id},`${item.name} is now level ${level+1}!`,itemArt(item.id))}>Level up for <Coins aria-hidden="true"/>{upgrade}</button><SaveUp price={upgrade} me={me} onEarn={onEarn}/></div>)}
 <details className="expert-stats"><summary>See all the numbers</summary><StatsPanel type={me.hero} level={wl} weapon={weapon} loadout={withItem} compare={before}/></details></>}</DialogContent></Dialog>}
