'use client';
import {memo,useCallback,useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import {ArrowDown,Coins,GraduationCap,MessageCircle,SendHorizontal,ShieldAlert,Trash2,X} from 'lucide-react';
import type {Wardrobe} from '@/lib/clothing';
import {CHAT_WARNINGS,CHAT_FINE,CHAT_ISSUES,COINS_PER_WORD,countWords,type ChatFlag,type ChatIssue} from '@/lib/chat-rules';
import Sprite from './hero-sprite';
type Message={id:string;owner:string;name:string;text:string;at:number;status?:'sending'|'sent'|'failed';error?:string};
type Person={id:string;name:string;hero:number;gender?:string;clothing?:Wardrobe;uniform?:string;outfit?:string;heroLocked?:boolean};
type ChatState={count:number;lastId:string|null;lastAt:number;lastOwner:string|null}|null;
type Row={key:string;day:number}|{key:string;owner:string;name:string;items:Message[]};
type Blocked={reason:ChatIssue;warning:number|null;coins:number;message:string};
type Allowance={used:number;free:number;left:number;coinsPerWord:number;unlimited?:boolean};
type Paywall={message:string;words:number;freeLeft:number;paidWords:number;cost:number;coins:number};
// Quick messages fill the box, so pupils can add a row or path before sending.
const QUICK=['Which path needs a hero?','I will guard the left path','Ready for the next wave!','Great teamwork! 🎉'];
const LIMIT=300,SEND_GAP=3100,GROUP_GAP=5*60000;
const clock=(at:number)=>new Date(at).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});
function dayLabel(at:number){const day=new Date(at).toDateString(),now=new Date(),yesterday=new Date(now.getFullYear(),now.getMonth(),now.getDate()-1);return day===now.toDateString()?'Today':day===yesterday.toDateString()?'Yesterday':new Date(at).toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'});}
function onlineText(online:Person[],myId:string){const others=online.filter(p=>p.id!==myId).map(p=>p.name);if(!others.length)return 'No classmates online right now';if(others.length===1)return `${others[0]} is online`;if(others.length<=3)return `${others.slice(0,-1).join(', ')} and ${others.at(-1)} are online`;return `${others.slice(0,2).join(', ')} and ${others.length-2} others are online`;}
function scrollDown(el:HTMLElement|null,smooth=false){el?.scrollTo({top:el.scrollHeight,behavior:smooth&&!matchMedia('(prefers-reduced-motion: reduce)').matches?'smooth':'auto'});}
async function post(body:Record<string,string>){const r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}).catch(()=>{throw Error('No connection.');}),d=await r.json().catch(()=>({})) as {error?:string;blocked?:Blocked;paywall?:Paywall;charged?:number;allowance?:Allowance};if(d.blocked)throw Object.assign(Error(d.blocked.message),{blocked:d.blocked});if(d.paywall)throw Object.assign(Error(d.paywall.message),{paywall:d.paywall});if(!r.ok)throw Error(d.error??'Something went wrong.');return d;}
function Avatar({owner,player,name}:{owner:string;player?:Person;name:string}){if(owner==='teacher')return <span className="chat-avatar teacher" aria-hidden="true"><GraduationCap size={20}/></span>;return <span className="chat-avatar" aria-hidden="true">{player?<Sprite type={player.hero} gender={player.gender} clothing={player.clothing} uniform={player.uniform} outfit={player.outfit}/>:<b>{name.slice(0,1).toUpperCase()}</b>}</span>;}
function ClassChat({me,isTeacher,players,online,chatState,onRead,onEarn}:{me:{id:string;name:string;unlimitedCoins?:boolean}|null;isTeacher:boolean;players:Person[];online:Person[];chatState:ChatState;onRead:(at:number)=>void;onEarn?:()=>void}){
 const myId=isTeacher?'teacher':me?.id??'',myName=isTeacher?'Teacher':me?.name??'';
 const [messages,setMessages]=useState<Message[]|null>(null),[pending,setPending]=useState<Message[]>([]),[text,setText]=useState(''),[loadError,setLoadError]=useState(''),[notice,setNotice]=useState(''),[confirm,setConfirm]=useState(''),[unseen,setUnseen]=useState(0),[away,setAway]=useState(false),[warning,setWarning]=useState<Blocked|null>(null),[paywall,setPaywall]=useState<Paywall|null>(null),[warnings,setWarnings]=useState(0),[flags,setFlags]=useState<ChatFlag[]>([]),[allowance,setAllowance]=useState<Allowance|null>(null);
 const scroller=useRef<HTMLDivElement>(null),input=useRef<HTMLTextAreaElement>(null),stick=useRef(true),far=useRef(false),seen=useRef<Set<string>|null>(null),loads=useRef(0),queue=useRef(Promise.resolve()),lastSent=useRef(0);
 const load=useCallback(async()=>{const n=++loads.current;try{const r=await fetch('/api/chat',{cache:'no-store'}),d:{messages:Message[];flags?:ChatFlag[];warnings?:number;allowance?:Allowance;error?:string}=await r.json();if(!r.ok)throw Error(d.error);if(n===loads.current){setMessages(d.messages);setFlags(d.flags??[]);setWarnings(d.warnings??0);setAllowance(d.allowance??null);setLoadError('');}}catch(e){if(n===loads.current)setLoadError(e instanceof TypeError?'Could not load messages. Check your connection.':(e as Error).message||'Could not load messages.');}},[]);
 // The world poll carries a tiny chat summary, so messages are fetched only when something changed.
 const sig=chatState?`${chatState.count}:${chatState.lastId}`:'';
 useEffect(()=>{load();},[load,sig]);
 useEffect(()=>{const t=setInterval(()=>{if(!document.hidden)load();},15000);return()=>clearInterval(t);},[load]);
 useEffect(()=>{if(!messages)return;const ids=new Set(messages.map(m=>m.id));setPending(p=>p.some(m=>ids.has(m.id))?p.filter(m=>!ids.has(m.id)):p);},[messages]);
 const list=useMemo(()=>{const ids=new Set((messages??[]).map(m=>m.id));return [...(messages??[]),...pending.filter(m=>!ids.has(m.id))];},[messages,pending]);
 const rows=useMemo(()=>{const out:Row[]=[];let prev:Message|undefined;for(const m of list){const day=new Date(m.at).toDateString(),last=out.at(-1);if(!prev||new Date(prev.at).toDateString()!==day)out.push({key:'day-'+day,day:m.at});else if(last&&'items'in last&&last.owner===m.owner&&m.at-last.items.at(-1)!.at<GROUP_GAP){last.items.push(m);prev=m;continue;}out.push({key:m.id,owner:m.owner,name:m.name,items:[m]});prev=m;}return out;},[list]);
 const byId=useMemo(()=>new Map(players.map(p=>[p.id,p])),[players]);
 const latest=messages?.at(-1)?.at??0;
 // Open at the newest message; follow new ones only while the pupil is already at the bottom.
 useLayoutEffect(()=>{if(!messages)return;const ids=new Set(list.map(m=>m.id));if(!seen.current){seen.current=ids;scrollDown(scroller.current);return;}const fresh=list.filter(m=>!seen.current!.has(m.id)&&m.owner!==myId).length;seen.current=ids;if(stick.current)scrollDown(scroller.current,true);else if(fresh)setUnseen(u=>u+fresh);},[list,messages,myId]);
 useEffect(()=>{const read=()=>{if(stick.current&&latest&&!document.hidden)onRead(latest);};read();document.addEventListener('visibilitychange',read);return()=>document.removeEventListener('visibilitychange',read);},[latest,onRead]);
 useLayoutEffect(()=>{const el=input.current;if(!el)return;el.style.height='auto';el.style.height=Math.min(el.scrollHeight+2,140)+'px';},[text]);
 function onScroll(){const el=scroller.current!,gap=el.scrollHeight-el.scrollTop-el.clientHeight;stick.current=gap<72;if(stick.current){setUnseen(0);if(latest)onRead(latest);}if(gap>320!==far.current){far.current=gap>320;setAway(far.current);}}
 function send(body:string,id:string=crypto.randomUUID()){setNotice('');stick.current=true;setPending(p=>[...p.filter(m=>m.id!==id),{id,owner:myId,name:myName,text:body,at:Date.now(),status:'sending'}]);
  // One message every 3 seconds is allowed, so quick sends wait their turn instead of failing.
  queue.current=queue.current.then(async()=>{const wait=lastSent.current+SEND_GAP-Date.now();if(wait>0)await new Promise(r=>setTimeout(r,wait));try{const sent=await post({action:'send',id,text:body});setPending(p=>p.map(m=>m.id===id?{...m,status:'sent'}:m));if(sent.allowance)setAllowance(sent.allowance);setNotice(sent.charged?`Sent. ${sent.charged} coin${sent.charged===1?'':'s'} for the extra words.`:'');load();}catch(e){const stop=(e as {blocked?:Blocked;paywall?:Paywall}).blocked,wall=(e as {paywall?:Paywall}).paywall;
   // A blocked or unpaid message is not posted and must not be retried as if it were sent.
   if(stop){setPending(p=>p.filter(m=>m.id!==id));setWarning(stop);load();}
   else if(wall){setPending(p=>p.filter(m=>m.id!==id));setPaywall(wall);setText(current=>current.trim()?current:body);load();}
   else setPending(p=>p.map(m=>m.id===id?{...m,status:'failed',error:(e as Error).message}:m));}finally{lastSent.current=Date.now();}});}
 function submit(){const body=text.trim();if(!body||!myId)return;setText('');setWarning(null);setPaywall(null);send(body);input.current?.focus();}
 const draftWords=countWords(text),showCost=!!allowance&&!allowance.unlimited&&!isTeacher,draftCost=showCost?Math.max(0,draftWords-allowance.left)*COINS_PER_WORD:0;
 async function remove(id:string){setConfirm('');setMessages(ms=>ms&&ms.filter(m=>m.id!==id));try{await post({action:'delete',id});}catch(e){setNotice((e as Error).message);}load();}
 return <><section className="chat-window" aria-label="Class chat">
  <header className="chat-header"><div className="chat-online" title={online.map(p=>p.name).join(', ')}><span className="chat-faces" aria-hidden="true">{online.filter(p=>p.id!==myId).slice(0,5).map(p=><span className="chat-face" key={p.id}>{p.heroLocked!==false?<Sprite type={p.hero} clothing={p.clothing}/>:<b>{p.name.slice(0,1).toUpperCase()}</b>}</span>)}</span><span><i className={online.some(p=>p.id!==myId)?'online-dot':'offline-dot'}/>{onlineText(online,myId)}</span></div>{loadError&&messages&&<span className="chat-reconnect" role="status">Reconnecting…</span>}</header>
  <div className="chat-body"><div className="chat-scroll" ref={scroller} onScroll={onScroll} role="log" aria-live="polite" aria-label="Class messages" tabIndex={0}>
   {!messages?<p className="chat-empty" role={loadError?'alert':'status'}>{loadError||'Loading messages…'}</p>:!list.length?<div className="chat-empty"><MessageCircle size={34}/><b>No messages yet</b><span>Say hello and plan the next wave together.</span></div>:rows.map(g=>{if(!('items'in g))return <div className="chat-day" key={g.key}><span>{dayLabel(g.day)}</span></div>;const mine=g.owner===myId,teacher=g.owner==='teacher';return <div className={`chat-group${mine?' mine':''}${teacher?' from-teacher':''}`} key={g.key}>{!mine&&<Avatar owner={g.owner} player={byId.get(g.owner)} name={g.name}/>}<div className="chat-stack"><div className="chat-meta">{mine?<span className="sr-only">You</span>:<b>{g.name}</b>}{teacher&&!mine&&<span className="chat-badge">Teacher</span>}<time dateTime={new Date(g.items[0].at).toISOString()}>{clock(g.items[0].at)}</time></div>
    {g.items.map(m=><div className="chat-msg" key={m.id}><div className="chat-line"><p className={`chat-bubble${m.status?' pending':''}`} title={new Date(m.at).toLocaleString('en-GB')}>{m.text}</p>{!m.status&&(mine||isTeacher)&&(confirm===m.id?<span className="chat-confirm"><button type="button" onClick={()=>remove(m.id)}>Remove</button><button type="button" onClick={()=>setConfirm('')}>Keep</button></span>:<button type="button" className="chat-remove" aria-label={`Remove message: ${m.text.slice(0,40)}`} onClick={()=>setConfirm(m.id)}><Trash2 size={15}/></button>)}</div>
     {m.status==='sending'&&<span className="chat-status">Sending…</span>}{m.status==='failed'&&<span className="chat-status failed" role="alert">Not sent{m.error?`: ${m.error}`:'.'} <button type="button" onClick={()=>send(m.text,m.id)}>Try again</button> · <button type="button" onClick={()=>setPending(p=>p.filter(x=>x.id!==m.id))}>Delete</button></span>}</div>)}</div></div>;})}
  </div>{(unseen>0||away)&&<button type="button" className="chat-jump" onClick={()=>{stick.current=true;setUnseen(0);scrollDown(scroller.current,true);}}><ArrowDown size={16}/>{unseen?`${unseen} new message${unseen===1?'':'s'}`:'Latest messages'}</button>}</div>
  <div className="chat-compose">{warning&&<div className={`chat-warning${warning.coins?' fined':''}`} role="alert"><ShieldAlert size={20}/><p>{warning.message}</p><button type="button" aria-label="Dismiss warning" onClick={()=>setWarning(null)}><X size={16}/></button></div>}{paywall&&<div className="chat-paywall" role="alert"><Coins size={20}/><div><p>{paywall.message}</p>{onEarn&&paywall.coins<paywall.cost&&<button type="button" className="chat-earn" onClick={onEarn}>Earn coins</button>}</div><button type="button" aria-label="Dismiss" onClick={()=>setPaywall(null)}><X size={16}/></button></div>}{!text&&!isTeacher&&!warning&&!paywall&&<div className="chat-quick" role="group" aria-label="Quick messages">{QUICK.map(q=><button type="button" key={q} onClick={()=>{setText(q);input.current?.focus();}}>{q}</button>)}</div>}
   <form className="chat-form" onSubmit={e=>{e.preventDefault();submit();}}><label htmlFor="chat-message" className="sr-only">Message your class</label><textarea id="chat-message" ref={input} rows={1} value={text} maxLength={LIMIT} placeholder="Message your class…" onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();submit();}}}/><button className="chat-send" aria-label="Send message" disabled={!text.trim()||!messages}><SendHorizontal size={20}/></button></form>
   <p className="chat-hint">{notice?<span className={notice.startsWith('Sent')?'chat-words':'chat-error'} role="status">{notice}</span>:<span>{isTeacher?'Pupils’ messages are checked for rude words, links and personal details. Blocked messages are listed below the chat.':`Be kind. No rude words, links or personal details: ${CHAT_WARNINGS} warnings a week, then −${CHAT_FINE} coins each time. Teachers can read all messages.`}{warnings>0&&<b className="chat-strikes"> Warnings used this week: {Math.min(warnings,CHAT_WARNINGS)} of {CHAT_WARNINGS}.</b>}{showCost&&<b className="chat-words">{allowance.left>0?` Free words today: ${allowance.left} of ${allowance.free}.`:` Today's ${allowance.free} free words are used up.`} Extra words cost {allowance.coinsPerWord} coin each.{draftCost>0?` This message: ${draftWords} words, ${draftCost} coin${draftCost===1?'':'s'}.`:''}</b>}</span>}{text.length>=LIMIT-60&&<span className="chat-count">{LIMIT-text.length} left</span>}</p></div>
 </section>
 {isTeacher&&<details className="chat-flags"><summary><ShieldAlert size={18}/> Blocked messages <b>{flags.length}</b></summary>{flags.length?<ul>{flags.map(f=><li key={f.id}><div><b>{f.name}</b><span>{CHAT_ISSUES[f.reason]}</span><time dateTime={new Date(f.at).toISOString()}>{new Date(f.at).toLocaleString('en-GB',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</time><em className={f.warning?'':'fined'}>{f.warning?`Warning ${f.warning} of ${CHAT_WARNINGS}`:`−${f.coins} coins`}</em></div><p>{f.text}</p></li>)}</ul>:<p>No blocked messages. Pupils’ messages with rude words, links, phone numbers or email addresses will appear here.</p>}</details>}
 </>;
}
export default memo(ClassChat);
