'use client';
import {Shirt,ArrowRight} from 'lucide-react';
import {CLOTHING,CLOTHING_SLOTS,clothingArt} from '@/lib/clothing';
import Sprite from './hero-sprite';
import {Price,Ribbon,canAfford,celebrate} from './shop-kit';
// Clothes by body part, each with its picture. Tapping a card wears it (buying first if needed); tapping what you wear takes it off.
export default function ClothesRack({me,busy,action,mode='shop',onShop}:{me:any;busy:boolean;action:(data:any,message?:string)=>Promise<any>;mode?:'shop'|'backpack';onShop?:()=>void}){
 const owned:string[]=me.clothingOwned??[],worn=me.clothing??{},count=CLOTHING.filter(c=>owned.includes(c.id)).length;
 const tap=async(item:typeof CLOTHING[number])=>{const wearing=worn[item.slot]===item.id,r=await action(wearing?{action:'undress',slot:item.slot}:{action:'clothing',item:item.id});if(r)celebrate(wearing?`Took off the ${item.name}. It stays in your backpack.`:owned.includes(item.id)?`Now wearing the ${item.name}!`:`You bought the ${item.name} and put it on!`,clothingArt(item))};
 return <section className="clothes-rack"><div className="mirror">{me.heroLocked?<Sprite type={me.hero} gender={me.gender} uniform={me.uniform} clothing={me.clothing} outfit={me.outfit}/>:<Shirt aria-hidden="true"/>}<div><b>{mode==='shop'?'Try things on':`${me.name}’s wardrobe`}</b><p>{mode==='shop'?'Tap anything to wear it. You pay once, then wearing it again is always free. Clothes change your look, not your powers.':`${count} of ${CLOTHING.length} clothes collected. Tap to put things on or take them off.`}</p>{mode==='backpack'&&onShop&&<button className="quiet-button" onClick={onShop}>Find more clothes in the shop <ArrowRight aria-hidden="true"/></button>}</div></div>
 {mode==='backpack'&&!count&&<div className="empty-note"><img src="/clothes/0.png" alt=""/><p>No clothes yet. Earn some coins, then visit the clothes aisle in the shop.</p></div>}
 {CLOTHING_SLOTS.map(slot=>{const items=CLOTHING.filter(c=>c.slot===slot.id&&(mode==='shop'||owned.includes(c.id)));return items.length>0&&<div key={slot.id}><div className="aisle-title"><h3>{slot.name}</h3></div><div className="shop-grid clothes-grid">{items.map(item=>{const mine=owned.includes(item.id),wearing=worn[item.slot]===item.id;return <button key={item.id} className={`shop-card ${wearing?'is-equipped':mine?'is-owned':''}`} disabled={busy||(!mine&&!canAfford(item.price,me))} onClick={()=>tap(item)}>{wearing?<Ribbon kind="equipped">Wearing</Ribbon>:mine&&<Ribbon kind="owned">Owned</Ribbon>}<img className="shop-art" src={clothingArt(item)} alt=""/><b>{item.name}</b>{wearing?<span className="card-foot">Tap to take off</span>:mine?<span className="card-foot">Wear · Free</span>:<Price price={item.price} me={me}/>}</button>})}</div></div>})}</section>}
