'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {HeartHandshake,CheckCircle2,Lightbulb} from 'lucide-react';
import {toast} from 'sonner';
import {HELP_REWARD,ANSWER_PENALTY,HINTS_PER_QUESTION,OPEN_HELP_REQUESTS,HINT_MAX,answerPenalty,STUCK,hintStarters,type Stuck} from '@/lib/friend-help';
import {QuestionBody,AnswerChoices,ReadingPane,RichText,answered,type AnswerValue} from './question-card';
export async function helpAction(data:any){const r=await fetch('/api/help',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)}),d:any=await r.json();if(!r.ok)throw Error(d.error??'Could not save. Try again.');return d}
async function loadBoard(){const r=await fetch('/api/help',{cache:'no-store'}),d:any=await r.json();if(!r.ok)throw Error(d.error??'The help board is unavailable. Please try again.');return d}
const when=(t:number)=>new Date(t).toLocaleString('en-GB',{weekday:'short',hour:'2-digit',minute:'2-digit'});
const canHelp=(r:any)=>r.status==='ready'||r.status==='unlocked';
const HINT_PROMPTS:Record<Stuck,string>={meaning:'Explain what the question is asking, without the answer.',start:'What should they do first?',wrong:'What mistake is easy to make here?',word:'Explain the tricky word, without giving the answer.'};
// Asking takes two taps: say what is tricky (or just ask), and the question goes on the help board.
export function AskFriend({question,status=null,hints=0,online,onDone}:{question:string;status?:string|null;hints?:number;online?:number;onDone?:()=>void}){const [posted,setPosted]=useState<{from:string|null;to:string}|null>(null),[picking,setPicking]=useState(false),[busy,setBusy]=useState(false);
// What the pupil just did shows at once, until the notebook reloads with the board's own status.
const state=posted&&posted.from===status?posted.to:status;
async function send(body:any,done:string){setBusy(true);try{const r=await helpAction(body);setPosted({from:status,to:body.action==='withdraw'?'closed':'open'});setPicking(false);toast.success(r.already?'This question is already on the help board.':done);onDone?.()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
const ask=(stuck?:Stuck)=>send({action:'ask',question,stuck},'Posted! Friends who solve it can send you a hint.');
if(state==='full')return <p className="ask-status"><Lightbulb aria-hidden="true"/><span>You have {HINTS_PER_QUESTION} hints from friends. Use them to try again!</span></p>;
if(state==='open')return <div className="ask-status"><HeartHandshake aria-hidden="true"/><span>On the help board · {hints} of {HINTS_PER_QUESTION} hints so far. We’ll let you know when a hint arrives.</span><button className="quiet-button" disabled={busy} onClick={()=>send({action:'withdraw',question},'Taken off the help board.')}>Take it off the board</button></div>;
return <div className="ask-friend">{picking?<fieldset disabled={busy}><legend>What’s tricky? Your friends will see this.</legend><div className="stuck-options">{(Object.entries(STUCK) as [Stuck,string][]).map(([id,text])=><button type="button" key={id} onClick={()=>ask(id)}>{text}</button>)}</div><div className="ask-more"><button type="button" onClick={()=>ask()}>{busy?'Posting…':'Just ask for a hint'}</button><button type="button" onClick={()=>setPicking(false)}>Cancel</button></div></fieldset>:<button type="button" className="ask-friend-button" disabled={busy} onClick={()=>setPicking(true)}><HeartHandshake aria-hidden="true"/>Ask a friend for a hint</button>}{online!==undefined&&<small>{online?`${online} classmate${online===1?' is':'s are'} online now.`:'Classmates will see it next time they play.'}</small>}</div>}
// A signed-in pupil's hint news, polled for the Mistakes dot, New labels, toasts and the retry reminder. The read position is per device, like chat.
const readMark=(uid:string)=>{try{return Number(localStorage.getItem('mq-help-read:'+uid))||0}catch{return 0}};
export function useHelpNews(uid:string|undefined,reading:boolean,openNotebook:()=>void){const [loaded,setLoaded]=useState<{uid:string;board:any}|null>(null),[read,setRead]=useState<{id?:string;at:number}>({at:0}),[visit,setVisit]=useState({reading:false,since:0}),seen=useRef<{uid:string;hints:Set<string>;paid:Set<string>}|null>(null);
const news=loaded&&loaded.uid===uid?loaded.board:null;
const load=useCallback(()=>{if(uid&&!document.hidden)loadBoard().then(board=>{if(board.isTeacher)return;setLoaded({uid,board});setRead(r=>r.id===uid?r:{id:uid,at:readMark(uid)})}).catch(()=>{/* The next poll tries again. */})},[uid]);
useEffect(()=>{if(!uid)return;load();const t=setInterval(load,20000);document.addEventListener('visibilitychange',load);return()=>{clearInterval(t);document.removeEventListener('visibilitychange',load)}},[uid,load]);
const latest=news?Math.max(0,...news.myHints.map((h:any)=>h.at),...news.requests.filter(canHelp).map((r:any)=>r.at)):0;
// Opening Mistakes marks everything read. Hints newer than the old position keep a New label until the pupil leaves.
if(visit.reading!==reading)setVisit({reading,since:read.at});
if(reading&&uid&&read.id===uid&&latest>read.at)setRead({id:uid,at:latest});
useEffect(()=>{if(uid&&read.id===uid)try{localStorage.setItem('mq-help-read:'+uid,String(read.at))}catch{}},[uid,read]);
// Toast hints that arrive while the pupil is elsewhere, and a helper's hint that has just earned coins. The first load only records what is already there.
useEffect(()=>{if(!news||!uid||read.id!==uid)return;const first=seen.current?.uid!==uid;if(first)seen.current={uid,hints:new Set(),paid:new Set()};const s=seen.current!,fresh=news.myHints.filter((h:any)=>h.at>read.at&&!s.hints.has(h.id)),paid=news.sentHints.filter((h:any)=>h.status==='paid'&&!s.paid.has(h.id));news.myHints.forEach((h:any)=>s.hints.add(h.id));paid.forEach((h:any)=>s.paid.add(h.id));if(fresh.length&&!reading)toast(fresh.length>1?`You have ${fresh.length} new hints from friends!`:`${fresh[0].name} sent you a hint for your ${fresh[0].subject} question!`,{action:{label:'Read it',onClick:openNotebook}});if(!first)for(const h of paid)toast.success(`${h.name} got it right after your hint. You earned ${HELP_REWARD} coins!`)},[news,uid,read,reading,openNotebook]);
return{news,reload:load,unread:!reading&&!!uid&&read.id===uid&&latest>read.at,since:visit.since,helpable:news?news.requests.filter(canHelp).length:0}}
// Pupils must solve a friend's question before the hint box opens. Teachers see every hint, can remove it, and can fine a hint that gave the answer away.
export function HelpFriends({Diagram,refresh=0,teacher=false}:any){const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[open,setOpen]=useState(''),[answer,setAnswer]=useState<AnswerValue>(''),[hint,setHint]=useState(''),[penalise,setPenalise]=useState('');const hintId=useRef(''),hintBox=useRef<HTMLTextAreaElement>(null);
useEffect(()=>{let stopped=false;const run=()=>loadBoard().then(d=>{if(!stopped){setData(d);setError('')}}).catch(e=>{if(!stopped)setError(e.message)});run();const t=setInterval(run,10000);return()=>{stopped=true;clearInterval(t)}},[refresh]);
function choose(id:string){setOpen(id);setAnswer('');setHint('');hintId.current=crypto.randomUUID()}
function startHint(starter:string){setHint(h=>`${h.trim()?h.trimEnd()+' ':''}${starter} `.slice(0,HINT_MAX));requestAnimationFrame(()=>{const box=hintBox.current;if(box){box.focus();box.setSelectionRange(box.value.length,box.value.length)}})}
async function act(body:any,done:(r:any)=>void){setBusy(true);try{done(await helpAction(body))}catch(e){toast.error((e as Error).message)}try{setData(await loadBoard())}catch{}setBusy(false)}
return <section className="panel help-board" aria-labelledby="help-board-title"><div className="section-title"><h2 id="help-board-title"><HeartHandshake/> Help a friend with questions</h2><b>+{HELP_REWARD} coins when your friend gets it right</b></div><p>{teacher?`Pupils post questions they are stuck on. Friends must answer correctly before they can send a hint, and earn ${HELP_REWARD} coins only when the pupil then solves the question. Remove any unkind hint. If a hint gives the answer away, choose Gave the answer: the hint is removed and the helper loses ${ANSWER_PENALTY} coins, plus the ${HELP_REWARD} it earned if it was already paid.`:`Classmates post questions they are stuck on. Answer one correctly to unlock the hint box, then send a clue — not the answer. You earn ${HELP_REWARD} coins when your friend gets the question right, but if your teacher finds a hint that gives the answer away, you lose ${ANSWER_PENALTY} coins.`}</p>{error&&<p role="alert" className="error-banner">{error}</p>}{!teacher&&data?.mine>0&&<p className="help-mine">You have {data.mine} of {OPEN_HELP_REQUESTS} questions on the board. Hints from friends appear in your notebook below.</p>}
{!data?<p role="status">Loading questions from your class…</p>:!data.requests.length?<p>{teacher?'No pupil has asked for help yet.':'No one needs help right now. When classmates ask for a hint, their questions appear here.'}</p>:<div className="help-list">{data.requests.map((r:any)=><article className="help-card" key={r.id}><div className="section-title"><b>{r.name} {teacher?'asked':'asks'} · {r.question.subject} · {r.question.difficulty}</b><span>{teacher?r.status==='open'?'On the board':r.status==='full'?'Enough hints':'Closed':`${r.hints} of ${HINTS_PER_QUESTION} hints`}</span></div><h3><RichText text={r.question.prompt}/></h3>{r.stuck&&<p className="help-stuck"><b>{r.name}:</b> “{STUCK[r.stuck as Stuck]}”</p>}
{teacher?(!r.hints.length?<p>No hints yet.</p>:<ul className="hint-list">{r.hints.map((h:any)=><li key={h.id}><div><b>{h.name}</b> <time dateTime={new Date(h.at).toISOString()}>{when(h.at)}</time>{h.paidAt&&!h.gaveAnswer&&<span>· earned {HELP_REWARD} coins</span>}{h.gaveAnswer&&<span className="hint-penalty">· gave the answer · lost {h.gaveAnswer.coins} coins</span>}{!h.removed&&penalise!==h.id&&<span className="hint-actions"><button className="quiet-button" disabled={busy} onClick={()=>act({action:'remove',id:r.id,hint:h.id},()=>toast.success('Hint removed.'))}>Remove</button><button className="quiet-button hint-penalise" disabled={busy} onClick={()=>setPenalise(h.id)}>Gave the answer</button></span>}</div>
{penalise===h.id&&!h.removed&&<div className="hint-confirm"><span>Remove this hint and take {answerPenalty(h)} coins from {h.name}{h.paidAt?` (${ANSWER_PENALTY}, plus the ${HELP_REWARD} it earned)`:''}?</span><button className="hint-fine" disabled={busy} onClick={()=>act({action:'gave_answer',id:r.id,hint:h.id},res=>{toast.success(`Hint removed. ${res.name} lost ${res.coins} coins.`);setPenalise('')})}>Take {answerPenalty(h)} coins</button><button className="quiet-button" disabled={busy} onClick={()=>setPenalise('')}>Cancel</button></div>}
<p>{h.gaveAnswer?<s>{h.text}</s>:h.removed?<i>Removed by teacher</i>:h.text}</p></li>)}</ul>)
:r.status==='sent'?<p className="help-note">{r.sent?<><CheckCircle2/><span>Hint sent. You earn {HELP_REWARD} coins when {r.name} gets it right.</span></>:r.lost!=null?`Your teacher removed your hint because it gave the answer away. You lost ${r.lost} coins.`:'Your teacher removed your hint.'}</p>
:r.status==='own'?<p className="help-note">This question is in your mistake notebook too. Solve it there first, then come back to help.</p>
:r.status==='active'?<p className="help-note">This is your current question in Earn coins. Answer it there first.</p>
:r.status==='resting'?<p className="help-note">Not quite this time. You can try this question again {when(r.retryAt)}.</p>
:open!==r.id?<button className="secondary-button" disabled={busy} onClick={()=>choose(r.id)}>{r.status==='unlocked'?`Write your hint for ${r.name}`:`Help ${r.name}`}</button>
:<div className="help-work">{r.status==='ready'&&<>{r.question.reading&&<ReadingPane reading={r.question.reading} page={r.question.page}/>}<QuestionBody q={r.question} Diagram={Diagram} showPrompt={false}/><form onSubmit={e=>{e.preventDefault();act({action:'answer',id:r.id,answer},res=>res.correct?toast.success(`Correct! Now write a hint for ${r.name}.`):toast('Not quite. You can try this question again in 24 hours.'))}}><AnswerChoices q={r.question} name={`help-${r.id}`} value={answer} onChange={setAnswer} disabled={busy} label="Solve it first to unlock the hint box"/><button className="primary" disabled={busy||!answered(r.question,answer)}>{busy?'Checking…':'Check my answer'}</button></form></>}
{r.status==='unlocked'&&<form onSubmit={e=>{e.preventDefault();act({action:'hint',id:r.id,hint:hintId.current,text:hint},()=>{toast.success(`Hint sent! You earn ${HELP_REWARD} coins when ${r.name} gets it right.`);setOpen('')})}}><label htmlFor={`help-hint-${r.id}`}>You solved it! Write a hint for {r.name}</label><div className="hint-starters" role="group" aria-label="Start your hint with">{hintStarters(r.stuck).map(s=><button type="button" key={s} disabled={busy} onClick={()=>startHint(s)}>{s}…</button>)}</div><textarea id={`help-hint-${r.id}`} ref={hintBox} value={hint} onChange={e=>setHint(e.target.value)} maxLength={HINT_MAX} rows={3} placeholder={HINT_PROMPTS[r.stuck as Stuck]??'Give a clue, not the answer. What should they try first?'} required/><p className="help-warning">Clues only. If your teacher finds a hint that gives the answer away, you lose {ANSWER_PENALTY} coins.</p><div className="section-title"><span>{hint.length}/{HINT_MAX}</span><button className="primary" disabled={busy||!hint.trim()}>{busy?'Sending…':'Send hint'}</button></div></form>}<button type="button" className="quiet-button" onClick={()=>setOpen('')}>Close</button></div>}</article>)}</div>}
{!teacher&&data?.sentHints?.length>0&&<div className="sent-hints"><h3>Your hints</h3><ul className="hint-list">{data.sentHints.map((h:any)=><li key={h.id}><div><b>To {h.name} · {h.subject}</b> <time dateTime={new Date(h.at).toISOString()}>{when(h.at)}</time></div><p>{h.status==='removed'?<i>Removed by your teacher</i>:h.status==='answer'?<>“{h.text}” — <b className="hint-penalty">Your teacher removed this hint because it gave the answer away. You lost {h.lost} coins.</b></>:<>“{h.text}” —{h.status==='paid'?`${h.name} got it right! You earned ${HELP_REWARD} coins.`:`Waiting for ${h.name} to solve it.`}</>}</p></li>)}</ul></div>}</section>}
