'use client';
import {useEffect,useRef,useState} from 'react';
import {HeartHandshake,CheckCircle2} from 'lucide-react';
import {toast} from 'sonner';
import {HELP_REWARD,ANSWER_PENALTY,HINTS_PER_QUESTION,OPEN_HELP_REQUESTS,HINT_MAX,answerPenalty} from '@/lib/friend-help';
export async function helpAction(data:any){const r=await fetch('/api/help',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)}),d:any=await r.json();if(!r.ok)throw Error(d.error??'Could not save. Try again.');return d}
async function loadBoard(){const r=await fetch('/api/help',{cache:'no-store'}),d:any=await r.json();if(!r.ok)throw Error(d.error??'The help board is unavailable. Please try again.');return d}
const when=(t:number)=>new Date(t).toLocaleString('en-GB',{weekday:'short',hour:'2-digit',minute:'2-digit'});
// Pupils must solve a friend's question before the hint box opens. Teachers see every hint, can remove it, and can fine a hint that gave the answer away.
export function HelpFriends({Diagram,refresh=0,teacher=false}:any){const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[open,setOpen]=useState(''),[answer,setAnswer]=useState(''),[hint,setHint]=useState(''),[penalise,setPenalise]=useState('');const hintId=useRef('');
useEffect(()=>{let stopped=false;const run=()=>loadBoard().then(d=>{if(!stopped){setData(d);setError('')}}).catch(e=>{if(!stopped)setError(e.message)});run();const t=setInterval(run,10000);return()=>{stopped=true;clearInterval(t)}},[refresh]);
function choose(id:string){setOpen(id);setAnswer('');setHint('');hintId.current=crypto.randomUUID()}
async function act(body:any,done:(r:any)=>void){setBusy(true);try{done(await helpAction(body))}catch(e){toast.error((e as Error).message)}try{setData(await loadBoard())}catch{}setBusy(false)}
return <section className="panel help-board" aria-labelledby="help-board-title"><div className="section-title"><h2 id="help-board-title"><HeartHandshake/> Help a friend with questions</h2><b>+{HELP_REWARD} coins when your friend gets it right</b></div><p>{teacher?`Pupils post questions they are stuck on. Friends must answer correctly before they can send a hint, and earn ${HELP_REWARD} coins only when the pupil then solves the question. Remove any unkind hint. If a hint gives the answer away, choose Gave the answer: the hint is removed and the helper loses ${ANSWER_PENALTY} coins, plus the ${HELP_REWARD} it earned if it was already paid.`:`Classmates post questions they are stuck on. Answer one correctly to unlock the hint box, then send a clue — not the answer. You earn ${HELP_REWARD} coins when your friend gets the question right, but if your teacher finds a hint that gives the answer away, you lose ${ANSWER_PENALTY} coins.`}</p>{error&&<p role="alert" className="error-banner">{error}</p>}{!teacher&&data?.mine>0&&<p className="help-mine">You have {data.mine} of {OPEN_HELP_REQUESTS} questions on the board. Hints from friends appear in your notebook below.</p>}
{!data?<p role="status">Loading questions from your class…</p>:!data.requests.length?<p>{teacher?'No pupil has asked for help yet.':'No one needs help right now. When classmates ask for a hint, their questions appear here.'}</p>:<div className="help-list">{data.requests.map((r:any)=><article className="help-card" key={r.id}><div className="section-title"><b>{r.name} {teacher?'asked':'asks'} · {r.question.subject} · {r.question.difficulty}</b><span>{teacher?r.status==='open'?'On the board':r.status==='full'?'Enough hints':'Closed':`${r.hints} of ${HINTS_PER_QUESTION} hints`}</span></div><h3>{r.question.prompt}</h3>
{teacher?(!r.hints.length?<p>No hints yet.</p>:<ul className="hint-list">{r.hints.map((h:any)=><li key={h.id}><div><b>{h.name}</b> <time dateTime={new Date(h.at).toISOString()}>{when(h.at)}</time>{h.paidAt&&!h.gaveAnswer&&<span>· earned {HELP_REWARD} coins</span>}{h.gaveAnswer&&<span className="hint-penalty">· gave the answer · lost {h.gaveAnswer.coins} coins</span>}{!h.removed&&penalise!==h.id&&<span className="hint-actions"><button className="quiet-button" disabled={busy} onClick={()=>act({action:'remove',id:r.id,hint:h.id},()=>toast.success('Hint removed.'))}>Remove</button><button className="quiet-button hint-penalise" disabled={busy} onClick={()=>setPenalise(h.id)}>Gave the answer</button></span>}</div>
{penalise===h.id&&!h.removed&&<div className="hint-confirm"><span>Remove this hint and take {answerPenalty(h)} coins from {h.name}{h.paidAt?` (${ANSWER_PENALTY}, plus the ${HELP_REWARD} it earned)`:''}?</span><button className="hint-fine" disabled={busy} onClick={()=>act({action:'gave_answer',id:r.id,hint:h.id},res=>{toast.success(`Hint removed. ${res.name} lost ${res.coins} coins.`);setPenalise('')})}>Take {answerPenalty(h)} coins</button><button className="quiet-button" disabled={busy} onClick={()=>setPenalise('')}>Cancel</button></div>}
<p>{h.gaveAnswer?<s>{h.text}</s>:h.removed?<i>Removed by teacher</i>:h.text}</p></li>)}</ul>)
:r.status==='sent'?<p className="help-note">{r.sent?<><CheckCircle2/><span>Hint sent. You earn {HELP_REWARD} coins when {r.name} gets it right.</span></>:r.lost!=null?`Your teacher removed your hint because it gave the answer away. You lost ${r.lost} coins.`:'Your teacher removed your hint.'}</p>
:r.status==='own'?<p className="help-note">This question is in your mistake notebook too. Solve it there first, then come back to help.</p>
:r.status==='active'?<p className="help-note">This is your current question in Earn coins. Answer it there first.</p>
:r.status==='resting'?<p className="help-note">Not quite this time. You can try this question again {when(r.retryAt)}.</p>
:open!==r.id?<button className="secondary-button" disabled={busy} onClick={()=>choose(r.id)}>{r.status==='unlocked'?`Write your hint for ${r.name}`:`Help ${r.name}`}</button>
:<div className="help-work">{r.status==='ready'&&<>{r.question.passage&&<blockquote className="passage">{r.question.passage}</blockquote>}{r.question.diagram&&<Diagram diagram={r.question.diagram}/>}<form onSubmit={e=>{e.preventDefault();act({action:'answer',id:r.id,answer},res=>res.correct?toast.success(`Correct! Now write a hint for ${r.name}.`):toast('Not quite. You can try this question again in 24 hours.'))}}>{r.question.options?<fieldset className="answer-options" disabled={busy}><legend>Solve it first to unlock the hint box</legend>{r.question.options.map((o:string,i:number,all:string[])=>{const lettered=all.every(x=>/^[A-Z]$/.test(x));return <label key={o} className={answer===o?'selected':''}><input type="radio" name={`help-${r.id}`} value={o} checked={answer===o} onChange={()=>setAnswer(o)}/><span className="option-letter">{lettered?o:String.fromCharCode(65+i)}</span>{!lettered&&<span>{o}</span>}</label>})}</fieldset>:<><label htmlFor={`help-answer-${r.id}`}>Solve it first to unlock the hint box</label><input id={`help-answer-${r.id}`} value={answer} onChange={e=>setAnswer(e.target.value)} maxLength={300} placeholder="Your answer" autoComplete="off" disabled={busy}/></>}<button className="primary" disabled={busy||!answer.trim()}>{busy?'Checking…':'Check my answer'}</button></form></>}
{r.status==='unlocked'&&<form onSubmit={e=>{e.preventDefault();act({action:'hint',id:r.id,hint:hintId.current,text:hint},()=>{toast.success(`Hint sent! You earn ${HELP_REWARD} coins when ${r.name} gets it right.`);setOpen('')})}}><label htmlFor={`help-hint-${r.id}`}>You solved it! Write a hint for {r.name}</label><textarea id={`help-hint-${r.id}`} value={hint} onChange={e=>setHint(e.target.value)} maxLength={HINT_MAX} rows={3} placeholder="Give a clue, not the answer. What should they try first?" required/><p className="help-warning">Clues only. If your teacher finds a hint that gives the answer away, you lose {ANSWER_PENALTY} coins.</p><div className="section-title"><span>{hint.length}/{HINT_MAX}</span><button className="primary" disabled={busy||!hint.trim()}>{busy?'Sending…':'Send hint'}</button></div></form>}<button type="button" className="quiet-button" onClick={()=>setOpen('')}>Close</button></div>}</article>)}</div>}
{!teacher&&data?.sentHints?.length>0&&<div className="sent-hints"><h3>Your hints</h3><ul className="hint-list">{data.sentHints.map((h:any)=><li key={h.id}><div><b>To {h.name} · {h.subject}</b> <time dateTime={new Date(h.at).toISOString()}>{when(h.at)}</time></div><p>{h.status==='removed'?<i>Removed by your teacher</i>:h.status==='answer'?<>“{h.text}” — <b className="hint-penalty">Your teacher removed this hint because it gave the answer away. You lost {h.lost} coins.</b></>:<>“{h.text}” —{h.status==='paid'?`${h.name} got it right! You earned ${HELP_REWARD} coins.`:`Waiting for ${h.name} to solve it.`}</>}</p></li>)}</ul></div>}</section>}
