'use client';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {StatsPanel} from './build-shop';
import dynamic from 'next/dynamic';
const EquippedHero3D=dynamic(()=>import('./equipped-hero-3d'),{ssr:false,loading:()=> <p>Loading your hero…</p>});
import {CLOTHING} from '@/lib/clothing';
import {VEHICLES} from '@/lib/vehicles';
import {ITEMS} from '@/lib/builds';
import {HEROES} from '@/lib/heroes';
import {equipment} from '@/lib/equipment';
export default function HeroProfile({player,defenders,onClose,focusId,battle,meId,onManage}:any){
 const heroes=defenders.filter((d:any)=>d.owner===player?.id).sort((a:any,b:any)=>Number(b.id===focusId)-Number(a.id===focusId)),level=Math.floor((player?.stats?.correct??0)/10)+1,focused=heroes.find((d:any)=>d.id===focusId),portraitRide=focused?.ride??heroes.find((d:any)=>d.ride)?.ride;
 const clothes=CLOTHING.filter(c=>player?.collection?.clothing?.includes(c.id)),rides=VEHICLES.filter(v=>player?.collection?.vehicles?.includes(v.id));
 const items=ITEMS.filter(i=>(player?.collection?.items?.[i.id]??0)>0);
 return <Dialog open={!!player} onOpenChange={o=>!o&&onClose()}><DialogContent className="hero-profile-dialog"><DialogTitle>{player?.name}’s hero</DialogTitle><DialogDescription>{player?HEROES[player.hero]?.name:''} · {player?.online?'Online now':'Offline'} · Adventurer level {level}</DialogDescription>{player&&<><div className="hero-profile-summary"><EquippedHero3D type={player.hero} clothing={player.clothing} uniform={player.uniform} gender={player.gender} ride={portraitRide}/><div className="profile-stats"><span><b>{level}</b>Adventurer level</span><span><b>{player.stats?.correct??0}</b>Correct answers</span><span><b>{player.stats?.kills??0}</b>Monsters defeated</span><span><b>{heroes.length}</b>Owned defenders</span></div></div><section className="profile-section"><h3>Combat builds & weapon levels</h3><p>Each defender has its own weapon level. Adventurer level comes from answering questions and is separate.</p>{heroes.map((d:any,i:number)=>{const live=battle?.fighters?.find((f:any)=>f.id===d.id),loadout=live??d;return <article key={d.id} className="profile-defender"><strong>{d.id===focusId?'Selected defender':`Defender ${i+1}`} · {d.cell<0?'In reserve':'On the map'}</strong><p>{d.level?`${equipment(d.weapon).name} · Weapon level ${d.level}/10`:'Unarmed · Weapon level 0'}</p>{live&&<p>Stats locked for the current battle.</p>}<StatsPanel type={d.type} level={d.level} weapon={d.weapon??'none'} loadout={loadout} stats={live?.stats}/><details><summary>Owned weapons</summary><div className="profile-collection">{(d.weapons??[]).map((id:string)=><span key={id}>{equipment(id).name} · Lv. {id===d.weapon?d.level:d.weaponLevels?.[id]??1}</span>)}</div></details>{player.id===meId&&onManage&&<button className="secondary-button" onClick={()=>onManage(d)}>Manage weapons & upgrades</button>}</article>})}{!heroes.length&&<p>No defenders placed yet. Combat stats become available once a defender is purchased.</p>}</section><section className="profile-section"><h3>Rides · {rides.length}</h3><div className="profile-collection">{rides.map(v=>{const who=heroes.find((d:any)=>d.ride?.id===v.id);return <span key={v.id}>{v.name}{who?` · Defender ${heroes.indexOf(who)+1}`:''}</span>})}</div>{!rides.length&&<p>No rides bought yet.</p>}</section><section className="profile-section"><h3>Wardrobe & accessories · {clothes.length}</h3><div className="profile-collection">{clothes.map(c=><span key={c.id}>{c.name}{player.clothing?.[c.slot]===c.id?' · Wearing':''}</span>)}</div>{!clothes.length&&<p>No clothing or accessories bought yet.</p>}</section><section className="profile-section"><h3>Items · {items.length}</h3><div className="profile-collection">{items.map(i=><span key={i.id}>{i.name} · Level {player.collection.items[i.id]}{player.collection.equippedItems?.includes(i.id)?' · Equipped':''}</span>)}</div>{!items.length&&<p>No items bought yet.</p>}</section></>}</DialogContent></Dialog>
}
