'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Shield,Swords,Coins,BookOpen,Sparkles,Trophy,Users,ArrowRight,ChevronRight,Check,Lock,Heart,Zap,LogOut,HelpCircle,CheckCircle2,XCircle,RefreshCw,Flag,Target,GraduationCap,Crown,Palette} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Progress} from '@/components/ui/progress';
import {Toaster,toast} from 'sonner';
import {CHAPTERS,chapterFor} from '@/lib/chapters';
import {HEROES,heroStats,upgradeCost} from '@/lib/heroes';
import GameBoard from './game-board';
import {COLS,RANGES} from '@/lib/battle';
const subjects=['Maths','English','Verbal reasoning','Non-verbal reasoning'];
const defenders=HEROES;
const empty={wave:1,power:0,target:170,contributors:0,players:[],defenders:[],me:null,battle:null,result:null,serverNow:0};
function Sprite({type=0,className='',outfit='classic'}:{type?:number;className?:string;outfit?:string}){return <span aria-hidden="true" className={`sprite sprite-${type} outfit-${outfit} ${className}`}/>}
function Diagram({diagram}:{diagram:any}){return <div className="diagram" aria-label="Pattern diagram">{diagram.items.map((n:number,i:number)=><div className="diagram-cell" key={i}><svg viewBox="0 0 100 100" role="img" aria-label={diagram.kind==='grid'?`Numbered 3 by 3 grid. Shaded positions: ${Array.from({length:9},(_,k)=>n&(1<<k)?k+1:null).filter(Boolean).join(', ')}`:diagram.kind==='dots'?`${n} dots`:diagram.kind==='arrows'?['up','right','down','left'][n]:`${n}-sided regular polygon`}>{diagram.kind==='grid'?Array.from({length:9},(_,k)=><g key={k}><rect x={5+k%3*30} y={5+Math.floor(k/3)*30} width="28" height="28" fill={n&(1<<k)?'#d0a300':'#153f34'} stroke="#aac7ac"/><text x={19+k%3*30} y={24+Math.floor(k/3)*30} textAnchor="middle" fontSize="13" fill={n&(1<<k)?'#142c22':'#eaf2dd'}>{k+1}</text></g>):diagram.kind==='dots'?Array.from({length:n},(_,k)=><circle key={k} cx={25+(k%4)*17} cy={12+Math.floor(k/4)*16} r="5" fill="#c9aff4"/>):diagram.kind==='arrows'?<path d="M50 14 26 40h16v42h16V40h16Z" fill="#b7ed77" transform={`rotate(${n*90} 50 50)`}/>:<polygon points={Array.from({length:n},(_,k)=>`${50+35*Math.cos(k*2*Math.PI/n-Math.PI/2)},${50+35*Math.sin(k*2*Math.PI/n-Math.PI/2)}`).join(' ')} fill="#c9aff422" stroke="#c9aff4" strokeWidth="3"/>}</svg></div>)}{diagram.items.length>1&&<div className="diagram-cell missing">?</div>}</div>}
async function api(url:string,data?:any){const r=await fetch(url,{...(data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{}),cache:'no-store'});const b:any=await r.json();if(!r.ok)throw new Error(b.error??'Something went wrong. Please try again.');return b}
export default function Home(){
 const [world,setWorld]=useState<any>(empty),[tab,setTab]=useState('world'),[auth,setAuth]=useState(false),[authMode,setAuthMode]=useState('login'),[name,setName]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[help,setHelp]=useState(false),[subject,setSubject]=useState('Maths'),[question,setQuestion]=useState<any>(null),[token,setToken]=useState(''),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState<any>(null),[questionMessage,setQuestionMessage]=useState(''),[now,setNow]=useState(Date.now()),[selected,setSelected]=useState<any>(null);
 const offset=useRef(0),inputRef=useRef<HTMLInputElement>(null),questionPending=useRef(false);
 const [placement,setPlacement]=useState<any>(null),[tilePicker,setTilePicker]=useState<number|null>(null);
 const [pupils,setPupils]=useState<any[]>([]),[pupilName,setPupilName]=useState(''),[pupilPassword,setPupilPassword]=useState(''),[resetName,setResetName]=useState(''),[teacherError,setTeacherError]=useState('');
 const me=world.me;const chapter=chapterFor(world.wave);
 const refresh=useCallback(async()=>{try{const data=await api('/api/game');offset.current=data.serverNow-Date.now();setWorld((old:any)=>old.serverNow>data.serverNow?old:data);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{refresh();const timer=setInterval(refresh,1500);return()=>clearInterval(timer)},[refresh]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()+offset.current),150);return()=>clearInterval(timer)},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'navigate_manor_quest',description:'Open the class world, coin-earning questions, hero customisation, achievements. Does not answer questions or spend coins.',inputSchema:{type:'object',properties:{view:{type:'string',enum:['world','practice','hero','achievements']}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!input||!['world','practice','hero','achievements'].includes(input.view))throw new Error('Unknown view');setTab(input.view);return{view:input.view}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 async function action(data:any,success?:string){if(!me&&!(world.isTeacher&&data.action==='battle')){setAuthMode('login');setAuth(true);return}setBusy(true);try{const r=await api('/api/game',data);if(r.world)setWorld(r.world);if(success)toast.success(success);return r}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 async function authenticate(e:React.FormEvent){e.preventDefault();setBusy(true);try{const login=await api('/api/account',{action:authMode,name,password});setPassword('');setAuth(false);await refresh();if(login.isTeacher)setTab('teacher');toast.success(login.isTeacher?'Welcome to your teacher area.':'Welcome back, adventurer!')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 async function logout(){setBusy(true);try{await api('/api/account',{action:'logout'});setQuestion(null);setFeedback(null);await refresh();setTab('world')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 async function nextQuestion(s=subject){if(!me){setAuthMode('login');setAuth(true);return}if(questionPending.current)return;questionPending.current=true;setBusy(true);try{const r=await api('/api/game',{action:'question',subject:s});setQuestion(r.question);setToken(r.token??'');setFeedback(null);setAnswer('');setQuestionMessage(r.message??'');setTimeout(()=>inputRef.current?.focus(),80)}catch(e){toast.error((e as Error).message)}finally{questionPending.current=false;setBusy(false)}}
 function startPractice(s=subject){setSubject(s);setTab('practice');if(me)nextQuestion(s);else setAuth(true)}
 async function submitAnswer(e:React.FormEvent){e.preventDefault();if(busy||feedback)return;const r=await action({action:'answer',token,answer});if(r){setFeedback(r);if(r.correct&&r.reward)toast.success(`Well done! +${r.reward} coins`)}}
 useEffect(()=>{if(tab==='practice'&&me&&!question&&!questionMessage&&!questionPending.current)nextQuestion()},[tab,me?.id]);
 async function loadPupils(){try{const r=await api('/api/teacher');setPupils(r.pupils);setTeacherError('')}catch(e){setTeacherError((e as Error).message)}}
 useEffect(()=>{if(tab==='teacher'&&world.isTeacher)loadPupils()},[tab,world.isTeacher,world.players.length]);
 async function savePupil(e:React.FormEvent){e.preventDefault();setBusy(true);try{await api('/api/account',{action:resetName?'teacher_reset':'teacher_create',name:resetName||pupilName,password:pupilPassword});toast.success(resetName?'Password reset. Share the new password with this pupil.':'Pupil account created. Share their nickname and password privately.');setPupilName('');setPupilPassword('');setResetName('');await loadPupils();await refresh()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 const liveBattle=world.battle;
 const battle=liveBattle,elapsed=battle?Math.min(1,Math.max(0,(now-battle.start)/battle.duration)):0;
 function chooseHero(type:number){if(!me){setAuthMode('login');setAuth(true);return}setPlacement({type});setTilePicker(null);setTab('world');setTimeout(()=>document.getElementById('class-map')?.scrollIntoView({behavior:'smooth',block:'center'}),50)}
 async function placeAt(cell:number){if(!me){setAuthMode('login');setAuth(true);return}if(!placement){setTilePicker(cell);return}const r=await action(placement.move?{action:'move',id:placement.move,cell}:{action:'recruit',type:placement.type,cell},placement.move?'Hero moved. Ready for the next wave!':'Your hero is on the map!');if(r)setPlacement(null)}
 function inspectHero(hero:any){if(hero.camp){toast(hero.name,{description:'This is their personal character. Their battle heroes defend the path.'});return}setSelected(hero)}
 const ready=world.power>=world.target&&world.contributors>=4;
 const ownDefenders=world.defenders.filter((d:any)=>d.owner===me?.id);
 const heading:any={teacher:['YOUR CLASS, READY TO PLAY','Assemble your squad.','Create pupil accounts, reset passwords and follow their progress.'],world:['THE MANOR PREPARATORY SCHOOL · ABINGDON','Manor heroes. Stronger together.','Answer questions. Recruit heroes. Defend your world.'],practice:['QUESTS THAT POWER YOUR CLASS','Answer. Earn. Recruit.','Every correct answer earns 20 coins to buy heroes for the shared battle.'],hero:['MAKE YOUR MARK','Your hero. Your style.','Choose your character and make them unmistakably yours.'],achievements:['EVERY STEP COUNTS','Look how far you’ve come.','Your answers, progress and proudest moments.']};
 return <main className="shell"><Toaster theme="dark" position="top-center" richColors/><header className="topbar"><a className="brand" href="/" aria-label="Manor Quest home"><Shield/><span className="brand-lockup"><strong>MANOR <em>QUEST</em></strong><small>THE MANOR PREPARATORY SCHOOL</small></span></a><nav aria-label="Main navigation">{[['world','Class world',Swords],['practice','Earn coins',Coins],['hero','My hero',Sparkles],['achievements','Achievements',Trophy]].map(([id,label,Icon]:any)=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon/>{label}</button>)}</nav><div className="top-actions">{world.isTeacher?<button className="account" onClick={()=>setTab('teacher')}><GraduationCap size={20}/> Teacher area</button>:me?<><span className="coin-wallet"><Coins size={18}/>{me.coins}<span className="sr-only"> coins</span></span><button className="account" onClick={()=>setTab('hero')}><Sprite type={me.hero} outfit={me.outfit}/><span>{me.name}</span></button></>:<button className="account" onClick={()=>setAuth(true)}>Pupil sign in <ArrowRight size={17}/></button>}</div></header>
 <section className="page-heading"><div><div className="eyebrow">{heading[tab][0]}</div><h1>{heading[tab][1]}</h1><p>{heading[tab][2]}</p></div><div className="class-label"><Users size={20}/><div><b>Manor Prep · Year 6</b><span>{world.players.length} / 40 adventurers</span></div></div></section>
 {error&&<div className="error-banner" role="alert">{error}<button onClick={refresh}><RefreshCw size={16}/> Retry</button></div>}
 {liveBattle&&tab!=='world'&&<button className="shared-battle-banner" onClick={()=>setTab('world')}><Swords size={20}/><span><b>Your class is fighting wave {world.wave}!</b> Everyone shares this battle. {Math.max(0,Math.ceil((liveBattle.duration-(now-liveBattle.start))/1000))}s remaining.</span><ArrowRight size={18}/></button>}
 {tab==='world'&&<div className="game-layout expanded-layout"><section><div className="world-card"><div className="world-header"><div><span className="eyebrow mint">CHAPTER {String(chapter.number).padStart(2,'0')} · {chapter.name}</span><h2>Defend The Manor</h2></div><span className="wave-pill"><Swords size={16}/> Wave {world.wave}</span></div>
 <div className="chapter-strip"><div><b>{chapter.boss?'Chapter boss':chapter.elite?'Elite wave':`Wave ${chapter.stage} of 10`}</b><span>{chapter.boss?'A giant slime joins the wave. Bring the class together!':chapter.elite?'Tougher monsters test your upgraded defence.':`Next boss: wave ${chapter.number*10} · Stronger enemies in every chapter`}</span></div><Progress value={(chapter.stage-1)*10} aria-label="Waves completed in this chapter"/><details className="chapter-roadmap"><summary>Chapter map · 300 waves +</summary><ol>{CHAPTERS.map((name,i)=><li key={name} className={chapter.number===i+1?'current':chapter.number>i+1?'complete':''}><b>{i+1}. {name}</b><span>Waves {i*10+1}–{i*10+10}{chapter.number>i+1?' · Cleared':chapter.number===i+1?' · Your chapter':''}</span></li>)}</ol><p>After chapter 30, Manor Legends continues with harder waves. Failed waves can always be retried.</p></details></div>
 <GameBoard world={world} battle={battle} now={now} placement={placement} onPlace={placeAt} onHero={inspectHero} onCancel={()=>setPlacement(null)} onHelp={()=>setHelp(true)}/>
 <div className="world-footer"><div className="power-icon"><Zap size={22}/></div><div className="power-details"><div><b>Class power <span>{world.power} <i>/ {world.target}</i></span></b><Progress aria-label="Class defence power" value={Math.min(100,world.power/world.target*100)} className="power-progress"/></div><span>Suggested power {world.target} · {world.contributors} / 4 classmates contributed</span></div><button disabled={busy||!!battle||loading||!!error} className="primary" onClick={()=>action({action:'battle'})}>{battle?<><Swords size={16}/>{Math.max(0,Math.ceil((battle.duration-(now-battle.start))/1000))}s remaining</>:<><Swords size={16}/>{world.result&&!world.result.won?'Retry wave':'Start wave'}</>}</button></div></div>
 {world.result&&!battle&&<div className={`battle-result ${world.result.won?'won':''}`} role="status">{world.result.won?<Trophy size={23}/>:<Shield size={23}/>}<div><b>{world.result.won?`Wave ${world.result.wave} cleared. Brilliant teamwork!`:`Wave ${world.result.wave} needs a little more teamwork.`}</b><p>{world.result.won?'Your heroes stay with you. Answer new questions to prepare for the next wave.':`${world.result.killed} / ${world.result.count} monsters defeated · ${world.result.contributors} / 4 contributors. Reposition heroes, earn more coins and retry.`}</p></div></div>}
 <div className="section-title"><h2>Buy heroes & towers for your class</h2><span>{ownDefenders.length} / 3 in your team</span></div><div className="defender-grid">{defenders.map((d,i)=><article className={`defender-card card-${i}`} key={d.name}><Sprite type={i} className="recruit-sprite"/><div><span className="eyebrow">{d.role} · <Zap size={11}/>{d.power}</span><h3>{d.name}</h3><p>{d.description}</p><button disabled={busy||!!me&&(me.coins<d.price||ownDefenders.length>=3)} onClick={()=>chooseHero(i)}><Coins size={14}/>{d.price}<span>Recruit</span></button></div></article>)}</div>
 {ownDefenders.length>0&&<div className="your-team"><span>Your battle heroes</span>{ownDefenders.map((d:any)=><button key={d.id} onClick={()=>setSelected(d)}>{defenders[d.type].name} <span>Lv. {d.level}</span><ChevronRight size={14}/></button>)}</div>}
 </section><aside className="right-column"><article className="practice-card"><span className="eyebrow mint">KNOWLEDGE IS YOUR SUPERPOWER</span><div className="practice-symbol"><BookOpen size={35}/><Sparkles size={22}/></div><h2>Big brains. <br/>Brave heroes.</h2><p>Answer questions. Earn coins. Buy heroes & towers for your class.</p><button className="primary" onClick={()=>startPractice()}>Earn coins <ArrowRight size={18}/></button><span className="reward"><Coins size={16}/> +20 coins per correct answer</span></article>
 <article className="panel squad-panel"><div className="panel-heading"><h3><Users size={18}/> Your squad</h3><span>{world.players.length}/40</span></div>{world.players.length?<><div className="squad-avatars">{world.players.slice(0,8).map((p:any)=><div key={p.id} title={p.name}><Sprite type={p.hero} outfit={p.outfit}/></div>)}{world.players.length>8&&<span>+{world.players.length-8}</span>}</div><p>{world.contributors>=4?'Teamwork goal reached. Position and upgrade your heroes to protect the route.':`${Math.max(0,4-world.contributors)} more classmates need to answer a question this wave.`}</p></>:<p>Every adventure starts with someone. Your teacher will create your account so you can join the squad.</p>}<div className="note"><Shield size={20}/><span>Lost a wave? Keep your heroes and try again. No starting over.</span></div></article>
 </aside></div>}
 {tab==='practice'&&<div className="practice-layout"><section><div className="subject-grid">{subjects.map((s,i)=><button disabled={busy} key={s} className={`subject subject-${i} ${subject===s?'selected':''}`} onClick={()=>{setSubject(s);nextQuestion(s)}}><span>{[<GraduationCap key="m"/>,<BookOpen key="e"/>,<Sparkles key="v"/>,<Target key="n"/>][i]}</span><b>{s}</b>{subject===s&&<Check size={17}/>}</button>)}</div>
 <article className="question-card">{!me?<div className="practice-empty"><BookOpen size={42}/><h2>Your first quest is waiting.</h2><p>Use the nickname and password your teacher gave you to earn coins for your class.</p><button className="primary" onClick={()=>setAuth(true)}>Pupil sign in <ArrowRight size={18}/></button></div>:!question?<div className="practice-empty"><Sparkles size={40}/><h2>{questionMessage?'A brilliant bit of exploring.':'Ready to warm up your brain?'}</h2><p>{questionMessage||`Your ${subject.toLowerCase()} quest is ready. Take your time and give it your best shot.`}</p><button className="primary" disabled={busy} onClick={()=>nextQuestion()}>{busy?'Finding your question…':'Find a question'}<ArrowRight size={17}/></button></div>:<><div className="question-meta"><span className="subject-tag">{question.subject}</span><span><Coins size={16}/>{'+20 coins'}</span></div>{question.passage&&<blockquote className="passage">{question.passage}</blockquote>}{question.diagram&&<Diagram diagram={question.diagram}/>}<h2>{question.prompt}</h2><form onSubmit={submitAnswer}>{question.options?<fieldset className="answer-options" disabled={busy||!!feedback}><legend>Choose one answer</legend>{question.options.map((option:string,i:number)=><label key={option} className={answer===option?'selected':''}><input type="radio" name="question-answer" value={option} checked={answer===option} onChange={()=>setAnswer(option)}/><span className="option-letter">{String.fromCharCode(65+i)}</span><span>{option}</span></label>)}</fieldset>:<><label htmlFor="answer">Your answer</label><input id="answer" ref={inputRef} value={answer} onChange={e=>setAnswer(e.target.value)} maxLength={300} placeholder="Type your answer here…" autoComplete="off" disabled={busy||!!feedback}/></>}<button className="primary submit-question" disabled={busy||!!feedback||!answer.trim()} type="submit">{busy?'Checking…':'Check answer'}<ArrowRight size={17}/></button></form>{feedback?<div className={`answer-feedback ${feedback.correct?'correct':'incorrect'}`} role="status">{feedback.correct?<CheckCircle2/>:<BookOpen/>}<div><h3>{feedback.correct?'You’ve got it!':'A chance to learn something new.'}</h3>{!feedback.correct&&<p>The answer is <b>{feedback.answer}</b>.</p>}<p>{feedback.explanation}</p><span>{feedback.correct?(feedback.reward?`+${feedback.reward} coins for your team.`:'Your answer is saved.'):'No coins lost. This question will rest for at least 24 hours.'}</span><button onClick={()=>nextQuestion()} disabled={busy}>Next question <ArrowRight size={17}/></button></div></div>:<p className="question-tip">No timer. Think it through — your best effort is what matters.</p>}</>}
 </article></section><aside className="right-column"><article className="panel"><h3><Coins size={19}/> Your quest rewards</h3><div className="big-number">{me?.coins??0}<span>coins to spend</span></div><button className="secondary-button" onClick={()=>setTab('world')}>Buy heroes <ArrowRight size={16}/></button><div className="note"><Users size={18}/><span>Every correct answer earns 20 coins. Spend them on heroes or upgrades to strengthen your whole class.</span></div></article><article className="panel"><h3><Shield size={18}/> A fresh challenge</h3><p>Questions you get right won’t come back. Missed questions rest for at least 24 hours, so you can return with a fresh mind.</p><p>Different classmates can get the same question. Your progress is your own.</p></article></aside></div>}
 {tab==='hero'&&(!me?<SignInPrompt onClick={()=>setAuth(true)}/>:<div className="hero-layout"><article className="hero-showcase"><span className="eyebrow mint">YOUR ADVENTURE STARTS WITH YOU</span><Sprite type={me.hero} outfit={me.outfit} className="showcase-sprite"/>{me.outfit==='royal'&&<Crown className="royal-crown"/>}<h2>{me.name}</h2><span className="hero-level">Level {Math.floor(me.correct/10)+1} adventurer</span><p>Your hero appears in the class world.<br/>Your battle heroes do the fighting.</p><div className="hero-stat"><span><b>{me.correct}</b>Correct answers</span><span><b>{ownDefenders.length}</b>Defenders</span></div><button className="quiet-button" disabled={busy} onClick={logout}><LogOut size={16}/> Sign out</button></article><section><div className="section-title"><h2>Choose your character</h2><span>All starting characters are free</span></div><div className="hero-choices">{defenders.slice(0,7).map((d,i)=><button disabled={busy} className={me.hero===i?'chosen':''} key={d.name} onClick={()=>action({action:'hero',hero:i},'Your hero is ready!')}><Sprite type={i}/><b>{d.name}</b><span>{d.role}</span>{me.hero===i&&<CheckCircle2 size={20}/>}</button>)}</div><div className="section-title"><h2>Make it your own</h2><span><Coins size={14}/> {me.coins} coins</span></div><div className="outfit-grid">{[['classic','Forest original',0],['moonlight','Moonlight cloak',80],['sunset','Sunset colours',80],['royal','Royal glow',120]].map(([id,label,price]:any)=><button disabled={busy||!me.owned.includes(id)&&me.coins<price} key={id} className={me.outfit===id?'chosen':''} onClick={()=>action({action:'outfit',outfit:id},'Looking good, adventurer!')}><Sprite type={me.hero} outfit={id}/><b>{label}</b><span>{me.outfit===id?<><Check size={15}/> Equipped</>:me.owned.includes(id)?'Equip outfit':<><Coins size={14}/>{price}</>}</span></button>)}</div><div className="note"><Palette size={20}/><span>Outfits are just for fun. Every hero starts with the same chance to succeed.</span></div></section></div>)}
 {tab==='achievements'&&(!me?<SignInPrompt onClick={()=>setAuth(true)}/>:<><div className="stats-grid"><div><CheckCircle2/><b>{me.correct}</b><span>Correct answers</span></div><div><BookOpen/><b>{me.incorrect}</b><span>Learning moments</span></div><div><Target/><b>{me.correct+me.incorrect?Math.round(me.correct/(me.correct+me.incorrect)*100):0}%</b><span>Accuracy</span></div><div><Flag/><b>{world.wave-1}</b><span>Class waves cleared</span></div></div><div className="section-title"><h2>Your adventure badges</h2><span>Little steps. Big victories.</span></div><div className="badge-grid">{[{name:'First spark',text:'Answer your first question correctly.',done:me.correct>=1,icon:Sparkles},{name:'Brain power',text:'Get 25 questions right.',done:me.correct>=25,icon:GraduationCap},{name:'Centurion',text:'Get 100 questions right.',done:me.correct>=100,icon:Trophy},{name:'Squad builder',text:'Recruit your first defender.',done:ownDefenders.length>=1,icon:Shield},{name:'Curious mind',text:'Get an answer right in all 4 subjects.',done:subjects.every(s=>me.subjects[s]?.correct>0),icon:BookOpen},{name:'Victory together',text:'Clear a wave as a class.',done:world.wave>1,icon:Flag}].map(b=><article className={`badge-card ${b.done?'unlocked':''}`} key={b.name}><div className="badge-medal"><b.icon size={32}/></div><h3>{b.name}</h3><p>{b.text}</p><span>{b.done?<><Check size={14}/> Unlocked</>:<><Lock size={13}/> Keep exploring</>}</span></article>)}</div><div className="section-title"><h2>Your subject progress</h2></div><div className="subject-progress">{subjects.map(s=>{const p=me.subjects[s]??{correct:0,incorrect:0};return <article className="panel" key={s}><h3>{s}</h3><Progress value={p.correct+p.incorrect?p.correct/(p.correct+p.incorrect)*100:0} aria-label={`${s} accuracy`} className="power-progress"/><p><b>{p.correct}</b> correct · <b>{p.incorrect}</b> to learn from</p></article>})}</div></>)}
 {tab==='teacher'&&(world.isTeacher?<div className="teacher-layout"><section className="panel teacher-create"><h2>{resetName?'Reset pupil password':'Create a pupil account'}</h2><p>Use nicknames rather than real names. Give each pupil their sign-in details privately.</p><form onSubmit={savePupil}><label htmlFor="pupil-name">Pupil nickname</label><input id="pupil-name" value={resetName||pupilName} disabled={!!resetName} onChange={e=>setPupilName(e.target.value)} placeholder="e.g. foxexplorer" pattern="[a-zA-Z][a-zA-Z0-9_-]{2,19}" maxLength={20} required/><label htmlFor="pupil-password">{resetName?'New password':'Pupil password'}</label><input id="pupil-password" type="text" autoComplete="off" value={pupilPassword} onChange={e=>setPupilPassword(e.target.value)} placeholder="At least 5 characters" minLength={5} maxLength={100} required/><p className="field-note">Make a note before saving. Passwords cannot be viewed later, but you can reset them here.</p><button className="primary" disabled={busy||(!resetName&&pupils.length>=40)}>{busy?'Saving…':resetName?'Save new password':'Create pupil account'}<ArrowRight size={17}/></button>{resetName&&<button className="quiet-button" type="button" onClick={()=>{setResetName('');setPupilPassword('')}}>Cancel password reset</button>}</form><div className="note"><Users size={20}/><span>{pupils.length} / 40 pupil accounts. Everyone joins the same class world and the same wave.</span></div><button className="quiet-button" onClick={logout}><LogOut size={16}/> Sign out of teacher area</button></section><section className="panel register-panel"><div className="section-title"><h2>Your class register</h2><button className="quiet-button" onClick={loadPupils}><RefreshCw size={15}/> Refresh</button></div>{teacherError&&<p className="error-banner">{teacherError}</p>}{pupils.length?<Table><TableHeader><TableRow><TableHead>Pupil</TableHead><TableHead>Correct</TableHead><TableHead>Incorrect</TableHead><TableHead>Coins</TableHead><TableHead><span className="sr-only">Manage</span></TableHead></TableRow></TableHeader><TableBody>{pupils.map(p=><TableRow key={p.id}><TableCell><span className="register-name"><Sprite type={p.hero}/>{p.name}</span></TableCell><TableCell>{p.correct}</TableCell><TableCell>{p.incorrect}</TableCell><TableCell>{p.coins}</TableCell><TableCell><button className="reset-button" onClick={()=>{setResetName(p.name);setPupilPassword('')}}>Reset password</button></TableCell></TableRow>)}</TableBody></Table>:<div className="register-empty"><Users size={35}/><h3>Your squad starts here.</h3><p>Create the first pupil account to begin. Pupils cannot register themselves.</p></div>}</section></div>:<SignInPrompt onClick={()=>{setAuthMode('teacher_login');setAuth(true)}}/>)}
 <footer><button onClick={()=>{if(world.isTeacher)setTab('teacher');else{setAuthMode('teacher_login');setAuth(true)}}}><GraduationCap size={14}/> Teacher area</button><button onClick={()=>setHelp(true)}><HelpCircle size={14}/> How to play</button><span>Challenge. Cherish. Inspire.</span></footer>
 <Dialog open={auth} onOpenChange={o=>{setAuth(o);if(!o){setAuthMode('login');setPassword('')}}}><DialogContent className="auth-dialog"><div className="auth-mark"><Shield size={30}/></div><DialogTitle className="modal-title">{authMode==='teacher_login'?'Your teacher area.':'Your squad is waiting.'}</DialogTitle><DialogDescription>{authMode==='teacher_login'?'Enter your private teacher password to manage pupil accounts.':'Sign in with the nickname and password your teacher gave you.'}</DialogDescription><form onSubmit={authenticate}>{authMode!=='teacher_login'&&<><label htmlFor="nickname">Adventurer nickname</label><input id="nickname" value={name} onChange={e=>setName(e.target.value)} placeholder="Your nickname" autoComplete="username" maxLength={20} required/></>}<label htmlFor="password">{authMode==='teacher_login'?'Teacher password':'Password'}</label><input id="password" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Your password" minLength={5} maxLength={100} autoComplete="current-password" required/><button className="primary" disabled={busy} type="submit">{busy?'Signing in…':authMode==='teacher_login'?'Open teacher area':'Enter the adventure'}<ArrowRight size={17}/></button></form><p className="auth-footnote">{authMode==='teacher_login'?'Keep your teacher password private. Pupils use their own accounts.':'Need your nickname or a new password? Ask your teacher.'}</p></DialogContent></Dialog>
 <Dialog open={tilePicker!==null} onOpenChange={o=>!o&&setTilePicker(null)}><DialogContent><DialogTitle className="modal-title">Choose a hero or tower for this square</DialogTitle><DialogDescription>Row {tilePicker===null?'':Math.floor(tilePicker/COLS)+1}, column {tilePicker===null?'':tilePicker%COLS+1} · {me?.coins??0} coins</DialogDescription><div className="tile-hero-list">{defenders.map((d,i)=><button disabled={busy||!me||me.coins<d.price||ownDefenders.length>=3} key={d.name} onClick={async()=>{const r=await action({action:'recruit',type:i,cell:tilePicker},'Your hero is on the map!');if(r)setTilePicker(null)}}><Sprite type={i}/><span><b>{d.name}</b><small>{RANGES[i]} square range · {d.power} damage</small></span><strong><Coins size={16}/>{d.price}</strong></button>)}</div>{me?.coins<60&&<button className="primary" onClick={()=>{setTilePicker(null);startPractice()}}>Answer questions to earn coins <ArrowRight size={17}/></button>}</DialogContent></Dialog>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="help-dialog"><DialogTitle className="modal-title">One class. One quest.</DialogTitle><DialogDescription>Every hero has a part to play.</DialogDescription><ol className="how-list"><li><BookOpen/><div><b>Put your brain to work</b><p>Choose a subject, then type an answer or choose an option. Earn 20 coins for every correct answer, then use them to buy heroes.</p></div></li><li><Shield/><div><b>Build your defence</b><p>Recruit up to 3 heroes or towers and choose empty grass squares for them. Each hero has its own range, attack speed and special role. Move and upgrade your heroes between waves.</p></div></li><li><Users/><div><b>Rally the squad</b><p>At least 4 classmates must answer correctly each wave. Place your heroes near the path, then start the battle. Range and positioning matter.</p></div></li><li><Swords/><div><b>Keep going, together</b><p>Every chapter has 10 waves: an elite wave at 5 and a boss at 10. Later chapters bring more, tougher and faster monsters. Lose a wave? Your coins and defenders stay. Prepare and retry.</p></div></li></ol><p className="help-small">Each hero attacks monsters within range of its square. The battle starts with a snapshot of everyone’s heroes and contributions. New recruits join the next battle.</p></DialogContent></Dialog>
 <Dialog open={!!selected} onOpenChange={o=>!o&&setSelected(null)}><DialogContent className="hero-detail-dialog"><DialogTitle className="modal-title">{selected&&defenders[selected.type].name} · Level {selected?.level}</DialogTitle><DialogDescription>{selected?.name}’s defender</DialogDescription>{selected&&<><Sprite type={selected.type} className="detail-sprite"/><ol className="upgrade-path">{defenders[selected.type].tiers.map((tier,i)=><li key={tier} className={selected.level>=i+1?'unlocked':''}><b>{i+1}. {tier}</b><span>{i===0?defenders[selected.type].description:defenders[selected.type].upgrade[i-1]}</span><small>{heroStats(selected.type,i+1).damage} damage · {heroStats(selected.type,i+1).range} range · {heroStats(selected.type,i+1).cooldown.toFixed(2)}s{ i>0?` · ${defenders[selected.type].costs[i-1]} coins`:''}</small></li>)}</ol><p className="detail-power"><Zap/> {heroStats(selected.type,selected.level).damage} damage · {heroStats(selected.type,selected.level).range} square range · {heroStats(selected.type,selected.level).cooldown.toFixed(2)}s between attacks</p>{selected.owner===me?.id?<><button className="primary" disabled={busy||!!liveBattle||selected.level>=3||me.coins<(upgradeCost(selected.type,selected.level)??0)} onClick={async()=>{const r=await action({action:'upgrade',id:selected.id},'Defender upgraded!');if(r)setSelected(r.world.defenders.find((d:any)=>d.id===selected.id))}}><Coins size={18}/>{selected.level>=3?'Fully upgraded':`Upgrade to ${defenders[selected.type].tiers[selected.level]} · ${upgradeCost(selected.type,selected.level)} coins`}</button><button className="secondary-button" disabled={!!liveBattle} onClick={()=>{setPlacement({type:selected.type,move:selected.id,level:selected.level});setSelected(null);setTab('world')}}>Move to another square · Free</button></>:<p className="muted">This defender belongs to your classmate. Recruit your own to add to the team.</p>}</>}</DialogContent></Dialog>
 </main>
}
function SignInPrompt({onClick}:{onClick:()=>void}){return <section className="signin-prompt"><Shield size={45}/><h2>Your adventure, saved.</h2><p>Sign in with the nickname and password your teacher gave you to join the shared class world.</p><button className="primary" onClick={onClick}>Pupil sign in <ArrowRight size={18}/></button></section>}
