'use client';
import type {ReactNode} from 'react';
import {Coins,Star,Swords,Zap,Eye,ChevronsRight,Snowflake,Bomb,Wind,Snail,Repeat,Clover,Dumbbell,Target,Heart,Paintbrush,BookOpen,Bell,Flame,Crosshair,WandSparkles,Crown,Sparkles,type LucideIcon} from 'lucide-react';
import {toast} from 'sonner';
import type {Mods} from '@/lib/builds';
import {MOD_WORDS,modAmount} from '@/lib/item-guide';
// Picture-first pieces shared by the Quest Shop, the backpack and the hero dialog. Numbers stay available under "See all the numbers".
export const WEAPON_ICONS:Record<string,LucideIcon>={standard:ChevronsRight,swift:Zap,frost:Snowflake,blast:Bomb,ruler:Wind,glue:Snail,tennis:Repeat,basketball:Bomb,cricket:Clover,pingpong:Zap,rugby:Dumbbell,badminton:Snail,fork:Target,teddy:Heart,paint:Paintbrush,book:BookOpen,bell:Bell,eraser:Flame};
export const WEAPON_KINDS:Record<string,{label:string;icon:LucideIcon}>={str:{label:'Strength',icon:Dumbbell},aim:{label:'Aim',icon:Crosshair},magic:{label:'Magic',icon:WandSparkles}};
const MOD_ICONS:Record<keyof Mods,LucideIcon>={str:Dumbbell,aim:Crosshair,magic:WandSparkles,damage:Swords,speed:Zap,range:Eye,crit:Clover,critDamage:Sparkles,area:Bomb,control:Snowflake,dot:Paintbrush,boss:Crown,normal:Target,single:Target};
const shortBy=(price:number,me:any)=>me.unlimitedCoins?0:Math.max(0,price-me.coins);
export const canAfford=(price:number,me:any)=>shortBy(price,me)===0;
export function Price({price,me}:{price:number;me:any}){const short=shortBy(price,me);return <span className={`price-tag ${short?'short':''}`}><Coins aria-hidden="true"/>{price.toLocaleString()}<span className="sr-only"> coins</span>{short>0&&<small>Need {short.toLocaleString()} more</small>}</span>}
// Turns "not enough coins" into a goal: how far along the pupil is, and roughly how many correct answers are left.
export function SaveUp({price,me,onEarn}:{price:number;me:any;onEarn?:()=>void}){const short=shortBy(price,me);if(!short)return null;return <div className="save-up"><div className="save-track" aria-hidden="true"><i style={{width:`${Math.min(100,me.coins/price*100)}%`}}/></div><p>You have {me.coins.toLocaleString()} of {price.toLocaleString()} coins. About {Math.ceil(short/20)} more correct {Math.ceil(short/20)===1?'answer':'answers'} will get you there!</p>{onEarn&&<button className="secondary-button" onClick={onEarn}><Coins aria-hidden="true"/>Earn coins</button>}</div>}
export function Ribbon({kind,children}:{kind:'equipped'|'owned';children:ReactNode}){return <span className={`ribbon ${kind}`}>{children}</span>}
export function Stars({level,max=3}:{level:number;max?:number}){return <span className="stars" role="img" aria-label={`Level ${level} of ${max}`}>{Array.from({length:max},(_,i)=><Star key={i} className={i<level?'on':''} aria-hidden="true"/>)}</span>}
export function LevelTrack({level,max=10}:{level:number;max?:number}){return <div className="level-track" role="img" aria-label={`Level ${level} of ${max}`}>{Array.from({length:max},(_,i)=>{const n=i+1,special=n===3||n===6||n===10;return <span key={n} className={`${n<=level?'on':''} ${special?'special':''}`}>{special&&<Star aria-hidden="true"/>}</span>})}</div>}
const BARS:[string,string,LucideIcon,(s:any)=>number,number,(v:number)=>string][]=[['Power','Damage from each hit',Swords,s=>s.damage,90,v=>String(Math.round(v))],['Speed','Attacks each second',Zap,s=>s.damage?1/s.cooldown:0,3,v=>v.toFixed(1)],['Reach','How many squares away it can hit',Eye,s=>s.range,8,v=>v.toFixed(1)]];
// Three simple bars instead of DPS tables; a thin mark shows where the hero is now.
export function PowerBars({stats,compare}:{stats:any;compare?:any}){return <div className="power-bars">{BARS.map(([label,title,Icon,get,max,fmt])=>{const v=get(stats),c=compare?get(compare):null,d=c===null?0:v-c;return <div className="power-bar" key={label} title={title}><span className="power-label"><Icon aria-hidden="true"/>{label}</span><span className="power-track" aria-hidden="true"><i style={{width:`${Math.min(100,v/max*100)}%`}}/>{c!==null&&Math.abs(d)>.01&&<em style={{left:`${Math.min(100,c/max*100)}%`}}/>}</span><b>{fmt(v)}{Math.abs(d)>=.05&&<small className={d>0?'up':'down'}>{d>0?'+':'−'}{fmt(Math.abs(d))}</small>}</b></div>})}</div>}
export function ModChips({mods,limit,good=false}:{mods:Mods;limit?:number;good?:boolean}){const entries=Object.entries(mods).filter(([,v])=>v&&(!good||v>0)).sort((a,b)=>Number(b[1]!>0)-Number(a[1]!>0)).slice(0,limit);return <span className="mod-chips">{entries.map(([k,v])=>{const Icon=MOD_ICONS[k as keyof Mods];return <span key={k} className={`mod-chip ${v!>0?'up':'down'}`}><Icon aria-hidden="true"/>{MOD_WORDS[k as keyof Mods]} {modAmount(k,v!)}</span>})}</span>}
export function celebrate(text:string,art?:string){toast.success(text,art?{icon:<img src={art} alt="" className="toast-art"/>}:undefined)}
