import {env} from 'cloudflare:workers';
import {db,sha,user,requireOrigin,json,mutate,newPlayer} from '@/lib/world';
async function hash(password:string,salt:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},key,256);return Array.from(new Uint8Array(bits)).map(b=>b.toString(16).padStart(2,'0')).join('')}
async function session(req:Request,uid:string){const token=crypto.randomUUID()+crypto.randomUUID();await db().prepare('INSERT INTO sessions (token,user_id,expires) VALUES (?,?,?)').bind(await sha(token),uid,Date.now()+7*86400000).run();return Response.json({ok:true,isTeacher:uid==='teacher'},{headers:{'Set-Cookie':`qg_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800${new URL(req.url).protocol==='https:'?'; Secure':''}`,'Cache-Control':'no-store'}})}
export async function POST(req:Request){try{requireOrigin(req);const b:any=await req.json();if(b.action==='logout'){const c=req.headers.get('cookie')?.match(/(?:^|;\s*)qg_session=([^;]+)/)?.[1];if(c)await db().prepare('DELETE FROM sessions WHERE token=?').bind(await sha(c)).run();return Response.json({ok:true},{headers:{'Set-Cookie':'qg_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0','Cache-Control':'no-store'}})}
if(!['login','teacher_login','teacher_create','teacher_reset'].includes(b.action))return json({error:'Pupil accounts are created by your teacher. Please sign in.'},403);
const teacherAction=b.action==='teacher_create'||b.action==='teacher_reset';if(teacherAction&&await user(req)!=='teacher')return json({error:'Only your teacher can create or reset pupil accounts.'},403);
const name=b.action==='teacher_login'?'teacher':String(b.name??'').trim().toLowerCase(),pass=String(b.password??'');if(!/^[a-z][a-z0-9_-]{2,19}$/.test(name)||pass.length<5||pass.length>100)return json({error:'Use a 3–20 character nickname (letters, numbers, _ or -) and a password of at least 5 characters.'},400);
const now=Date.now();const key=await sha((req.headers.get('cf-connecting-ip')??'local')+':'+name);if(!teacherAction){await db().prepare('INSERT INTO auth_attempts (key,count,reset) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN reset<? THEN 1 ELSE count+1 END, reset=CASE WHEN reset<? THEN excluded.reset ELSE reset END').bind(key,now+900000,now,now).run();const rate=await db().prepare('SELECT count FROM auth_attempts WHERE key=?').bind(key).first<{count:number}>();if((rate?.count??0)>10)return json({error:'Too many sign-in attempts. Try again in 15 minutes.'},429)}
if(b.action==='teacher_login'){if(!env.TEACHER_PASSWORD||await sha(pass)!==await sha(env.TEACHER_PASSWORD))return json({error:'That teacher password does not match.'},401);await db().prepare('DELETE FROM auth_attempts WHERE key=?').bind(key).run();return session(req,'teacher')}
if(teacherAction){if(name==='teacher')return json({error:'Choose a pupil nickname other than teacher.'},400);const salt=crypto.randomUUID(),password=await hash(pass,salt);if(b.action==='teacher_reset'){const row=await db().prepare('SELECT id FROM accounts WHERE nickname=?').bind(name).first<{id:string}>();if(!row)return json({error:'That pupil could not be found.'},404);await db().batch([db().prepare('UPDATE accounts SET password=?,salt=? WHERE id=?').bind(password,salt,row.id),db().prepare('DELETE FROM sessions WHERE user_id=?').bind(row.id),db().prepare('DELETE FROM auth_attempts WHERE key=?').bind(key)]);return json({ok:true})}
const id=crypto.randomUUID();try{const r=await db().prepare('INSERT INTO accounts (id,nickname,password,salt,created) SELECT ?,?,?,?,? WHERE (SELECT COUNT(*) FROM accounts)<40').bind(id,name,password,salt,now).run();if(!r.meta.changes)return json({error:'This squad is full (40 pupils).'},400)}catch{return json({error:'That nickname is already in use.'},400)}await mutate(w=>{w.players[id]=newPlayer(name)});return json({ok:true})}
const row=await db().prepare('SELECT id,password,salt FROM accounts WHERE nickname=?').bind(name).first<{id:string;password:string;salt:string}>();const candidate=await hash(pass,row?.salt??'unknown-account');if(!row||candidate!==row.password)return json({error:'That nickname and password do not match. Ask your teacher if you need help.'},401);await mutate(w=>{if(!w.players[row.id])w.players[row.id]=newPlayer(name)});await db().prepare('DELETE FROM auth_attempts WHERE key=?').bind(key).run();return session(req,row.id);
}catch(e){console.error('Account request failed',e);return json({error:'Unable to save the account just now. Please try again.'},503)}}
