import type {Topic} from './bank-kit';
import {mc,item,science,sorted,quick,challenge} from './bank-science-kit';
// Science: working scientifically — variables, fair tests, repeat readings, anomalies, tables, graphs and conclusions.

const enquiryTopic:Topic={id:'sc-working-scientifically',subject:'Science',strand:'Working scientifically',title:'Working scientifically',helpsheet:{
 intro:'In a **fair test** you change one thing, measure one thing and keep everything else the same. Then you look for a pattern in the results.',
 steps:['Choose the variable to **change** (the independent variable).','Decide what to **measure** (the dependent variable), and how.','Keep all the other variables the **same** (the control variables).','Repeat your measurements and look out for **anomalous** results that do not fit the pattern.','Write a **conclusion** that describes the pattern, such as "the longer …, the slower …".'],
 example:{title:'Paper helicopters',visual:{kind:'table',head:['Wing length (cm)','Time to fall (s)'],rows:[['4','1.2'],['6','1.6'],['8','2.1'],['10','2.5']],alt:'A results table of wing length and falling time for paper helicopters'},lines:['Changed: wing length. Measured: time to fall. Kept the same: drop height, type of paper, paper clip.','Conclusion: the longer the wings, the longer the helicopter takes to fall.']},
 tips:['Only change **one** thing at a time, or you cannot tell which change caused the result.','An anomalous result does not fit the pattern. Check it and repeat it rather than just ignoring it.','Use a line graph for something that changes continuously, such as over time; use a bar chart for separate groups.','The mean is the total of the results divided by how many results there are.']}};

const enquiry=science(enquiryTopic,[
 item(mc('Maya wants to find out whether the height a ball is dropped from affects how high it bounces. What should she **change**?','The height the ball is dropped from',['The height the ball bounces back up to','The type of ball she drops','The kind of floor it bounces on'],
  ['The variable you **change** is the one you are testing: the drop height.','She **measures** the bounce height, and keeps the ball and the floor the **same** so the test is fair.'])),
 item(mc('Ben tests how the temperature of water affects how quickly sugar dissolves in it. What should he **measure**?','The time the sugar takes to dissolve',['The temperature of the water in each cup','The amount of sugar he adds each time','The size of the cup he uses'],
  ['He wants to know **how quickly** the sugar dissolves, so he measures the **time** it takes.','He **changes** the water temperature and keeps the amount of sugar and the cup the **same**.'])),
 item(mc('Hana tests which type of paper towel soaks up the most water. What must she keep the **same** for a fair test?','The size of each paper towel',['The type of paper towel','The amount of water each towel soaks up','How many types of towel she tests'],
  ['She is **changing** the type of towel and **measuring** how much water each one soaks up.','Everything else, such as the **size** of each towel and how long it is dipped, must stay the same.'])),
 item(mc('Vikram tests whether the amount of light affects how tall cress grows. Select the **two** things he should keep the **same**.',['The amount of water each pot gets','The type of seeds'],['The amount of light each pot gets','The height the cress grows','How many leaves each seedling has at the end'],
  ['He **changes** the amount of light and **measures** the height of the cress, so everything else must be kept the same.','Water and the type of seeds could both affect growth, so they must be the same for every pot.'])),
 item(mc('Rory rolled a car down a ramp three times from each height. Which result is **anomalous** (does not fit the pattern)?','Test 3 at 20 cm (64 cm)',['Test 1 at 10 cm (52 cm)','Test 2 at 30 cm (152 cm)','Test 2 at 40 cm (203 cm)'],
  ['At each height the three results should be close together. At 20 cm, tests 1 and 2 gave about 100 cm, but test 3 gave only **64 cm**.','That result does not fit, so Rory should check it and repeat that test.'],
  {visual:{kind:'table',caption:'Distance the car travelled',head:['Ramp height (cm)','Test 1 (cm)','Test 2 (cm)','Test 3 (cm)'],rows:[['10','52','50','51'],['20','98','101','64'],['30','149','152','150'],['40','199','203','201']],alt:'A results table of ramp heights with three distances for each'}}),
  {type:'anomaly-table'}),
 item(mc('Tom put ice cubes in four places and timed how long each took to melt. Where did the ice melt **fastest**?','Next to the radiator',['In the fridge','In the classroom','On the windowsill'],
  ['The **shortest** bar shows the shortest melting time, so the ice melted fastest next to the radiator (8 minutes).','The tallest bar is the fridge, the coldest place, where the ice melted most slowly.'],
  {visual:{kind:'chart',type:'bar',title:'Time for an ice cube to melt',x:'Place',y:'Time (minutes)',labels:['Fridge','Classroom','Windowsill','Radiator'],values:[95,40,28,8],max:100,step:10,alt:'A bar chart of melting times for ice cubes in four places'}}),
  {type:'chart-min',names:{'Next to the radiator':'Radiator','In the fridge':'Fridge','In the classroom':'Classroom','On the windowsill':'Windowsill'}}),
 item(mc('Tilly hung weights on a spring and measured its length each time. If the pattern continues, how long will the spring be with a 5 N weight?','25 cm',['22 cm','20 cm','28 cm','30 cm'],
  ['Each extra 1 N makes the spring **3 cm** longer: 10, 13, 16, 19 cm.','So 4 N would give 22 cm, and 5 N would give **25 cm**.'],
  {visual:{kind:'table',head:['Weight (N)','Length of spring (cm)'],rows:[['0','10'],['1','13'],['2','16'],['3','19']],alt:'A results table of weights and the length of a spring'},...challenge,...sorted}),
  {type:'extrapolate-linear',at:5}),
 item(mc('Keira timed 10 swings of a pendulum with different lengths of string. Which conclusion do her results support?','The longer the string, the longer 10 swings take.',['The longer the string, the shorter 10 swings take.','The heavier the weight, the longer 10 swings take.','The length of the string makes no difference.'],
  ['As the string length goes up (20, 40, 60, 80 cm), the time for 10 swings also goes **up**.','She did not change the weight, so her results cannot tell her anything about it.'],
  {visual:{kind:'table',head:['Length of string (cm)','Time for 10 swings (s)'],rows:[['20','9.0'],['40','12.7'],['60','15.5'],['80','17.9']],alt:'A results table of string length and the time for 10 swings'}}),
  {type:'trend',dir:'up'}),
 item(mc('Which piece of equipment should Poppy use to measure the force needed to drag a shoe across the floor?','A forcemeter',['A thermometer','A measuring cylinder','A stopwatch','A ruler'],
  ['A **forcemeter** measures forces in newtons (N).','Thermometers measure temperature, measuring cylinders measure volume, stopwatches measure time and rulers measure length.'],quick)),
 item(mc('Why do scientists repeat measurements and work out an average?','To make the results more reliable and help spot any anomalous results',['To make sure the test is fair, by changing only one thing','To keep changing the results until they match what they hoped for','To make the investigation last longer and use more equipment'],
  ['Repeating a measurement shows whether the results are **consistent**, and makes it easier to spot one that does not fit.','A fair test is about keeping the other variables the same, which is a different idea.'])),
 item(mc('Cara timed a ball rolling down a slope three times. What is the **mean** time?','2.7 s',['2.8 s','8.1 s','2.9 s','2.4 s'],
  ['Add the three times: 2.4 + 2.8 + 2.9 = **8.1 s**.','Divide by the number of results: 8.1 ÷ 3 = **2.7 s**.'],
  {visual:{kind:'table',head:['Test 1','Test 2','Test 3'],rows:[['2.4 s','2.8 s','2.9 s']],alt:'A table of three times'},...sorted}),
  {type:'mean'}),
 item(mc('Priya measured the height of her sunflower every week for eight weeks. Which type of graph would show her results best?','A line graph',['A pie chart','A pictogram','A Venn diagram'],
  ['A **line graph** shows how something **changes over time**, such as a plant growing week by week.','Pie charts show parts of a whole, and Venn diagrams sort things into groups.'],quick)),
 item(mc('Olu wants to find out which ball bounces highest. He drops a tennis ball from 1 m and a football from 2 m. Why is this **not** a fair test?','He changed two things: the type of ball and the drop height.',['He should have tested more than two balls.','He did not use a stopwatch to time the bounces.','Footballs always bounce higher, so there is no need to test.'],
  ['In a fair test you change **only one** variable. Olu changed the ball **and** the height.','If the football bounces higher, he cannot tell whether it is because of the ball or the bigger drop.'])),
 item(mc('Callum planted 20 seeds in each of four places. How many **more** seeds germinated in the cupboard than in the fridge?','14',['16','2','18','12'],
  ['Read the bars: **16** seeds germinated in the cupboard and **2** in the fridge.','16 − 2 = **14**.'],
  {visual:{kind:'chart',type:'bar',title:'Seeds that germinated',x:'Place',y:'Number of seeds',labels:['Fridge','Shed','Windowsill','Cupboard'],values:[2,9,13,16],max:20,step:2,alt:'A bar chart of the number of seeds that germinated in four places'},...sorted}),
  {type:'chart-diff',a:'Cupboard',b:'Fridge'}),
 item(mc('Five children measured their arm span and their height. Which statement do the results support?','Children with a longer arm span tend to be taller.',['Children with a longer arm span tend to be shorter.','Arm span and height are not linked at all.','Everyone\'s arm span is exactly the same as their height.'],
  ['As arm span increases, height **increases** too: the child with the longest arm span, Luca, is also the tallest.','The two measurements are close, but not always exactly equal.'],
  {visual:{kind:'table',head:['Name','Arm span (cm)','Height (cm)'],rows:[['Zara','138','140'],['Finn','145','144'],['Ruby','131','133'],['Luca','150','151'],['Sami','142','141']],alt:'A table of five children\'s arm spans and heights'},...challenge}),
  {type:'correlation',sign:1}),
 item(mc('Which of these is a **prediction** that could be tested in an investigation?','If I give cress more water, it will grow taller.',['Cress sandwiches are the tastiest kind of sandwich.','Cress is a living thing that grows from seeds.','My cress seeds came in a small paper packet.'],
  ['A **prediction** says what you think will happen when you change something, so it can be tested and measured.','The other sentences are opinions or facts, not predictions about a change.'])),
 item(mc('Look at the headings of Tom\'s results table. What did he **measure**?','The distance the car rolled',['The type of surface the car rolled on','The height of the ramp','The weight of the car'],
  ['The **measured** variable is the one you record results for: the distance the car rolled.','The type of surface is the variable he **changed**.'],
  {visual:{kind:'table',head:['Type of surface','Distance the car rolled (cm)'],rows:[['Carpet',''],['Wood',''],['Lino','']],alt:'An empty results table with two column headings'},...quick}),
  {type:'header',col:1}),
 item(mc('Jaya measured the length of a stick\'s shadow every hour. Which reading on the line graph looks **anomalous**?','The reading at 11:00',['The reading at 9:00','The reading at 12:00','The reading at 14:00'],
  ['Through the morning the shadow gets **shorter** each hour, and after midday it gets longer, making a smooth curve.','The reading at 11:00 jumps up out of the pattern, so it should be checked and measured again.'],
  {visual:{kind:'chart',type:'line',title:'Length of a stick\'s shadow',x:'Time',y:'Shadow length (cm)',labels:['9:00','10:00','11:00','12:00','13:00','14:00','15:00'],values:[80,62,76,44,44,50,62],max:90,step:10,alt:'A line graph of the length of a shadow at different times of day'},...challenge}),
  {type:'anomaly-chart'}),
]);

export const enquiryParts=[enquiry];
