import type {Topic} from './bank-kit';
import {mc,item,science,sorted,quick,challenge} from './bank-science-kit';
import {rays,seeingApple,shadowSetup,shadowPicture,periscope,forceMeter,ballArrows,lever,gears,magnets,bottles,xylophone,dayNight,moonOrbit,solarSketch} from './bank-science-draw';
// Science: physics — light, forces, sound, and Earth and space. Electricity is in bank-science-electricity.ts.

// ── Light ───────────────────────────────────────────────────────────────────────────────────────────────────
const RAY_CHOICES:{key:string;paths:string[];alt:string}[]=[
 {key:'reflect',paths:['lamp>book','book>eye'],alt:'Arrows from the lamp to the book, and from the book to the eye'},
 {key:'fromEye',paths:['lamp>book','eye>book'],alt:'Arrows from the lamp to the book, and from the eye to the book'},
 {key:'lampEye',paths:['lamp>eye'],alt:'An arrow from the lamp to the eye'},
 {key:'eyeOnly',paths:['eye>book'],alt:'An arrow from the eye to the book'}];
const SHADOW_CHOICES:{key:string;at:[number,number];alt:string}[]=[
 {key:'inLine',at:[176,60],alt:'A shadow on the wall, level with the ball'},
 {key:'high',at:[176,30],alt:'A shadow on the wall, higher than the ball'},
 {key:'low',at:[176,90],alt:'A shadow on the wall, lower than the ball'},
 {key:'front',at:[68,60],alt:'A shadow between the torch and the ball'}];

const lightTopic:Topic={id:'sc-light',subject:'Science',strand:'Physics',title:'Light',helpsheet:{
 intro:'Light spreads out from a light source in straight lines. We see an object when light from it enters our eyes: either the object gives out light, or it reflects light from a source.',
 steps:['Light leaves a **light source**, such as the Sun, a flame or a lamp.','It travels in **straight lines** until it hits something.','Objects **reflect** some of the light that hits them. Smooth, shiny surfaces such as mirrors reflect it best.','We see an object when light from it travels **into our eyes**.','An **opaque** object blocks light, so a **shadow** forms behind it with the same outline as the object.'],
 example:{title:'How Priya sees an apple',visual:seeingApple('A lamp, an apple and an eye, with arrows from the lamp to the apple and from the apple to the eye'),lines:['Light travels from the lamp to the apple.','The apple reflects some of that light into Priya\'s eye, so she sees the apple.']},
 tips:['Light does not come out of our eyes: in a ray diagram the arrows point **towards** the eye.','Only things that give out their own light, such as flames and the Sun, are light sources. We see everything else by the light it reflects.','A shadow is a dark area where light has been blocked by an opaque object.','The size of a shadow depends on how far the object is from the light.','Sunlight can damage your eyes, so never look straight at the Sun.']}};

const light=science(lightTopic,[
 item({...mc('Isaac reads a book by the light of a lamp. Which diagram shows how he **sees** the book?','reflect',['fromEye','lampEye','eyeOnly'],
  ['Light travels from the **lamp** to the book. The book **reflects** some of it, and that light travels **into Isaac\'s eye**.','Light never travels out of our eyes, and light going straight from the lamp to the eye would let Isaac see the lamp, not the book.']),
  pictures:RAY_CHOICES.map(c=>({key:c.key,visual:rays(c.paths,c.alt)}))},
  {type:'rays',pictures:RAY_CHOICES.map(c=>({visual:rays(c.paths,c.alt),paths:c.paths}))}),
 item(mc('Which surface would reflect light **best**?','A smooth, flat mirror',['A black velvet cloth','A rough brick wall','A dark woollen jumper'],
  ['Smooth, shiny surfaces such as **mirrors** reflect almost all the light that hits them, evenly.','Dark and rough surfaces absorb more of the light and scatter the rest.'],quick)),
 item(mc('Why can we see the Moon at night?','It reflects light from the Sun towards the Earth.',['It gives out its own light, like a star does.','It glows because its rocks are very hot.','Light from our eyes bounces back off it.'],
  ['The Moon is **not a light source**. Sunlight hits the Moon, and some is **reflected** to Earth and into our eyes.','The Moon\'s surface is not hot enough to glow, and our eyes do not give out light.'])),
 item(mc('Tom moves the puppet **closer to the torch**. What happens to its shadow on the screen?','It gets bigger.',['It gets smaller.','It stays the same size.','It disappears.'],
  ['Closer to the torch, the puppet blocks **more of the spreading light**, so the shadow gets **bigger**.','Moving the puppet towards the screen would make the shadow smaller.'],
  {visual:shadowSetup('A torch shines on a puppet in front of a screen; an arrow shows the puppet moving towards the torch')}),
  {type:'shadow-size'}),
 item(mc('Why does a shadow have the same shape as the object that makes it?','Light travels in straight lines, so it is blocked in the object\'s shape.',['The object reflects a copy of its own shape onto the wall behind it.','Darkness flows out from the object and spreads over the wall in its shape.','Light passes through the object and takes on the shape of the object.'],
  ['Light travels in **straight lines**, and an **opaque** object blocks the light that hits it.','The light that just misses the edges carries on in straight lines, so the dark area behind has the object\'s outline.'])),
 item(mc('Which material would make the **darkest** shadow?','Cardboard',['Clear glass','Tracing paper','Clear plastic','Tissue paper'],
  ['Cardboard is **opaque**: it blocks all the light, so its shadow is darkest.','Tracing paper and tissue paper are **translucent** and let some light through; clear glass and clear plastic are **transparent**.']),
  {type:'category',yes:'opaque',no:['translucent','transparent']}),
 item(mc('Why can you see your reflection in a mirror, but not in a sheet of white paper?','A mirror is smooth and reflects light evenly; paper scatters it.',['Paper does not reflect any light at all, so no image can form.','The mirror gives out its own light, but paper does not.','White paper soaks up all of the light that hits it.'],
  ['**Both** reflect light: that is how we see the paper at all.','A mirror is so **smooth** that the reflected light keeps its pattern and forms an image. The rough surface of paper **scatters** light in all directions.'],challenge)),
 item(mc('Ravi uses a periscope to see over a wall. In what order does light travel through it?','object → top mirror → bottom mirror → eye',['eye → bottom mirror → top mirror → object','object → bottom mirror → top mirror → eye','top mirror → object → eye → bottom mirror'],
  ['Light from the object goes in at the top opening and **reflects** off the top mirror, down to the bottom mirror.','The bottom mirror reflects it **into Ravi\'s eye**. Light always travels towards the eye, never out of it.'],
  {visual:periscope('A periscope with a top mirror and a bottom mirror, an object at the top left and an eye at the bottom right')}),
  {type:'order',kb:'periscope'}),
 item(mc('What is the **safest** way to protect your eyes on a very sunny day?','Wear sunglasses and never look straight at the Sun',['Look at the Sun through binoculars to shade your eyes','Look straight at the Sun for just a minute','Look at the Sun through a telescope, but only briefly'],
  ['Sunlight is so strong that looking straight at the Sun can **permanently damage** your eyes.','Binoculars and telescopes collect even more light, which makes the danger worse.'],quick)),
 item(mc('Uma is in a room with no light at all. What can she see?','Nothing, because no light is entering her eyes',['Her white T-shirt, because white things glow','Her own hands, because her eyes give out light','Shiny objects, because they make their own light'],
  ['We see things only when **light enters our eyes**. Dark is simply the **absence of light**.','White and shiny things only reflect light; with no light to reflect, they cannot be seen.'])),
 item(mc('Priya measured the height of a puppet\'s shadow on a screen as she moved the torch further away from the puppet. What pattern do her results show?','The further the torch is from the puppet, the smaller the shadow.',['The further the torch is from the puppet, the bigger the shadow.','Moving the torch makes no difference to the size of the shadow.','The shadow is always the same height as the puppet.'],
  ['As the distance goes up from 10 cm to 40 cm, the shadow height goes **down**, from 60 cm to 23 cm.','When the torch is further away, the puppet blocks less of the spreading light.'],
  {visual:{kind:'table',head:['Distance from torch to puppet (cm)','Height of shadow (cm)'],rows:[['10','60'],['20','35'],['30','27'],['40','23']],alt:'A results table of torch distance and shadow height'}}),
  {type:'trend',dir:'down'}),
 item(mc('On a sunny day, when is your shadow **shortest**?','Around the middle of the day',['Early in the morning, just after sunrise','In the late afternoon, after school','In the evening, just before sunset'],
  ['Around the middle of the day the Sun is **highest** in the sky, so its light comes from above and your shadow is short.','In the morning and evening the Sun is low, so shadows are long.'],quick)),
 item(mc('Oscar lines up three cards, each with a small hole in the middle, between his eye and a candle. He can see the flame only when the three holes are in a straight line. What does this show?','Light travels in straight lines.',['Light can reach his eye even when the holes are not lined up.','Light travels out of his eye to the flame.','The holes in the cards make the flame brighter.'],
  ['Light from the flame reaches Oscar\'s eye only when there is a **straight** path through all three holes.','If one card moves, it blocks that straight path, so he cannot see the flame. Light travels into our eyes, not out of them.'],challenge)),
 item(mc('Which word describes a material that lets **some** light through, but you cannot see clearly through it?','Translucent',['Transparent','Opaque','Reflective'],
  ['**Translucent** materials, such as tracing paper or frosted glass, let some light through but blur what is behind them.','Transparent materials let light straight through; opaque materials let no light through.'],quick)),
 item(mc('Select the **two** light sources.',['The Sun','A lit candle'],['The Moon','A mirror','A shiny coin'],
  ['A **light source** gives out its own light. The Sun and a candle flame both do.','The Moon, a mirror and a shiny coin only **reflect** light that comes from somewhere else.']),
  {type:'category',yes:'light source',no:['reflector']}),
 item({...mc('A torch shines on a ball in front of a wall. Which picture shows where the ball\'s shadow will be?','inLine',['high','low','front'],
  ['Light travels in **straight lines** from the torch. The ball blocks some of it, so the shadow is on the wall **directly behind the ball**, in line with the torch.','A shadow is always on the side of the object **away from** the light.']),
  pictures:SHADOW_CHOICES.map(c=>({key:c.key,visual:shadowPicture(c.at[0],c.at[1],c.alt)}))},
  {type:'shadow-pictures',pictures:SHADOW_CHOICES.map(c=>({visual:shadowPicture(c.at[0],c.at[1],c.alt),at:c.at}))}),
 item(mc('Sofia says her shadow is a reflection of her. Why is she wrong?','A shadow is where light is blocked; a reflection is light bouncing back.',['Shadows and reflections are just two different names for the same thing.','A shadow is light that shines out of her body onto the ground.','Her shadow is made by moonlight, and reflections by sunlight.'],
  ['A **shadow** is a dark area where light cannot reach, because an **opaque** object is in the way.','A **reflection** is made when light **bounces off** a smooth surface, such as a mirror or still water.'])),
]);

// ── Forces ──────────────────────────────────────────────────────────────────────────────────────────────────
const forcesTopic:Topic={id:'sc-forces',subject:'Science',strand:'Physics',title:'Forces',helpsheet:{
 intro:'A force is a push or a pull. Forces are measured in **newtons (N)** with a **forcemeter** (a force meter or newton meter).',
 steps:['**Gravity** pulls everything towards the centre of the Earth. The pull of gravity on an object is its **weight**, measured in newtons.','**Air resistance** and **water resistance** push against things moving through air or water. Streamlined shapes reduce them.','**Friction** acts between surfaces that slide or rub together. Rough surfaces make more friction.','**Levers, pulleys and gears** let a small force have a bigger effect.'],
 example:{title:'Reading a forcemeter',visual:forceMeter(3,'A forcemeter with a scale from 0 to 10 N, holding a bag'),lines:['Each small mark on this scale is **1 N**, and every second mark is numbered.','The pointer is at the mark for 3, so the bag weighs **3 N**.']},
 tips:['Mass is measured in kilograms (kg); weight is a force, measured in newtons (N).','Friction is often useful: it lets shoes grip the ground.','With a lever, where you push matters: the distance from the pivot changes the force you need.','Like magnetic poles repel; unlike poles attract.']}};

const forces=science(forcesTopic,[
 item(mc('What unit are forces measured in?','Newtons (N)',['Kilograms (kg)','Metres (m)','Litres (l)','Degrees Celsius (°C)'],
  ['Forces, including weight, are measured in **newtons**, using a forcemeter.','Kilograms measure **mass**, the amount of matter in an object, which is not a force.'],quick)),
 item(mc('Mei hangs a bag of apples on a forcemeter. What is the weight of the bag?','7 N',['7 kg','70 N','6 N','3.5 N'],
  ['Every mark on the scale is **1 N**. The pointer is one mark below 6, at **7**.','Weight is a force, so it is measured in **newtons**, not kilograms.'],
  {visual:forceMeter(7,'A forcemeter with a scale from 0 to 10 N, holding a bag of apples'),...sorted}),
  {type:'meter',reading:7}),
 item(mc('Why does a ball fall back to the ground after you throw it up?','Gravity pulls it down towards the Earth.',['It runs out of the force from your throw.','The air above it pushes it back down.','The spinning Earth drags it back down.'],
  ['**Gravity** pulls every object towards the centre of the Earth, all the time.','As the ball rises, gravity slows it, stops it and pulls it back down. A thrown ball does not carry a store of "force" that runs out.'])),
 item(mc('Zara drops a football and a tennis ball from the same window at the same time. They land at almost the same moment. Why?','Air resistance is small, so gravity makes both fall at the same rate.',['Heavier objects always fall faster, so one ball must have been thrown.','The tennis ball is so light that gravity hardly pulls on it at all.','The two balls must have exactly the same mass as each other.'],
  ['Gravity pulls harder on the heavier ball, but it also has more mass to get moving, so both **speed up at the same rate**.','Something light with a large surface, such as a feather, falls slowly because of **air resistance**.'],challenge)),
 item(mc('Why does a parachute slow a skydiver down?','Its large surface area causes a big air resistance force.',['It makes the skydiver lighter, so gravity pulls less.','It blocks the pull of gravity from the Earth below.','It traps warm air, which floats upwards like a balloon.'],
  ['A parachute has a **large surface area**, so it pushes against a lot of air. This makes a large **air resistance** force upwards.','Gravity still pulls the skydiver down, but air resistance balances it at a slow, safe speed.'])),
 item(mc('The ball is **falling** through the air. Which arrow shows the **air resistance** acting on it?','Arrow P',['Arrow Q','Arrow R','Arrow S'],
  ['Air resistance always acts in the **opposite direction** to the movement.','The ball is moving **down**, so air resistance pushes **up** (P). Gravity pulls down (Q).'],
  {visual:ballArrows('A ball with four arrows labelled P, Q, R and S pointing up, down, left and right'),...sorted}),
  {type:'arrows',moving:'down',against:true,directions:{P:'up',Q:'down',R:'left',S:'right'}}),
 item(mc('Why is it harder to slide a heavy box across thick carpet than across a smooth wooden floor?','The carpet makes more friction against the box.',['The carpet makes the box heavier.','Gravity pulls harder on things on a carpet.','Air resistance is bigger just above a carpet.'],
  ['**Friction** acts between two surfaces that rub together. The rough carpet grips the sliding box more than the smooth floor does.','The box weighs the same on both floors: only the friction is different.'],quick)),
 item(mc('Hugo pulled a wooden block across different surfaces with a forcemeter. Which surface gave the **most** friction?','Sandpaper',['Tiles','Wood','Carpet'],
  ['The more friction there is, the bigger the force needed to pull the block. The biggest force was needed on **sandpaper** (6.5 N).','The smallest force was needed on tiles (1.5 N), so tiles gave the least friction.'],
  {visual:{kind:'table',head:['Surface','Force needed to pull the block (N)'],rows:[['Carpet','4.0'],['Wood','2.5'],['Sandpaper','6.5'],['Tiles','1.5']],alt:'A results table of four surfaces and the force needed to pull a wooden block across each'}}),
  {type:'table-max',col:1}),
 item(mc('Which is an example of friction being **useful**?','Bicycle brakes gripping the wheels to slow the bike',['Car tyres slowly wearing thin as they rub on the road','The soles of new shoes wearing away as you walk','A heavy door sticking and scraping on its hinges'],
  ['Brakes work because of **friction** between the brake pads and the wheel.','Wearing away and sticking are unwanted effects of friction.'])),
 item(mc('Why are fish and speedboats streamlined?','A smooth, pointed shape reduces water resistance, so they move easily.',['A streamlined shape increases water resistance, so they go faster.','A streamlined shape makes them heavier, so they do not float away.','A streamlined shape stops gravity from pulling them down.'],
  ['**Water resistance** pushes against things moving through water.','A smooth, pointed **streamlined** shape lets the water flow around it easily, so there is less water resistance.'])),
 item(mc('Farah wants to lift the rock using the plank as a lever. Where should she push down to lift it with the **smallest** force?','Point R',['Point P','Point Q','It makes no difference where she pushes'],
  ['With a lever, the **further from the pivot** you push, the smaller the force you need.','Point R is furthest from the pivot, so pushing there needs the least force.'],
  {visual:lever('A plank balanced on a pivot with a rock on the left end and three pushing points labelled P, Q and R'),...sorted}),
  {type:'lever'}),
 item(mc('Sofia is heavier than Leo. Where should Sofia sit so that the seesaw balances?','Closer to the pivot than Leo',['Further from the pivot than Leo','The same distance from the pivot as Leo','Right on top of the pivot'],
  ['A force has a **bigger turning effect** the further it is from the pivot.','The heavier person must sit **closer to the pivot**, so that both turning effects are equal.'])),
 item(mc('Builders lift a heavy chest into the manor loft with a set of pulleys, arranged so that the rope holds the chest up in **four** places. Compared with lifting the chest straight up by hand, what difference does this make?','Less force is needed, but more rope must be pulled through.',['The chest becomes lighter, so it is easier to lift.','More force is needed, but less rope has to be pulled.','The pulleys lift the chest on their own, without anyone pulling.'],
  ['The weight of the chest is shared between **four** lengths of rope, so a much **smaller force** is needed to lift it.','The trade-off is that you must pull **more rope** through: about 4 m of rope to raise the chest 1 m.'],challenge)),
 item(mc('The large gear turns **once** clockwise. What does the small gear do?','It turns twice, anticlockwise.',['It turns twice, clockwise.','It turns once, anticlockwise.','It turns half a turn, anticlockwise.','It turns half a turn, clockwise.'],
  ['The small gear has **half as many teeth** (12 instead of 24), so it must turn **twice** for every turn of the large gear.','Gears that mesh always turn in **opposite directions**, so it turns anticlockwise.'],
  {visual:gears(24,12,'A large gear with 24 teeth meshing with a small gear with 12 teeth; an arrow shows the large gear turning clockwise'),...challenge}),
  {type:'gears',turns:1,dir:'clockwise'}),
 item(mc('Which of these would be attracted to a magnet?','An iron nail',['An aluminium can','A plastic spoon','A gold ring','A wooden pencil'],
  ['Only a few metals are **magnetic**: iron, nickel, cobalt and most kinds of steel, which is mostly iron.','Aluminium and gold are metals but are **not** magnetic, so not all metals are attracted to magnets.']),
  {type:'category',yes:'magnetic',no:['non-magnetic']}),
 item(mc('The two magnets are pushed together as shown. What will happen?','They will repel, because two south poles are facing.',['They will attract, because two south poles are facing.','They will attract, because all magnets attract each other.','Nothing, because magnets only attract metals.'],
  ['**Like poles repel** and **unlike poles attract**.','The facing ends are both **S**, which are like poles, so the magnets push each other apart.'],
  {visual:magnets([['N','S'],['S','N']],'Two bar magnets end to end, the first labelled N then S, the second S then N')}),
  {type:'magnets'}),
 item(mc('A bag of flour has a mass of 1 kg. About how much does it weigh on Earth?','About 10 N',['About 1 N','About 1 kg','About 100 N'],
  ['On Earth, gravity pulls with about **10 newtons** on every **1 kilogram** of mass.','So a 1 kg bag of flour weighs about 10 N. Its mass is 1 kg, but weight is a force, measured in newtons.'],{...challenge,...sorted}),
  {type:'weight',kg:1}),
 item(mc('Select the **two** forces that only act when things are in contact.',['Friction','Water resistance'],['Gravity','Magnetic force'],
  ['**Friction** and **water resistance** are **contact forces**: they act only where surfaces touch, or where something moves through water.','Gravity and magnetic forces can act at a **distance**, without touching.'])),
]);

// ── Sound ───────────────────────────────────────────────────────────────────────────────────────────────────
const soundTopic:Topic={id:'sc-sound',subject:'Science',strand:'Physics',title:'Sound',helpsheet:{
 intro:'Sounds are made when something **vibrates**. The vibrations travel through a solid, liquid or gas to your ear.',
 steps:['A vibrating object, such as a drum skin, a guitar string or your vocal cords, makes the air next to it vibrate.','The vibrations pass through the air (or through a solid or liquid) to your ear, and your eardrum vibrates too.','**Volume**: bigger (stronger) vibrations make **louder** sounds. Sounds get fainter as they travel further.','**Pitch**: faster vibrations make **higher** notes. Shorter, tighter or thinner strings, and smaller drums, vibrate faster.'],
 example:{title:'Rice on a drum',lines:['Hana sprinkles rice on a drum and taps it: the rice jumps because the drum skin is **vibrating**.','When she hits it harder, the rice jumps higher and the sound is louder, because the vibrations are bigger.']},
 tips:['Pitch (high or low) and volume (loud or quiet) are different things.','Sound needs something to travel through: a solid, a liquid or a gas.','Sound travels much more slowly than light: at a fireworks display you see each burst before you hear the bang.','Soft materials absorb sound better than hard, smooth ones.']}};

const sound=science(soundTopic,[
 item(mc('How are all sounds made?','By something vibrating',['By something getting hot','By light hitting an object','By something standing completely still'],
  ['Every sound starts with something **vibrating**: moving quickly backwards and forwards.','You can feel this by touching your throat while you hum.'],quick)),
 item(mc('How does the sound of a drum reach your ears?','The drum skin vibrates, and the vibrations pass through the air to your ears.',['Sound travels out of your ears to the drum and bounces back again.','The drumstick throws tiny pieces of sound through the air to you.','The drum\'s sound can only travel along the floor, not through the air.'],
  ['The vibrating drum skin makes the **air** next to it vibrate. The vibrations pass through the air until they reach your **ear**.','Your **eardrum** then vibrates, and your brain hears the sound.'])),
 item(mc('Astronauts say that space is completely silent. Why?','Space is almost empty, so there is nothing to carry the vibrations.',['Space is far too cold for any sounds to be made there.','Sound travels too fast in space for ears to hear it.','The stars give out so much light that sounds are drowned out.'],
  ['Sound needs a **medium** (a solid, liquid or gas) whose particles can pass the vibrations along.','Space is almost a **vacuum**, so sound cannot travel through it. Astronauts talk to each other by radio.'])),
 item(mc('Which change makes a guitar string play a **higher** note?','Tightening the string',['Plucking the string harder','Using a thicker string','Making the vibrating part longer'],
  ['A **tighter** string vibrates **faster**, and faster vibrations make a **higher** pitch.','Plucking harder makes the note **louder**, not higher. Thicker or longer strings play lower notes.'])),
 item(mc('Uma blows across the tops of these bottles to make notes. Which bottle makes the **highest** note?','Bottle R',['Bottle P','Bottle Q','Bottle S'],
  ['When you blow across a bottle, the **air inside** vibrates.','Bottle R has the most water, so its column of air is the **shortest**. A shorter column of air vibrates faster, making a **higher** note.'],
  {visual:bottles([60,30,104,80],'P','Four identical bottles, P to S, holding different amounts of water'),...sorted,...challenge}),
  {type:'bottles',ask:'highest'}),
 item(mc('How can Kofi make his drum sound **louder**?','Hit it harder, so it vibrates more strongly',['Hit it more gently, so it vibrates less','Lay a thick cloth over the drum skin','Walk further away from the drum'],
  ['Hitting the drum harder makes **bigger vibrations**, and bigger vibrations make a **louder** sound.','A cloth soaks up the vibrations, and walking away lets the sound spread out, so both make the drum sound quieter.'])),
 item(mc('Callum used a data logger to measure how loud a speaker was at different distances. What do his results show?','The sound gets quieter as you move further from the speaker.',['The sound gets louder as you move further from the speaker.','Distance from the speaker makes no difference to how loud it is.','The sound is quietest when you stand closest to the speaker.'],
  ['The sound level falls from 80 dB at 1 m to 62 dB at 8 m, so the sound gets **fainter** with distance.','The vibrations **spread out** as they travel, so less of their energy reaches your ear.'],
  {visual:{kind:'table',head:['Distance from speaker (m)','Sound level (dB)'],rows:[['1','80'],['2','74'],['4','68'],['8','62']],alt:'A results table of distance from a speaker and sound level'}}),
  {type:'trend',dir:'down'}),
 item(mc('Aisha tested materials for ear defenders by covering a sound sensor with each one. Which material would be **best** for ear defenders?','Foam',['Bubble wrap','Cotton wool','Kitchen foil'],
  ['The best material lets the **least sound through**, so it gives the **lowest** reading.','Foam gave the lowest reading (45 dB), so it absorbed the most sound.'],
  {visual:{kind:'table',head:['Material','Sound level through it (dB)'],rows:[['No material','70'],['Kitchen foil','66'],['Cotton wool','52'],['Bubble wrap','58'],['Foam','45']],alt:'A results table of materials and the sound level measured through each'}}),
  {type:'table-min',col:1,skip:['No material']}),
 item(mc('Olu presses his ear to one end of a desk while Priya gently taps the other end. He hears the tap clearly. What does this show?','Sound can travel through solids.',['Sound can only travel through air.','The desk makes its own sounds.','Sound travels more slowly through wood than through air.'],
  ['The tapping makes the wood **vibrate**, and the vibrations travel **through the solid desk** to Olu\'s ear.','In fact, sound travels **faster** through solids than through air.'])),
 item(mc('Why does a string telephone work better when the string is pulled tight?','A tight string passes the vibrations along from one cup to the other.',['A tight string stops the vibrations from reaching the other cup.','A loose string lets the sound leak out through the sides of the cups.','A tight string sends the sound through the air instead of the string.'],
  ['Your voice makes the cup **vibrate**, and the vibrations travel **along the string** to the other cup.','A **slack** string flops about and soaks up the vibrations, so little sound gets through.'])),
 item(mc('The bars of a xylophone are different lengths. Which bar plays the **lowest** note?','Bar Q',['Bar P','Bar R','Bar S','Bar T'],
  ['Longer bars vibrate more **slowly**, and slower vibrations make **lower** notes.','Bar Q is the **longest**, so it plays the lowest note. The shortest bar, R, plays the highest.'],
  {visual:xylophone([110,150,70,130,90],'P','Five xylophone bars of different lengths labelled P to T'),...sorted}),
  {type:'bars',ask:'lowest'}),
 item(mc('Ellie shouts across the manor courtyard and hears her voice again a moment later. What is this echo?','Her voice reflecting off a hard wall and coming back to her',['Her voice travelling through a vacuum and coming back','Another person nearby copying the sound of her voice','Her voice being soaked up by the soft grass around her'],
  ['An **echo** is a sound that **reflects** (bounces) off a hard surface, such as a wall or a cliff, and comes back.','It arrives a moment later because sound takes time to travel there and back.'])),
 item(mc('During a storm you see the lightning before you hear the thunder. Why?','Light travels much faster than sound.',['Sound travels much faster than light.','Thunder is made a few seconds after the lightning.','Your eyes work faster than your ears.'],
  ['Lightning and thunder happen at the **same moment**, but light travels about a million times faster than sound.','The further away the storm is, the longer the gap between the flash and the rumble.'])),
 item(mc('Select the **two** changes that would make a drum play a **higher** note.',['Tightening the drum skin','Using a smaller drum'],['Hitting it harder','Using a bigger drum','Loosening the drum skin'],
  ['A **tighter** skin and a **smaller** drum both vibrate **faster**, giving a higher pitch.','Hitting harder only makes the sound louder. Bigger drums and looser skins give lower notes.'])),
 item(mc('Why does a sound get fainter the further you are from it?','The vibrations spread out and get weaker as they travel.',['Sound slows down as it travels, and after a while it stops.','The pitch of the sound gets lower as it travels.','Sound can only travel a few metres through air.'],
  ['As sound travels outwards, its energy **spreads out** over a bigger and bigger area.','So the vibrations reaching you are **weaker**, and less reaches your ear. The pitch stays the same.'],challenge)),
 item(mc('Jonah stretched four rubber bands across a box to make a guitar. Which band will play the **highest** note?','Band S',['Band P','Band Q','Band R'],
  ['**Thinner** bands and **tighter** bands vibrate faster, making higher notes.','Band S is both thin and tight, so it plays the highest note. Band P is thick and loose, so it plays the lowest.'],
  {visual:{kind:'table',head:['Band','Thickness','How tightly stretched'],rows:[['P','thick','loose'],['Q','thin','loose'],['R','thick','tight'],['S','thin','tight']],alt:'A table describing four rubber bands'},...sorted}),
  {type:'bands'}),
 item(mc('Why should people wear ear defenders when they use very loud machines?','Very loud sounds can damage the ears and harm hearing.',['Loud sounds make the machine work faster.','Ear defenders make sounds higher, so they are easier to hear.','Loud sounds only harm animals, not people.'],
  ['Very loud sounds make very **strong vibrations**, which can **damage** the delicate parts inside the ear.','Ear defenders are made of materials that **absorb** sound, so less of it reaches the ears.'])),
]);

// ── Earth and space ─────────────────────────────────────────────────────────────────────────────────────────
const spaceTopic:Topic={id:'sc-earth-space',subject:'Science',strand:'Physics',title:'Earth and space',helpsheet:{
 intro:'The Earth spins on its axis once a day and travels around the Sun once a year. The Moon travels around the Earth about once a month.',
 steps:['The Earth **spins** on its axis, so each place turns to face the Sun and then turns away again.','Because the Earth spins, the Sun **appears** to travel across the sky, even though it is the Earth that is moving.','The Earth travels round the Sun on a path called an **orbit**. One trip takes a **year**.','The Moon travels round the Earth, and the Sun always lights up half of the Moon.','There are eight planets. Mercury is closest to the Sun and Neptune is furthest away.'],
 example:{title:'The Sun, the Earth and the Moon',visual:solarSketch('The Sun, with the Earth on its orbit and the Moon going round the Earth'),lines:['The Sun is a star at the centre of the solar system.','The Earth travels round the Sun, and the Moon travels round the Earth. All three are roughly spheres.']},
 tips:['The Sun does not move around the Earth; it only seems to because the Earth spins.','The Moon is not a light source: it reflects sunlight.','The Moon\'s phases are not caused by the Earth\'s shadow; that only happens in an eclipse.','To remember the order of the planets, try: Many Very Eager Mice Jump Straight Up Now.']}};

const space=science(spaceTopic,[
 item(mc('What causes day and night on Earth?','The Earth spinning on its axis',['The Sun moving around the Earth','The Earth orbiting the Sun','The Moon blocking out the Sun'],
  ['The Earth **spins** on its axis about once every 24 hours.','The half facing the Sun has **day**; the half facing away has **night**. Orbiting the Sun takes a whole year.'],quick)),
 item(mc('How long does it take the Earth to travel once around the Sun?','About 365¼ days',['24 hours','About 28 days','About 7 days'],
  ['One **orbit** of the Sun takes about **365¼ days**: one year.','24 hours is about one **spin** of the Earth: a day. About 28 days is roughly a month.'],quick)),
 item(mc('Which list shows the four planets closest to the Sun, in order, starting with the nearest?','Mercury, Venus, Earth, Mars',['Venus, Mercury, Earth, Mars','Mercury, Venus, Mars, Earth','Mars, Earth, Venus, Mercury'],
  ['Starting nearest the Sun, the planets are **Mercury, Venus, Earth, Mars**, then Jupiter, Saturn, Uranus and Neptune.','These four inner planets are small and rocky.']),
  {type:'order',kb:'planets'}),
 item(mc('Which is the **largest** planet in our solar system?','Jupiter',['Saturn','Earth','Neptune','The Sun'],
  ['**Jupiter** is the largest planet: more than 1,000 Earths could fit inside it.','The Sun is much bigger still, but it is a **star**, not a planet.'],quick)),
 item(mc('The diagram shows the Earth lit by the Sun. For which person is it **midday**?','Person P',['Person Q','Person R','Person S'],
  ['It is **midday** where the Sun is highest in the sky: the point facing **straight towards** the Sun.','Person R is on the night side, facing directly away from the Sun, so it is midnight there.'],
  {visual:dayNight([['P',180],['Q',270],['R',0],['S',135]],'The Earth with its left half lit by the Sun and four people labelled P, Q, R and S'),...sorted}),
  {type:'daynight',ask:'midday'}),
 item(mc('Why does the Sun seem to move across the sky during the day?','Because the Earth is spinning on its axis',['Because the Sun travels around the Earth each day','Because the Moon pulls the Sun across the sky','Because the wind blows the clouds and the Sun along'],
  ['The Sun is not really moving across our sky. The Earth **spins** towards the east, so the Sun **appears** to move across the sky from east to west.','Long ago, many people thought the Sun really did move around the Earth.'])),
 item(mc('About how long does the Earth take to spin once on its axis?','About 24 hours',['About 12 hours','About 28 days','About 365 days'],
  ['The Earth spins once on its axis in about **24 hours**, which gives us one day and one night.','About 365 days is how long it takes to travel once around the Sun.'],quick)),
 item(mc('The diagram shows the Moon at four places in its orbit. At which position would we see a **full moon** from Earth?','Position R',['Position P','Position Q','Position S'],
  ['The half of the Moon facing the Sun is always lit. At **R**, the Moon is on the far side of the Earth from the Sun, so its **whole lit half faces us**.','At P, the lit half faces away from us, so we would see a **new moon**.'],
  {visual:moonOrbit([['P',180],['Q',270],['R',0],['S',90]],'The Earth with the Moon drawn at four places around it, labelled P, Q, R and S, and sunlight coming from the left'),...sorted,...challenge}),
  {type:'moon',ask:'full'}),
 item(mc('About how long does the Moon take to travel once around the Earth?','About four weeks',['About one day','About one year','About one week'],
  ['The Moon **orbits the Earth** about once every 27 days, which is roughly four weeks, or a month.','The word "month" comes from "moon".'])),
 item(mc('What shape are the Sun, the Earth and the Moon?','They are all roughly spheres.',['They are all flat discs.','The Earth is a sphere, but the Moon is a flat disc.','The Moon changes its shape every night.'],
  ['The Sun, Earth and Moon are all approximately **spheres** (ball shapes).','The Moon only **seems** to change shape because we see different amounts of its lit half.'])),
 item(mc('What is the Sun?','A star',['A planet','A moon','A comet'],
  ['The Sun is a **star**: a huge ball of very hot gas that gives out its own light.','It looks much bigger and brighter than the other stars because it is so much closer to us.'],quick)),
 item(mc('Why do we always see the same side of the Moon from Earth?','The Moon spins once in the same time that it takes to orbit the Earth.',['The Moon does not spin at all as it travels round us.','The far side of the Moon is always in darkness, so we cannot see it.','The Earth is always in the way, blocking our view of the far side.'],
  ['The Moon **spins** on its axis exactly once for every **orbit** of the Earth, so the same side always faces us.','The far side is not always dark: it is in sunlight when we see a new moon.'],challenge)),
 item(mc('The table shows four planets. What pattern does it show?','The further a planet is from the Sun, the longer it takes to orbit.',['The further a planet is from the Sun, the shorter its orbit takes.','The bigger a planet is, the longer it takes to orbit the Sun.','All planets take the same time to orbit the Sun.'],
  ['Reading down the table, the distance and the time to orbit **both increase**.','Planets further out have a longer path to travel, and they also move more slowly. The table says nothing about size.'],
  {visual:{kind:'table',head:['Planet','Distance from the Sun (million km)','Time to orbit the Sun (days)'],rows:[['Mercury','58','88'],['Venus','108','225'],['Earth','150','365'],['Mars','228','687']],alt:'A table of four planets with their distance from the Sun and the time each takes to orbit it'}}),
  {type:'trend',dir:'up'}),
 item(mc('When it is midday in London, it is night in New Zealand. Why?','The Earth is spinning, so different places face towards or away from the Sun.',['New Zealand is much further away from the Sun than London is.','The Sun always sets many hours earlier in the south of the world.','The Moon blocks the Sun\'s light from reaching New Zealand at that time.'],
  ['As the Earth **spins**, only half of it faces the Sun at any time.','When London faces the Sun, New Zealand, on the other side of the world, faces **away** from it.'])),
 item(mc('Select the **two** statements that are true.',['The Earth orbits the Sun.','The Moon orbits the Earth.'],['The Sun orbits the Earth.','The Earth orbits the Moon.','The Sun orbits the Moon.'],
  ['The **Earth** travels around the **Sun** once a year, and the **Moon** travels around the **Earth** about once a month.','The Sun only **appears** to move across our sky because the Earth spins.'])),
 item(mc('Long ago, most people believed that the Sun and planets moved around the Earth. Which astronomer argued that the Earth moves around the Sun?','Nicolaus Copernicus',['Ptolemy','Charles Darwin','Mary Anning'],
  ['About 500 years ago, **Copernicus** described a model of the solar system with the **Sun at the centre**.','Ptolemy, much earlier, described a model with the Earth at the centre. Darwin and Anning studied living things and fossils.'])),
 item(mc('Which planet takes the **longest** to travel once around the Sun?','Neptune',['Jupiter','Mercury','Earth'],
  ['The further a planet is from the Sun, the longer one orbit takes. **Neptune** is the furthest planet from the Sun.','One orbit of Neptune takes about 165 Earth years. Jupiter is the largest planet, but size does not decide how long an orbit takes.'],challenge),
  {type:'planet-furthest'}),
 item(mc('Why does the Moon seem to change shape during a month?','We see different amounts of its sunlit half as it orbits the Earth.',['The Earth\'s shadow covers different parts of it each night.','Clouds in space cover up different parts of the Moon each night.','The Moon really does change its shape as it spins round.'],
  ['The Sun always lights **half** of the Moon. As the Moon **orbits** the Earth, we see different amounts of that lit half.','The Earth\'s shadow only falls on the Moon during a lunar eclipse.'],challenge)),
]);

export const physicsParts=[light,forces,sound,space];
