const town='https://www.abingdon.gov.uk/places-to-visit';
const oxford='https://www.ox.ac.uk/about/visit-us/what-to-see';
export const CHAPTER_DETAILS=[
 ['The Quest Gates','Manor Quest','Hold the entrance and welcome the hero squad.','Your shared adventure begins at the gates.',''],
 ['The Watchtower House','Manor Quest','Protect the house at the heart of your world.','Keep the home base safe from the approaching slimes.',''],
 ['The Library Watch','Manor Quest','Keep the story scrolls safe from the slimes.','Guard the shelves and their enchanted stories.',''],
 ['Woodland Guardians','Manor Quest','Patrol the woodland edge together.','Build a defence along the forest paths.',''],
 ['Azure Banner Rally','Manor Quest','The blue banners mark a new challenge.','Bring your strongest equipment for the elite wave.',''],
 ['Crimson Watch','Manor Quest','Rally beneath the red banners.','Watch every turn in the monster route.',''],
 ['Emerald Guard','Manor Quest','Stand together beneath the green banners.','Mix weapon effects to strengthen your defence.',''],
 ['Golden Beacon','Manor Quest','Protect the golden rally point.','Every teammate can help hold the path.',''],
 ['The Playing Field','Manor Quest','Defend the playing-field boundary.','Turn everyday sports equipment into heroic tools.',''],
 ['The United Squad','Manor Quest','Unite your heroes for the first boss.','Protect your home base against a powerful foe.',''],
 ['Abingdon Market Watch','Abingdon','Guard the town-centre gathering place.','County Hall overlooks Abingdon Market Place.',town],
 ['County Hall Keepers','Abingdon','Protect the museum from a wave of curious slimes.','County Hall now houses the town museum.','https://www.abingdon.gov.uk/abingdon-county-hall-museum'],
 ['The Bun Throwing Beacon','Abingdon','Keep the celebration supplies safe.','Bun throwing from County Hall marks royal occasions.','https://www.abingdon.gov.uk/abingdon-county-hall-museum/about-the-museum'],
 ['Abbey Gardens Adventure','Abingdon','Hold the garden paths through the next wave.','Abbey Gardens is one of Abingdon’s places to explore.',town],
 ['Abbey Meadow Rally','Abingdon','Build a defence beside the meadow.','Abbey Meadow is part of the town’s riverside green space.',town],
 ['The Abbey Buildings','Abingdon','Guard the old stone doorways.','Surviving Abbey Buildings tell part of Abingdon’s history.',town],
 ['Abingdon Bridge Patrol','Abingdon','Stop the slimes at the crossing.','Abingdon Bridge was first built in 1416.','https://www.abingdon.gov.uk/abingdon_buildings/abingdon-bridge'],
 ['St Helen’s Wharf','Abingdon','Protect the riverside landing place.','St Helen’s Wharf sits beside the Thames.','https://www.abingdon.gov.uk/the-river-great-outdoors'],
 ['Where the Ock Meets the Thames','Abingdon','Hold the meeting point of the rivers.','The River Ock joins the Thames in Abingdon.','https://www.abingdon.gov.uk/feature-articles/abingdons-boundaries'],
 ['The Thames Guardians','Abingdon','Face the riverside boss together.','The Thames Path passes through Abingdon.','https://www.abingdon.gov.uk/the-river-great-outdoors'],
 ['Oxford’s Dreaming Spires','Oxford','Carry the Manor banner into the city.','Oxford is home to university libraries, museums and gardens.',oxford],
 ['The Bodleian Bookkeepers','Oxford','Keep the enchanted books in their reading rooms.','The Bodleian includes the Old Library, Weston Library and Radcliffe Camera.','https://visit.bodleian.ox.ac.uk/plan-your-visit/how-to-get-here'],
 ['Radcliffe Camera Watch','Oxford','Defend the famous domed landmark.','The Radcliffe Camera is a working library, not a camera shop.','https://bodreader.web.ox.ac.uk/libraries/radcliffe-camera'],
 ['The Weston Story Vault','Oxford','Protect the next chapter of the adventure.','The Weston Library stands on Broad Street.','https://visit.bodleian.ox.ac.uk/plan-your-visit/how-to-get-here'],
 ['Ashmolean Artefact Rescue','Oxford','Guard the gallery doors through an elite wave.','The Ashmolean is Oxford’s museum of art and archaeology.',oxford],
 ['Natural History Night Watch','Oxford','Keep the slimes away from the specimens.','Oxford’s Museum of Natural History houses natural-history collections.',oxford],
 ['Pitt Rivers Storykeepers','Oxford','Protect objects and the stories they carry.','The Pitt Rivers Museum holds collections from around the world.',oxford],
 ['The Botanic Garden Defence','Oxford','Protect the plants with a carefully placed squad.','Oxford Botanic Garden is the oldest botanic garden in Britain.',oxford],
 ['The Science Instrument Quest','Oxford','Guard the instruments before the final journey.','Oxford has a History of Science Museum.',oxford],
 ['Home to Manor Quest','Manor Quest','Bring everything you have learned home for the final defence.','Your squad returns to protect its home base.',''],
].map(([name,region,mission,fact,source])=>({name,region,mission,fact,source}));
export const CHAPTERS=CHAPTER_DETAILS.map(c=>c.name);
export function chapterFor(wave:number){const number=Math.floor((wave-1)/10)+1;return{...CHAPTER_DETAILS[Math.min(number-1,29)],number,name:CHAPTERS[number-1]??`Manor Legends ${number-30}`,stage:(wave-1)%10+1,boss:wave%10===0,elite:wave%10===5};}
