export const HEROES=[
 {name:'Bramble',role:'Ranger',price:60,power:12,range:4.5,cooldown:1.1,colour:'#ffe396',attack:'ARROW!',description:'Reliable arrows with a long reach.',tiers:['Scout','Eagle Eye','Master Ranger'],costs:[60,120],growth:[{range:.5,speed:.1},{range:1,speed:.2}],upgrade:['Longer reach and quicker arrows.','Maximum reach and rapid, powerful arrows.']},
 {name:'Luna',role:'Mage',price:100,power:22,range:3.5,cooldown:1.7,colour:'#c6a7ff',attack:'ZAP!',description:'Powerful magic against tough monsters.',tiers:['Apprentice','Moon Weaver','Archmage'],costs:[80,160],growth:[{range:.25,speed:.15},{range:.5,speed:.3}],upgrade:['Stronger spells with a shorter casting time.','Faster spells that reach further.']},
 {name:'Flint',role:'Guardian',price:140,power:34,range:1.8,cooldown:1.4,colour:'#ffcf6b',attack:'SLASH!',description:'Heavy sword strikes beside the path.',tiers:['Squire','Manor Knight','Champion'],costs:[100,200],growth:[{range:.3,speed:.15},{range:.6,speed:.3}],upgrade:['A longer blade and stronger strikes.','Champion strikes with extra reach and speed.']},
 {name:'Tempest',role:'Stormcaller',price:160,power:16,range:3.5,cooldown:1.6,colour:'#8de5ff',attack:'BOLT!',description:'Lightning hits two monsters each cast.',tiers:['Cloud Keeper','Thunder Wing','Storm Sage'],costs:[100,200],growth:[{range:.5,speed:.15},{range:1,speed:.3}],upgrade:['Stronger lightning and a wider storm.','Lightning strikes three targets at once.']},
 {name:'Pip',role:'Duellist',price:80,power:9,range:2,cooldown:.65,colour:'#d8ff9c',attack:'SWISH!',description:'Fast twin blades for tight corners.',tiers:['Trail Runner','Twinblade','Wind Dancer'],costs:[60,120],growth:[{range:.25,speed:.1},{range:.5,speed:.2}],upgrade:['Faster blades with a little more reach.','Lightning-fast strikes and stronger blades.']},
 {name:'Rowan',role:'Marksman',price:120,power:25,range:5.5,cooldown:2,colour:'#ffb887',attack:'BOLT!',description:'Crossbow bolts cover distant stretches.',tiers:['Lookout','Sharpshooter','Manor Sentinel'],costs:[80,160],growth:[{range:.75,speed:.15},{range:1.5,speed:.3}],upgrade:['Powerful bolts reach more of the path.','Seven-square reach with faster reloads.']},
 {name:'Ember',role:'Flamekeeper',price:180,power:18,range:2.8,cooldown:1.8,colour:'#ff9869',attack:'FLAME!',description:'Flames splash onto nearby monsters.',tiers:['Spark','Blaze','Inferno'],costs:[120,240],growth:[{range:.3,speed:.15},{range:.6,speed:.3}],upgrade:['Stronger flames and a wider splash.','A broad flame burst for crowded waves.']},
 {name:'Arrow Tower',role:'Tower',price:120,power:18,range:5,cooldown:1.3,colour:'#ffe396',attack:'VOLLEY!',description:'A steady crossbow covering long paths.',tiers:['Watchpost','Bolt Turret','Manor Ballista'],costs:[80,160],growth:[{range:.5,speed:.15},{range:1,speed:.3}],upgrade:['Faster crossbow reloads and longer reach.','Heavy bolts covering six squares.']},
 {name:'Crystal Tower',role:'Tower',price:200,power:20,range:4,cooldown:1.8,colour:'#d1a0ff',attack:'PULSE!',description:'Magic pulses strike two monsters at once.',tiers:['Crystal Spire','Arcane Beacon','Prismatic Keep'],costs:[120,240],growth:[{range:.5,speed:.15},{range:1,speed:.3}],upgrade:['Stronger pulses and a wider reach.','Prismatic energy hits three targets at once.']},
];
export function heroStats(type:number,level=1,weapon='standard'){const h=HEROES[type],bonus=level>1?h.growth[Math.min(level-2,1)]:null;const damage=level===0?0:h.power*level;const cooldown=Math.max(.25,h.cooldown-(bonus?.speed??0));return{damage:Math.round(damage*(weapon==='swift'||weapon==='frost'?.65:weapon==='blast'?.8:1)),range:h.range+(bonus?.range??0),cooldown:cooldown*(weapon==='swift'?.55:weapon==='blast'?1.35:1),targets:(type===3||type===8)?(level>=3?3:2):1,splash:weapon==='blast'?3.6:type===6?(level>=3?4.6:level===2?4.1:3.6):0,freeze:weapon==='frost'?.6:0};}
export function upgradeCost(type:number,level:number){return level>=3?null:[40,80][level-1]}

export const MAX_HEROES=2;
export function spawnCost(count:number){return count===0?120:600}
export const WEAPONS=[['Training bow','Longbow','Starshot bow'],['Oak staff','Moon staff','Astral staff'],['Iron sword','Knight blade','Champion blade'],['Storm wand','Thunder staff','Tempest sceptre'],['Practice blades','Twin daggers','Wind blades'],['Light crossbow','Reinforced crossbow','Eagle crossbow'],['Spark charm','Flame charm','Inferno gem'],['Wooden bolts','Steel bolts','Golden bolts'],['Quartz core','Amethyst core','Prismatic core']];
