import type {Question} from './questions';
// Original texts, aligned to upper KS2 retrieval, inference, vocabulary and authorial choices.
export const readingExpansion:Question[]=[];
type Row=[string,string,string,string[]?];
function text(id:string,title:string,passage:string,rows:Row[]){rows.forEach(([prompt,answer,explanation,options],i)=>readingExpansion.push({id:`reading-v2-${id}-${i+1}`,subject:'English',difficulty:'Year 6',passage:`${title}\n\n${passage}`,prompt,answers:answer.split('|'),explanation,...(options?{options}:{})}));}
text('bridge','The Model Bridge',`When the first bridge collapsed, Ella swept the broken straws towards herself. “We should have used my design,” she muttered. Yusuf said nothing. He turned one of the triangular supports over and examined the clean break at its corner.
At lunchtime, Ella found him testing different joints. Beside him lay a sheet headed “Things we have learnt”, rather than “Things that went wrong”. She sat down and held two straws steady while he tied them. By the afternoon, their bridge held twelve books. Ella wrote both their names on the display card, in letters exactly the same size.`,[
['What material formed the bridge? Type one word.','straws','The broken bridge is described as broken straws.'],
['What does Yusuf’s heading suggest about his attitude?','Mistakes can help them improve.','He records what they have learnt and tests better joints.',['Mistakes can help them improve.','Winning matters more than learning.','Ella must do all the work.','The bridge cannot be repaired.']],
['Why are the names written in letters of equal size?','Ella now values their shared contribution.','The equal lettering suggests that Ella gives Yusuf equal credit.',['Ella has forgotten who designed it.','Ella now values their shared contribution.','The display card is too small.','Yusuf insists on being first.']],
['How many books does the final bridge hold?','12|twelve','The final bridge holds twelve books.'],
['Which summary best captures the change in Ella?','She moves from blaming to cooperating.','She initially blames the design choice but later helps and shares credit.',['She moves from blaming to cooperating.','She stops caring about the project.','She learns that testing is unnecessary.','She decides to work entirely alone.']]
]);
text('river','Before the Rain',`The riverside path was usually a ribbon of pale dust. Today it was dark and soft beneath Amira’s boots. She noticed a twig racing past the landing stage, although the air was still. Farther upstream, brown water pressed against the lowest step.
“We can take the longer route,” her grandfather said. Amira glanced towards the bridge. The shortcut would save ten minutes, but the water was creeping over the path ahead. She folded the map and turned uphill. Behind them, the river swallowed the bottom step.`,[
['Which word shows the twig was moving quickly?','racing','“Racing” describes its rapid movement.'],
['What most likely moves the twig?','The river current','The air is still, while the twig moves along the water.',['The river current','A strong wind','Amira’s boots','The folded map']],
['Why does Amira choose the longer route?','The shortcut is becoming flooded.','Water is creeping over the path; the uphill route avoids it.',['She has lost the map.','The shortcut is becoming flooded.','The bridge has already collapsed.','She wants to find the twig.']],
['In “the river swallowed the bottom step”, what technique is used?','personification','The river is described as performing the living action of swallowing.',['Alliteration','Personification','Rhyme','Direct speech'].map(x=>x.toLowerCase())],
['How much time would the shortcut save, in minutes?','10|ten','The passage states that it would save ten minutes.']
]);
text('museum','The Unlabelled Object',`In the museum storeroom, Noah lifted a small wooden object from a padded tray. One end was polished smooth; the other had a narrow groove. “A toy boat?” he suggested.
Dr Bell did not answer immediately. She placed an old photograph beside it. In the picture, a weaver held a similar object beside a loom. Noah studied the groove again. A thin strand of thread remained caught inside it.
He crossed out “boat” in his notebook, but left the word readable. “Evidence can change an idea,” Dr Bell said. “It is useful to remember how you reached your answer.”`,[
['What material is the object made from?','wood','It is described as a wooden object.'],
['Which new evidence best links the object to weaving?','The photograph and the trapped thread','Both provide evidence connected with weaving, unlike its colour or size.',['Its small size alone','The padded tray','The photograph and the trapped thread','Noah’s first guess']],
['Why does Noah leave the crossed-out word readable?','To record how his thinking changed','Dr Bell explains that remembering the reasoning is useful.',['To record how his thinking changed','To hide his mistake','To confuse the next visitor','To claim that both guesses are certainly correct']],
['Copy the word meaning a long, narrow cut in the object.','groove','A groove is a narrow channel cut into a surface.'],
['Which statement is supported by the passage?','Noah revises his first idea.','He crosses out his first suggestion after examining evidence.',['The object is definitely a toy.','The object was found in a river.','Noah revises his first idea.','Dr Bell made the object.']]
]);
text('garden','A Patch for Pollinators',`Our school garden used to have a neatly clipped lawn right up to the fence. This year, the gardening club left a strip beside the fence uncut and planted flowers that bloom at different times. The patch looks less tidy, but pupils have recorded more visiting insects there than on the short grass.
The club’s report does not claim that every insect benefits equally. It notes that observations took place on warm afternoons, when many insects are active. Next term, pupils plan to count visitors at different times of day. They will also keep a section of short grass for comparison.`,[
['Where was the uncut strip left?','by the fence|beside the fence|at the fence|along the fence|the fence|fence','The lawn previously reached the fence; the strip is the edge being discussed.'],
['Why keep a section of short grass?','To compare insect visits in the two areas','A comparison helps assess differences between habitats.',['To compare insect visits in the two areas','To stop all insects entering','To avoid recording results','To remove every flower']],
['Which limitation does the report acknowledge?','Observations were only made on warm afternoons.','The timing may affect which insects were observed.',['No insects were counted.','Observations were only made on warm afternoons.','All the plants died.','The patch has no fence.']],
['Why choose flowers that bloom at different times?','To provide flowers over a longer period','Different flowering times extend the period when flowers are available.',['To make all flowers open on one day','To provide flowers over a longer period','To prevent any insect visits','To keep the grass shorter']],
['Which is an opinion rather than a recorded observation?','The untidy patch is the prettiest part of school.','“Prettiest” expresses a personal judgement.',['The club left a strip uncut.','Pupils observed insects on warm afternoons.','The untidy patch is the prettiest part of school.','The club plans more counts.']]
]);
text('stage','Waiting in the Wings',`The curtain trembled as someone hurried past. Behind it, Priya pressed her palms together and silently shaped the first line of her speech. From the hall came a cough, then the scraping of a chair. She wished the audience would make more noise; every tiny sound seemed enormous.
When her cue came, she stepped into the light. For a moment the words vanished. Then she spotted Ben in the front row, mouthing the opening phrase. Priya breathed out. Her voice began quietly, but by the end it reached the back of the hall.`,[
['What does Priya’s behaviour suggest before her entrance?','She is nervous about performing.','Her silent rehearsal and heightened awareness of sounds indicate nerves.',['She is nervous about performing.','She is bored with the audience.','She has already finished.','She is angry with Ben.']],
['Who helps Priya remember the opening?','ben','Ben mouths the opening phrase from the front row.'],
['What does “the words vanished” mean here?','She temporarily forgets what to say.','It describes a lapse in memory, not words physically disappearing.',['The script is burnt.','She temporarily forgets what to say.','The audience leaves.','The lights switch off.']],
['Which change suggests growing confidence?','Her voice reaches the back of the hall.','Her voice becomes stronger as she continues.',['The chair scrapes.','The curtain trembles.','Her voice reaches the back of the hall.','Someone coughs.']],
['Copy the word that means a signal to begin.','cue','A cue signals when a performer should start.']
]);
text('poem','The Library at Dusk',`The windows hold the fading gold,\nThe shelves stand shoulder, straight and tall.\nA thousand journeys, tightly folded,\nWait without a sound at all.\n\nI lift a cover: oceans wake,\nA forest stirs beyond the door.\nThe room stays still; yet with each page,\nMy feet find lands unknown before.`,[
['What do the “thousand journeys” most likely represent?','The experiences offered by books','The speaker opens a cover and imagines other places.',['The experiences offered by books','The distance to school','The number of library windows','Actual boats outside']],
['Which phrase best shows a contrast between real stillness and imagined travel?','The room stays still; yet with each page','“Yet” contrasts the unchanged room with the imagined journey.',['The windows hold','The room stays still; yet with each page','Without a sound at all','Straight and tall']],
['Which two words at the ends of lines rhyme in the first verse? Type them with “and”.','tall and all|all and tall','Tall and all share the same ending sound.'],
['What is the main theme of the poem?','Reading can take the imagination to new places.','The speaker remains in a room while imagining distant lands.',['Reading can take the imagination to new places.','Libraries should have more windows.','Walking is always better than reading.','Oceans are louder than forests.']],
['Copy the word that tells us the gold light is becoming weaker.','fading','“Fading” describes the diminishing evening light.']
]);
text('letter','A Letter to the Council',`Dear Councillors,\nI am writing on behalf of our cycling club to ask for more bicycle stands beside the leisure centre. Last Saturday, all eight stands were occupied before our lesson began. Three members had to leave their bicycles against a wall.
Extra stands would help visitors secure their bicycles and keep the entrance clear. We understand that space is limited, so we suggest replacing one unused noticeboard rather than widening the paved area. Could you visit during a busy session before making a decision?\nYours faithfully,\nLeah, club secretary`,[
['What is the main purpose of this letter?','To persuade the council to add bicycle stands','The writer requests a change and supports it with reasons.',['To describe a cycling race','To persuade the council to add bicycle stands','To advertise a new bicycle','To complain about swimming lessons']],
['How many existing stands were occupied?','8|eight','All eight stands were occupied.'],
['Why mention the unused noticeboard?','It offers a solution to the shortage of space.','Removing it is proposed as a way to fit stands without widening the area.',['It offers a solution to the shortage of space.','It proves nobody visits.','It changes the subject completely.','It describes the club’s prize.']],
['Which detail provides evidence for the request?','Three members had to use a wall for their bicycles.','This is a specific example of insufficient stands.',['The writer likes cycling.','Three members had to use a wall for their bicycles.','The council has a name.','The letter ends politely.']],
['What role does Leah hold in the club?','secretary|club secretary','The signature identifies Leah as club secretary.']
]);
text('diary','The Second Attempt',`Monday\nI thought measuring the playground would be easy. We stretched the tape, wrote down 32 metres and rushed inside. Only when we drew the plan did I notice the fence was longer than the side we had measured. Our “rectangle” was actually a shape with an extra corner.
Tuesday\nWe returned with clipboards and a sketch. This time, each person checked a different edge. It took longer, but our measurements fitted the drawing. I used to think careful work meant never making mistakes. Now I think it means noticing them and trying again.`,[
['What made the first plan inaccurate?','They treated an irregular shape as a rectangle.','They missed an extra corner and did not measure each edge.',['The tape was certainly broken.','They treated an irregular shape as a rectangle.','The playground moved.','They used metres instead of hours.']],
['On which day did they return with a sketch?','tuesday','The Tuesday entry describes returning with clipboards and a sketch.'],
['Which feature most clearly identifies this as a diary?','Dated entries describing personal experiences','The text uses day headings and first-person reflection.',['A list of prices','Dated entries describing personal experiences','An address to councillors','Rhyming lines']],
['How does the writer’s view of careful work change?','Checking and correcting mistakes becomes important.','The last sentences explicitly describe this change.',['Speed becomes the only goal.','Checking and correcting mistakes becomes important.','Measuring is no longer necessary.','Mistakes must be hidden.']],
['What unit was used for the first measurement?','metres|metre|m','The first recorded measurement was 32 metres.']
]);
text('notice','Repair Café Notice',`Saturday Repair Café\n10 am–1 pm, community hall\nBring a small broken household item and work with a volunteer to investigate the fault. Please bring any instruction booklet you still have. Repairs are free, but donations towards materials are welcome. Children must attend with an adult.
We cannot accept gas appliances or items with leaking batteries. A repair is not guaranteed: sometimes a replacement part must be ordered. Our aim is to help people learn repair skills and reduce unnecessary waste. Please arrive before noon so that volunteers have time to assess your item.`,[
['What is the latest arrival time requested?','before noon|before 12|before 12 pm|before 12:00','The notice asks visitors to arrive before noon.'],
['Which item does the notice explicitly refuse?','An item with leaking batteries','Leaking batteries and gas appliances are excluded.',['A small broken lamp','An item with leaking batteries','An instruction booklet','A household clock']],
['Why does the notice say a repair is not guaranteed?','A replacement part may need to be ordered.','The notice gives this as one reason a repair may not be completed.',['All volunteers are absent.','A replacement part may need to be ordered.','Visitors must buy new items.','The hall closes at 10 am.']],
['Which statement about payment is accurate?','Repairs are free; donations are optional.','Donations are welcome, not compulsory.',['Every repair costs £10.','Children must pay extra.','Repairs are free; donations are optional.','Materials can never be donated.']],
['Who must accompany a child?','an adult|adult','Children must attend with an adult.']
]);
text('team','The Quiet Captain',`During practice, everyone wanted to take the final shot. Captain Rosa watched three passes go astray while her teammates called for the ball. Instead of choosing the loudest player, she asked the team to repeat the move slowly.
“Look before you pass,” she said. On the next attempt, Max noticed that Asha had moved into open space. He passed to her, and she scored. Rosa clapped first. At the tournament, she reminded them of the practice, not the score. “A chance is something we make together.”`,[
['Why does Rosa slow the practice down?','To help players notice positions and make better passes','The successful attempt follows her instruction to look before passing.',['To punish Asha for scoring','To help players notice positions and make better passes','To stop anyone touching the ball','To finish practice immediately']],
['Who passes the ball to Asha?','max','Max notices Asha and passes to her.'],
['What does “go astray” mean in this context?','Fail to reach the intended player','The phrase describes misplaced passes.',['Travel exactly as planned','Become louder','Fail to reach the intended player','Win the tournament']],
['Which quality does Rosa show most clearly?','Thoughtful leadership','She observes a problem and helps the team solve it together.',['Thoughtful leadership','Impatience with all practice','A wish to score every point herself','Indifference to teamwork']],
['What is the main message of Rosa’s final remark?','Good opportunities depend on cooperation.','She emphasises making chances together.',['The loudest player should always shoot.','Good opportunities depend on cooperation.','Only the final score matters.','Practice should be avoided.']]
]);
text('storm','After the Storm',`By morning, the storm had scattered branches across the lane. Mr Khan stood beside his damaged fence, holding a hammer but not using it. Across the road, Zoe’s mother was already clearing a fallen branch from the pavement.
Zoe fetched gloves and joined her. Soon a neighbour brought a saw, and another arrived with a wheelbarrow. Mr Khan put down his hammer and held the gate open for them. Later, when the lane was clear, the group carried spare timber to his garden. This time, he picked up the hammer with a smile.`,[
['What had the storm scattered across the lane?','branches','The opening sentence names the scattered branches.'],
['Why is Mr Khan most likely not using the hammer at first?','He seems unsure how to tackle the damage.','His stillness beside the damage suggests hesitation; the text does not say the hammer is broken.',['He has already repaired everything.','He seems unsure how to tackle the damage.','He dislikes every neighbour.','His hammer has definitely snapped.']],
['What does Mr Khan do to help the group?','Holds the gate open','He puts down the hammer and opens the gate for them.',['Hides the wheelbarrow','Holds the gate open','Closes the pavement','Takes away their gloves']],
['Why does the hammer appear near both the beginning and end?','It highlights the change in Mr Khan’s mood.','Initially unused, it is later picked up with a smile after help arrives.',['It proves no time has passed.','It highlights the change in Mr Khan’s mood.','It shows the storm has restarted.','It explains how gloves are made.']],
['Which theme best fits the story?','Neighbours helping one another','People clear shared space and then help repair the fence.',['Neighbours helping one another','Winning an individual prize','Keeping discoveries secret','Avoiding all responsibility']]
]);
text('comparison','Two Views of a Journey',`Account A — Oliver\nThe coach journey felt endless. Every time I looked up, another field slid past. I had finished my puzzle before we reached the motorway. At last, the museum roof appeared, and I could stop counting road signs.
Account B — Nia\nI sat beside the window with my sketchbook. The fields changed from green to gold, and I tried to capture the shapes of passing trees. When we reached the museum, I was halfway through a drawing and wished for five more minutes.`,[
['How do the writers’ feelings about the journey differ?','Oliver is bored; Nia is absorbed in drawing.','Oliver counts signs and wants to arrive; Nia wants more drawing time.',['Both wish the journey were longer.','Oliver is bored; Nia is absorbed in drawing.','Nia is bored; Oliver enjoys sketching.','Both sleep throughout.']],
['What is the destination of both journeys?','museum|the museum','Both accounts mention arriving at the museum.'],
['Which detail best supports the idea that Oliver is bored?','He starts counting road signs.','Counting signs follows finishing his puzzle and wishing to arrive.',['He has a sketchbook.','He starts counting road signs.','He asks for five more minutes.','He draws passing trees.']],
['Why does Nia wish for more time?','She wants to continue her unfinished drawing.','She is only halfway through a drawing on arrival.',['She has lost the coach.','She wants to continue her unfinished drawing.','She dislikes all museums.','She has not started travelling.']],
['Which statement applies to both accounts?','They describe the same destination from different viewpoints.','Both arrive at a museum, but describe different experiences of travelling.',['They describe the same destination from different viewpoints.','They contain identical opinions.','They are instructions for driving.','They give no personal reactions.']]
]);
const grammar:Row[]=[
['Choose the sentence in the passive voice.','The trophy was polished by Mia.','The subject, the trophy, receives the action.',['Mia polished the trophy.','The trophy was polished by Mia.','Mia is polishing the trophy.','Mia will polish the trophy.']],
['Copy the modal verb: “The team might reach the final.”','might','Might expresses possibility.'],
['Choose the sentence using the subjunctive form.','If I were captain, I would listen carefully.','Were expresses an imagined situation.',['If I was the captain yesterday, I forgot.','If I were captain, I would listen carefully.','I am the captain today.','I became the captain last week.']],
['Which punctuation mark can join these related independent clauses: “The rain stopped __ we went outside”?','semicolon|;','A semicolon can link two closely related main clauses.'],
['Choose the correctly punctuated list introduction.','Bring three things: a pencil, a ruler and a rubber.','The colon follows a complete introductory clause.',['Bring: three things a pencil, a ruler and a rubber.','Bring three things: a pencil, a ruler and a rubber.','Bring three: things a pencil a ruler and a rubber.','Bring three things a: pencil, a ruler and a rubber.']],
['Copy the relative pronoun: “The book, which had a torn cover, was still readable.”','which','Which introduces the relative clause about the book.'],
['Choose the sentence with correct plural possession.','The teachers’ room was upstairs.','The apostrophe after teachers shows possession by more than one teacher.',['The teachers’ room was upstairs.','The teachers room was upstairs.','The teacher’s room belonged to several teachers.','The teachers’s room was upstairs.']],
['Add a prefix to “possible” to make its opposite. Type the complete word.','impossible','The prefix im- changes possible to impossible.'],
['Which word is a synonym for “reluctant”?','unwilling','Reluctant means hesitant or unwilling.',['unwilling','delighted','certain','careless']],
['Choose the more formal request.','Could you please provide further information?','Provide further information is more formal vocabulary.',['Tell me more stuff!','Could you please provide further information?','Give us the details, yeah?','What’s all that about?']],
['Copy the subordinating conjunction: “Unless we leave now, we will miss the train.”','unless','Unless introduces a condition.'],
['Which sentence uses a hyphen to make the meaning clearer?','We saw a man-eating shark in the film.','Man-eating describes the shark as one that eats people.',['We saw a man-eating shark in the film.','We-saw a man eating shark in the film.','We saw a man eating-shark in the film.','We saw a man eating shark-in the film.']],
['Choose the correct word: “The weather will ___ our plans.”','affect','Affect is the verb meaning influence.',['effect','affect','effects','affection']],
['Choose the correct word: “Please put the books over ___.”','there','There indicates a place.',['their','they’re','there','theirs']],
['What is the subject of “The exhausted runners crossed the finish line”?','the exhausted runners|exhausted runners','The exhausted runners are performing the action.'],
['Choose the sentence in the present perfect.','She has finished her drawing.','Has plus the past participle finished forms the present perfect.',['She finished her drawing yesterday.','She is finishing her drawing.','She has finished her drawing.','She will finish her drawing.']],
['Copy the adverb showing certainty: “The parcel will definitely arrive tomorrow.”','definitely','Definitely expresses certainty.'],
['Which ending turns “curious” into a noun? Type the whole noun.','curiosity','Curious becomes curiosity, with a spelling change.'],
['Choose the correctly punctuated direct speech.','“Wait here,” said Omar.','The spoken words are enclosed in quotation marks, with a comma before the reporting clause.',['“Wait here,” said Omar.','“Wait here, said Omar.”','“Wait here” said, Omar.','Wait “here, said Omar.”']],
['Which sentence places commas correctly around extra information?','Lena, our goalkeeper, saved the shot.','The paired commas enclose additional information about Lena.',['Lena our, goalkeeper saved, the shot.','Lena, our goalkeeper, saved the shot.','Lena our goalkeeper, saved, the shot.','Lena, our goalkeeper saved the shot.']]
];
grammar.forEach(([prompt,answer,explanation,options],i)=>readingExpansion.push({id:`english-v2-language-${i+1}`,subject:'English',difficulty:'Year 6',prompt,answers:answer.split('|'),explanation,...(options?{options}:{})}));
