import {HEROES} from './heroes';
import {env} from 'cloudflare:workers';
import {simulate,rules,type Battle} from './battle';
export function db(){if(!env.DB) throw new Error('Your class world is temporarily unavailable. Please try again.');return env.DB;}
export type Player={name:string;coins:number;correct:number;incorrect:number;subjects:Record<string,{correct:number;incorrect:number}>;history:Record<string,{correct:boolean;at:number}>;active?:{id:string;token:string;at:number};hero:number;outfit:string;owned:string[];waveAnswers:number;joined:number};
export type Defender={id:string;owner:string;type:number;level:number;cell:number};
export type World={wave:number;players:Record<string,Player>;defenders:Defender[];battle:Battle|null;result:null|{won:boolean;wave:number;at:number;power:number;target:number;contributors:number;killed:number;count:number}};
export const TYPES=HEROES;
export function fresh():World{return{wave:1,players:{},defenders:[],battle:null,result:null}}
export function power(w:World){return w.defenders.reduce((s,d)=>s+TYPES[d.type].power*d.level,0)}
export function target(w:World){return 170+70*(w.wave-1)}
export function beginBattle(w:World){if(w.battle)throw new Error('A wave is already in progress.');w.battle={start:Date.now(),wave:w.wave,duration:rules(w.wave).duration,power:power(w),target:target(w),contributors:Object.values(w.players).filter(p=>p.waveAnswers>0).length,fighters:w.defenders.map(d=>({id:d.id,type:d.type,level:d.level,cell:d.cell,owner:d.owner,name:w.players[d.owner]?.name??'Hero'}))};const sim=simulate(w.battle);if(sim.killed===sim.count&&w.battle.contributors>=4)w.battle.duration=Math.max(12000,Math.max(...sim.deathAt.map(t=>t??0))*1000+3000);}
export function finish(w:World){if(w.battle&&Date.now()-w.battle.start>=w.battle.duration){const b=w.battle;const sim=simulate(b);const won=sim.killed===sim.count&&b.contributors>=4;w.result={won,wave:w.wave,at:Date.now(),power:b.power,target:b.target,contributors:b.contributors,killed:sim.killed,count:sim.count};w.battle=null;if(won){w.wave++;Object.values(w.players).forEach(p=>{p.waveAnswers=0})}}}

export async function readWorld(){await db().prepare('INSERT OR IGNORE INTO world (id,revision,data) VALUES (?,?,?)').bind('class',0,JSON.stringify(fresh())).run();const row=await db().prepare('SELECT revision,data FROM world WHERE id=?').bind('class').first<{revision:number;data:string}>();if(!row)throw new Error('Class world unavailable');return{revision:row.revision,w:JSON.parse(row.data) as World}}
export async function mutate<T>(fn:(w:World)=>T):Promise<T>{for(let i=0;i<8;i++){const{w,revision}=await readWorld();finish(w);const result=fn(w);const r=await db().prepare('UPDATE world SET data=?, revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify(w),'class',revision).run();if(r.meta.changes===1)return result;}throw new Error('Your class is busy. Please try again.');}
export function newPlayer(name:string):Player{return{name,coins:0,correct:0,incorrect:0,subjects:{},history:{},hero:0,outfit:'classic',owned:['classic'],waveAnswers:0,joined:Date.now()}}
export function view(w:World,uid:string|null){return{isTeacher:uid==='teacher',wave:w.wave,power:power(w),target:target(w),contributors:Object.values(w.players).filter(p=>p.waveAnswers>0).length,battle:w.battle,result:w.result,defenders:w.defenders.map(d=>({...d,name:w.players[d.owner]?.name,hero:w.players[d.owner]?.hero,outfit:w.players[d.owner]?.outfit})),players:Object.entries(w.players).map(([id,p])=>({id,name:p.name,hero:p.hero,outfit:p.outfit,contributed:p.waveAnswers>0})),me:uid&&w.players[uid]?{id:uid,...((({history,active,...p})=>p)(w.players[uid]))}:null,serverNow:Date.now()}}
export async function sha(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function user(req:Request){const cookie=req.headers.get('cookie')?.match(/(?:^|;\s*)qg_session=([^;]+)/)?.[1];if(!cookie)return null;const row=await db().prepare('SELECT user_id FROM sessions WHERE token=? AND expires>?').bind(await sha(cookie),Date.now()).first<{user_id:string}>();return row?.user_id??null}
export function requireOrigin(req:Request){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new Error('Please submit from the game page.');}
export function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store'}})}
