import {ensureWardrobe,type Wardrobe} from './clothing';
import {TEAM_COLOURS,assignedColours} from './colours';
import {HEROES} from './heroes';
import {env} from '@/lib/runtime-env';
import {simulate,rules,type Battle} from './battle';
export function db(){if(!env.DB) throw new Error('Your class world is temporarily unavailable. Please try again.');return env.DB;}
export type Player={name:string;colourId?:number;coins:number;correct:number;incorrect:number;subjects:Record<string,{correct:number;incorrect:number}>;history:Record<string,{correct:boolean;at:number}>;active?:{id:string;token:string;at:number};hero:number;heroLocked?:boolean;gender?:'boy'|'girl';uniform?:string;uniforms?:string[];clothing?:Wardrobe;clothingOwned?:string[];outfit:string;owned:string[];waveAnswers:number;joined:number};
export type Defender={id:string;owner:string;type:number;level:number;cell:number;weapon?:string;weapons?:string[];weaponLevels?:Record<string,number>};
export type World={wave:number;players:Record<string,Player>;defenders:Defender[];battle:Battle|null;result:null|{won:boolean;wave:number;at:number;power:number;target:number;contributors:number;killed:number;count:number}};
export const TYPES=HEROES;
export function fresh():World{return{wave:1,players:{},defenders:[],battle:null,result:null}}
export function power(w:World){return w.defenders.reduce((s,d)=>s+TYPES[d.type].power*d.level,0)}
export function target(w:World){return 170+70*(w.wave-1)}
export function beginBattle(w:World){if(w.battle)throw new Error('A wave is already in progress.');w.battle={rulesVersion:2,start:Date.now(),wave:w.wave,duration:rules(w.wave).duration,power:power(w),target:target(w),contributors:Object.values(w.players).filter(p=>p.waveAnswers>0).length,fighters:w.defenders.map(d=>({id:d.id,type:d.type,level:d.level,weapon:d.weapon,cell:d.cell,owner:d.owner,name:w.players[d.owner]?.name??'Hero',gender:w.players[d.owner]?.gender,clothing:w.players[d.owner]?.clothing,uniform:w.players[d.owner]?.uniform??'none',outfit:w.players[d.owner]?.outfit,colour:TEAM_COLOURS[assignedColours(w.players)[d.owner]]?.css}))};const sim=simulate(w.battle);if(sim.killed===sim.count)w.battle.duration=Math.max(12000,Math.max(...sim.deathAt.map(t=>t??0))*1000+3000);}
export function finish(w:World){if(w.battle&&Date.now()-w.battle.start>=w.battle.duration){const b=w.battle;const sim=simulate(b);const won=sim.killed===sim.count;w.result={won,wave:w.wave,at:Date.now(),power:b.power,target:b.target,contributors:b.contributors,killed:sim.killed,count:sim.count};w.battle=null;if(won){w.wave++;Object.values(w.players).forEach(p=>{p.waveAnswers=0})}}}

export async function readWorld(){await db().prepare('INSERT OR IGNORE INTO world (id,revision,data) VALUES (?,?,?)').bind('class',0,JSON.stringify(fresh())).run();const row=await db().prepare('SELECT revision,data FROM world WHERE id=?').bind('class').first<{revision:number;data:string}>();if(!row)throw new Error('Class world unavailable');const w=JSON.parse(row.data) as World;Object.values(w.players).forEach(ensureWardrobe);return{revision:row.revision,w}}
export async function mutate<T>(fn:(w:World)=>T):Promise<T>{for(let i=0;i<8;i++){const{w,revision}=await readWorld();finish(w);const result=fn(w);const r=await db().prepare('UPDATE world SET data=?, revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify(w),'class',revision).run();if(r.meta.changes===1)return result;}throw new Error('Your class is busy. Please try again.');}
export function newPlayer(name:string):Player{return{name,coins:0,correct:0,incorrect:0,subjects:{},history:{},hero:0,uniform:'none',uniforms:[],clothing:{},clothingOwned:[],outfit:'none',owned:[],waveAnswers:0,joined:Date.now()}}
export function view(w:World,uid:string|null){const colours=assignedColours(w.players);return{isTeacher:uid==='teacher',wave:w.wave,power:power(w),target:target(w),contributors:Object.values(w.players).filter(p=>p.waveAnswers>0).length,battle:w.battle,result:w.result,defenders:w.defenders.map(d=>({...d,name:w.players[d.owner]?.name,hero:w.players[d.owner]?.hero,gender:w.players[d.owner]?.gender,clothing:w.players[d.owner]?.clothing,uniform:w.players[d.owner]?.uniform??'none',outfit:w.players[d.owner]?.outfit,colour:TEAM_COLOURS[colours[d.owner]]?.css})),players:Object.entries(w.players).map(([id,p])=>({id,colourId:colours[id],colour:TEAM_COLOURS[colours[id]]?.css,name:p.name,hero:p.hero,gender:p.gender,clothing:p.clothing,uniform:p.uniform??'none',outfit:p.outfit,contributed:p.waveAnswers>0})),me:uid&&w.players[uid]?{id:uid,...((({history,active,...p})=>p)(w.players[uid])),colourId:colours[uid],colour:TEAM_COLOURS[colours[uid]]?.css}:null,serverNow:Date.now()}}
export async function sha(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function user(req:Request){const cookie=req.headers.get('cookie')?.match(/(?:^|;\s*)qg_session=([^;]+)/)?.[1];if(!cookie)return null;const row=await db().prepare('SELECT user_id FROM sessions WHERE token=? AND expires>?').bind(await sha(cookie),Date.now()).first<{user_id:string}>();return row?.user_id??null}
export function requireOrigin(req:Request){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new Error('Please submit from the game page.');}
export function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store'}})}
