import {isOnline} from './presence';
import {roundStatus,assignedYear,matchesYear} from './question-policy';
import {questionById,publicQuestion} from './questions';
import {buildStats,type ItemLoadout} from './builds';
import {ensureWardrobe,type Wardrobe} from './clothing';
import {rideLook} from './vehicles';
import {TEAM_COLOURS,assignedColours} from './colours';
import {HEROES,spawnCost} from './heroes';
import {env} from '@/lib/runtime-env';
import {simulate,rules,isBuildable,autoRidePlan,type Battle} from './battle';
import {mapLayout} from './map-layout';
import {chapterFor} from './chapters';
import type {HelpRequest} from './friend-help';
import type {ChatFlag} from './chat-rules';
import type {MockState,MockResult} from './mock-tests';
/** A pupil's report that a question looks wrong; the teacher sees it with the answer and explanation. */
export type QuestionReport={id:string;question:string;owner:string;name:string;reason:string;note?:string;at:number;resolvedAt?:number};
export function db(){if(!env.DB) throw new Error('Your class world is temporarily unavailable. Please try again.');return env.DB;}
export type Player=ItemLoadout & {lastSeen?:number;assignedYear?:2|6;questionRound?:Record<string,number>;mock?:MockState;mockResults?:MockResult[];mockLast?:Record<string,number>;learningYear?:2|6;unlimitedCoins?:boolean;combat?:{kills:number;damage:number;controlSeconds:number;assistedDamage:number;battles:number;wins:number};mistakes?:Record<string,{attempts:number;lastWrongAt:number;lastAnswer?:string;correctedAt?:number;help?:HelpRequest}>;helpChecks?:Record<string,{correct:boolean;at:number}>;chatConduct?:{week:string;count:number};receipts?:{id:string;body:string}[];reserveRefund?:{coins:number;heroes:number};name:string;colourId?:number;coins:number;correct:number;incorrect:number;subjects:Record<string,{correct:number;incorrect:number}>;history:Record<string,{correct:boolean;at:number;attempted?:boolean}>;active?:{id:string;token:string;at:number;reward?:number};hero:number;heroLocked?:boolean;gender?:'boy'|'girl';uniform?:string;uniforms?:string[];clothing?:Wardrobe;clothingOwned?:string[];vehiclesOwned?:string[];vehicle?:string;vehiclePaint?:Record<string,string>;outfit:string;owned:string[];waveAnswers:number;joined:number};
export type Defender={id:string;owner:string;type:number;level:number;cell:number;weapon?:string;weapons?:string[];weaponLevels?:Record<string,number>;vehicle?:string};
export type World={reports?:QuestionReport[];chat?:{id:string;owner:string;name:string;text:string;at:number}[];chatFlags?:ChatFlag[];revision?:number;battleVersion?:number;routeFrom?:number;reserveRefunds?:boolean;wave:number;players:Record<string,Player>;defenders:Defender[];battle:Battle|null;result:null|{schoolHealth?:number|null;escaped?:number;won:boolean;wave:number;at:number;power:number;target:number;contributors:number;killed:number;count:number;contributions?:Record<string,{kills:number;damage:number;controlSeconds:number;assistedDamage:number}>}};
export const TYPES=HEROES;
export function fresh():World{return{wave:1,players:{},defenders:[],battle:null,result:null}}
export function power(w:World){return w.defenders.filter(d=>d.cell>=0).reduce((s,d)=>s+TYPES[d.type].power*d.level,0)}
export function target(w:World){return 170+70*(w.wave-1)}
export function beginBattle(w:World,expectedVersion:number){if(expectedVersion!==(w.battleVersion??0))throw new Error('The class battle has changed. Refresh and join your classmates.');if(w.battle)throw new Error('A wave is already in progress.');w.battleVersion=(w.battleVersion??0)+1;w.battle={rulesVersion:5,seed:Math.floor(Math.random()*4294967296),start:Date.now(),wave:w.wave,route:mapLayout(w.wave,5,w.routeFrom).waypoints,duration:rules(w.wave).duration,power:power(w),target:target(w),contributors:Object.values(w.players).filter(p=>p.waveAnswers>0).length,fighters:w.defenders.filter(d=>d.cell>=0).map(d=>({stats:buildStats(d.type,d.level,d.weapon,w.players[d.owner]),id:d.id,type:d.type,level:d.level,weapon:d.weapon,cell:d.cell,owner:d.owner,name:w.players[d.owner]?.name??'Hero',gender:w.players[d.owner]?.gender,clothing:w.players[d.owner]?.clothing,uniform:w.players[d.owner]?.uniform??'none',outfit:w.players[d.owner]?.outfit,colour:TEAM_COLOURS[assignedColours(w.players)[d.owner]]?.css}))};for(const plan of autoRidePlan(w.battle,w.defenders,d=>defenderRide(w,d)?.id,id=>w.battle!.fighters.find(f=>f.id===id)?.stats?.range??1.2,w.routeFrom)){const d=w.defenders.find(x=>x.id===plan.id);if(d)d.cell=plan.to;(w.battle.rideMoves??=[]).push(plan.move);}const sim=simulate(w.battle);w.battle.duration=Math.max(12000,sim.endedAt*1000+3000);}
export function finish(w:World){if(w.battle&&Date.now()-w.battle.start>=w.battle.duration){const b=w.battle;const sim=simulate(b);const won=sim.won;w.result={schoolHealth:sim.schoolHealth,escaped:sim.breaches.length,won,wave:w.wave,at:Date.now(),power:b.power,target:b.target,contributors:b.contributors,killed:sim.killed,count:sim.count,contributions:sim.contributions};for(const [id,c] of Object.entries(sim.contributions)){const p=w.players[id];if(!p)continue;p.combat??={kills:0,damage:0,controlSeconds:0,assistedDamage:0,battles:0,wins:0};p.combat.kills+=c.kills??0;p.combat.damage+=c.damage;p.combat.controlSeconds+=c.controlSeconds;p.combat.assistedDamage+=c.assistedDamage;p.combat.battles++;if(won)p.combat.wins++;}w.battle=null;if(won){const nextChapter=w.wave%10===0;w.wave++;if(nextChapter)w.defenders.forEach(d=>{d.cell=-1});Object.values(w.players).forEach(p=>{p.waveAnswers=0})}}}

export async function readWorld(){await db().prepare('INSERT OR IGNORE INTO world (id,revision,data) VALUES (?,?,?)').bind('class',0,JSON.stringify(fresh())).run();const row=await db().prepare('SELECT revision,data FROM world WHERE id=?').bind('class').first<{revision:number;data:string}>();if(!row)throw new Error('Class world unavailable');const w=JSON.parse(row.data) as World;w.revision=Number(row.revision);w.battleVersion??=0;w.routeFrom??=chapterFor(w.wave).number+1;refundReserveDeploys(w);Object.entries(w.players).forEach(([id,p])=>{p.heroLocked??=w.defenders.some(d=>d.owner===id);ensureWardrobe(p);p.itemInventory??={};p.equippedItems??=[];p.itemSlots??=2;p.combat??={kills:0,damage:0,controlSeconds:0,assistedDamage:0,battles:0,wins:0};if(!p.mistakes){p.mistakes={};for(const [qid,h] of Object.entries(p.history))if(!h.correct&&h.attempted!==false)p.mistakes[qid]={attempts:1,lastWrongAt:h.at};}});assignLegacyRides(w);if(!w.battle)for(const d of w.defenders)if(d.cell>=0&&!isBuildable(d.cell,w.wave,w.routeFrom))d.cell=-1;return{revision:Number(row.revision),w}}
// One-off: before placing reserve heroes again was free on the server, pupils could pay for a new hero while their own heroes
// waited in reserve after a new chapter. Receipts are the only purchase history. A hero still on the square where it was bought
// was bought after the latest chapter reset; if an older hero of the same pupil was still in reserve then (it still is, or it was
// only placed back afterwards) the purchase is refunded and the pupil keeps the hero. "Placed back afterwards" is only trusted when
// a hero somewhere in the class is still in reserve, which shows a chapter reset has actually happened.
export function refundReserveDeploys(w:World){if(w.reserveRefunds)return;w.reserveRefunds=true;const resetSeen=w.defenders.some(d=>d.cell<0);
 for(const [id,p] of Object.entries(w.players)){if(p.unlimitedCoins)continue;const own=w.defenders.filter(d=>d.owner===id),log=(p.receipts??[]).map(r=>{try{return JSON.parse(r.body)}catch{return{}}}),recruits=log.flatMap((b,t)=>b.action==='recruit'?[t]:[]);if(recruits.length>own.length)continue;
  const placedAfter=(d:Defender,t:number)=>log.some((b,s)=>s>t&&b.action==='move'&&b.id===d.id);let coins=0,heroes=0;
  recruits.forEach((t,k)=>{const j=own.length-recruits.length+k,d=own[j];if(j>0&&d.cell>=0&&!placedAfter(d,t)&&own.slice(0,j).some(o=>o.cell<0||resetSeen&&placedAfter(o,t))){coins+=spawnCost(j);heroes++;}});
  if(coins){p.coins+=coins;p.reserveRefund={coins,heroes};}}}
export async function mutate<T>(fn:(w:World)=>T):Promise<T>{for(let i=0;i<8;i++){const{w,revision}=await readWorld();finish(w);w.revision=revision+1;const result=fn(w);const r=await db().prepare('UPDATE world SET data=?, revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify(w),'class',revision).run();if(r.meta.changes===1)return result;}throw new Error('Your class is busy. Please try again.');}
export function newPlayer(name:string):Player{return{name,itemInventory:{},equippedItems:[],itemSlots:2,coins:0,correct:0,incorrect:0,subjects:{},history:{},hero:0,heroLocked:false,uniform:'none',uniforms:[],clothing:{},clothingOwned:[],outfit:'none',owned:[],waveAnswers:0,joined:Date.now()}}
/**
 * One purchased ride stays on one hero. Copies already stored on other heroes are removed.
 * The earliest of those heroes who is on the map keeps it. If every copy is in reserve, the earliest hero keeps it.
 * A saved pupil-wide ride that is not on a hero yet is given to the first hero on the map who is still on foot.
 */
export function assignLegacyRides(w:World){for(const [id,p] of Object.entries(w.players)){if(Array.isArray(p.vehiclesOwned))p.vehiclesOwned=[...new Set(p.vehiclesOwned.filter(ride=>!!rideLook(ride)))];const own=w.defenders.filter(d=>d.owner===id),claim=(ride:string)=>{p.vehiclesOwned??=[];if(!p.vehiclesOwned.includes(ride))p.vehiclesOwned.push(ride);};for(const d of own){const ride=rideLook(d.vehicle)?.id;if(d.vehicle&&!ride)delete d.vehicle;else if(ride)claim(ride);}for(const ride of new Set(own.flatMap(d=>d.vehicle?[d.vehicle]:[]))){const holders=own.filter(d=>d.vehicle===ride);if(holders.length<2)continue;const keeper=holders.find(d=>d.cell>=0)??holders[0];for(const d of holders)if(d!==keeper)delete d.vehicle;}const legacy=rideLook(p.vehicle)?.id;if(legacy){claim(legacy);if(!own.some(d=>d.vehicle===legacy)){const host=own.find(d=>!d.vehicle&&d.cell>=0)??own.find(d=>!d.vehicle);if(host)host.vehicle=legacy;}}if(p.vehicle)delete p.vehicle;}keepOneRideInBattle(w);}
/** A wave already underway may have sent one purchase with every hero. Only the hero who still has it keeps those orders. */
function keepOneRideInBattle(w:World){const battle=w.battle;if(!battle?.rideMoves?.length)return;const kept=battle.rideMoves.filter(m=>{const d=w.defenders.find(d=>d.id===m.id);return!!d?.vehicle&&(!m.ride||m.ride===d.vehicle);});if(kept.length===battle.rideMoves.length)return;const dropped=new Set(battle.rideMoves.filter(m=>!kept.includes(m)).map(m=>m.id));battle.rideMoves=kept;for(const id of dropped){if(kept.some(m=>m.id===id))continue;const d=w.defenders.find(d=>d.id===id),f=battle.fighters.find(f=>f.id===id);if(d&&f)d.cell=f.cell;}}
function defenderRide(w:World,d:Defender){const p=w.players[d.owner];return d.vehicle&&p?.vehiclesOwned?.includes(d.vehicle)?rideLook(d.vehicle,p.vehiclePaint):undefined;}
function pupilRide(w:World,id:string){const own=w.defenders.filter(d=>d.owner===id),d=own.find(d=>d.cell>=0&&defenderRide(w,d))??own.find(d=>defenderRide(w,d));return d?defenderRide(w,d):undefined;}
export function view(w:World,uid:string|null){const colours=assignedColours(w.players);const lastChat=w.chat?.at(-1);return{revision:w.revision??0,battleVersion:w.battleVersion??0,isTeacher:uid==='teacher',chatState:uid&&(uid==='teacher'||w.players[uid])?{count:w.chat?.length??0,lastId:lastChat?.id??null,lastAt:lastChat?.at??0,lastOwner:lastChat?.owner??null}:null,onlinePlayers:Object.entries(w.players).filter(([,p])=>isOnline(p.lastSeen)).map(([id,p])=>({id,name:p.name,hero:p.hero,heroLocked:p.heroLocked,clothing:p.clothing,ride:pupilRide(w,id),online:true})),wave:w.wave,routeFrom:w.routeFrom,power:power(w),target:target(w),contributors:Object.values(w.players).filter(p=>p.waveAnswers>0).length,battle:w.battle,result:w.result,defenders:w.defenders.map(d=>({...d,ride:defenderRide(w,d),itemInventory:w.players[d.owner]?.itemInventory,equippedItems:w.players[d.owner]?.equippedItems,itemSlots:w.players[d.owner]?.itemSlots,name:w.players[d.owner]?.name,hero:w.players[d.owner]?.hero,gender:w.players[d.owner]?.gender,clothing:w.players[d.owner]?.clothing,uniform:w.players[d.owner]?.uniform??'none',outfit:w.players[d.owner]?.outfit,colour:TEAM_COLOURS[colours[d.owner]]?.css})),players:Object.entries(w.players).filter(([,p])=>p.heroLocked).map(([id,p])=>({id,colourId:colours[id],colour:TEAM_COLOURS[colours[id]]?.css,name:p.name,online:isOnline(p.lastSeen),testAccount:!!p.unlimitedCoins,collection:{clothing:p.clothingOwned??[],vehicles:p.vehiclesOwned??[],items:p.itemInventory??{},equippedItems:p.equippedItems??[]},stats:{correct:p.correct,kills:p.combat?.kills??0,damage:Math.floor(p.combat?.damage??0)},hero:p.hero,gender:p.gender,clothing:p.clothing,uniform:p.uniform??'none',outfit:p.outfit,ride:pupilRide(w,id),contributed:p.waveAnswers>0})),me:uid&&w.players[uid]?{questionProgress:roundStatus(w.players[uid]),yearGroup:assignedYear(w.players[uid]),pendingQuestion:(()=>{const active=w.players[uid].active,q=active&&questionById.get(active.id);return active&&q&&matchesYear(w.players[uid],q)?{question:publicQuestion(q,active.reward??20,uid),token:active.token}:null})(),id:uid,...((({history,active,receipts,mistakes,helpChecks,mock,mockResults,mockLast,...p})=>p)(w.players[uid])),mock:(m=>m?{subject:m.subject,startedAt:m.startedAt,endsAt:m.endsAt,count:m.ids.length,answered:Object.keys(m.answers).length}:null)(w.players[uid].mock),mockResults:(w.players[uid].mockResults??[]).map(({items,...r})=>r),mockLast:w.players[uid].mockLast??{},coins:w.players[uid].unlimitedCoins?Number.MAX_SAFE_INTEGER:w.players[uid].coins,ride:pupilRide(w,uid),colourId:colours[uid],colour:TEAM_COLOURS[colours[uid]]?.css}:null,serverNow:Date.now()}}
export async function sha(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function user(req:Request){const cookie=req.headers.get('cookie')?.match(/(?:^|;\s*)qg_session=([^;]+)/)?.[1];if(!cookie)return null;const row=await db().prepare('SELECT user_id FROM sessions WHERE token=? AND expires>?').bind(await sha(cookie),Date.now()).first<{user_id:string}>();return row?.user_id??null}
export function requireOrigin(req:Request){const origin=req.headers.get('origin');if(!origin)return;const url=new URL(req.url),source=new URL(origin);const host=req.headers.get('host')??url.host;const protocol=req.headers.get('x-forwarded-proto')?.split(',')[0].trim()??url.protocol.slice(0,-1);if(source.host!==host||source.protocol!==protocol+':')throw new Error('Please submit from the game page.');}
export function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store'}})}
