import type {Question,Subject} from './questions';
export const year2Questions:Question[]=[];
function add(subject:Subject,prompt:string,answer:string|number,explanation:string,extra:Partial<Question>={}){year2Questions.push({id:`y2-${year2Questions.length+1}`,subject,prompt,answers:[String(answer)],explanation,difficulty:'Year 2',rewardGroup:'quick',...extra});}
for(let n=1;n<=10;n++){
 add('Maths',`What is ${n+12} + ${n}?`,12+2*n,`Start at ${n+12} and count on ${n}.`);
 add('Maths',`What is ${n+20} − ${n}?`,20,`Take ${n} away from ${n+20}.`);
 add('Maths',`What is ${n} × 2?`,2*n,`${n} groups of 2 make ${2*n}.`);
 add('Maths',`Share ${n*5} stickers equally between 5 children. How many does each child get?`,n,`${n*5} ÷ 5 = ${n}.`,{rewardGroup:'standard'});
 add('Maths',`What is half of ${2*n}?`,n,`Two equal groups of ${n} make ${2*n}.`);
 add('Maths',`What number comes next? ${n*3}, ${n*3+3}, ${n*3+6}, ___`,n*3+9,'Add 3 each time.');
}
for(const [p,a,e] of [
 ['How many tens are in 47?',4,'47 has 4 tens and 7 ones.'],['How many ones are in 63?',3,'63 has 6 tens and 3 ones.'],['Which number is greater: 38 or 83?',83,'83 has more tens.'],['What is one quarter of 12?',3,'12 shared into 4 equal groups gives 3.'],['What is three quarters of 8?',6,'One quarter is 2. Three quarters are 2 + 2 + 2.'],['A pencil costs 20p and a rubber costs 15p. How many pence altogether?',35,'20 + 15 = 35 pence.'],['You pay 50p for a 30p apple. How many pence change?',20,'50 − 30 = 20 pence.'],['How many minutes are in one hour?',60,'One hour has 60 minutes.'],['How many sides does a triangle have?',3,'A triangle has 3 straight sides.'],['How many faces does a cube have?',6,'A cube has 6 square faces.'],['A ribbon is 25 cm long. You cut off 10 cm. How many centimetres remain?',15,'25 − 10 = 15 cm.'],['There are 4 red balls and 7 blue balls. How many balls are there?',11,'Add the two groups: 4 + 7 = 11.'],['A chart shows 8 votes for cats and 5 for dogs. How many more votes did cats get?',3,'Find the difference: 8 − 5 = 3.'],['What number is 10 more than 56?',66,'Add one ten to 56.'],['What number is 10 less than 72?',62,'Take one ten away from 72.'],['How many legs do 5 chickens have altogether?',10,'Each chicken has 2 legs. 5 × 2 = 10.'] ] as const)add('Maths',p,a,e);
for(const [word,plural] of [['box','boxes'],['fox','foxes'],['baby','babies'],['party','parties'],['child','children'],['mouse','mice'],['brush','brushes'],['wish','wishes']])add('English',`Write the plural of ${word}.`,plural,`More than one ${word} is written ${plural}.`);
for(const [p,a,options,e] of [
 ['Choose the correct spelling.','because',['becaus','because','becose'],'Because is the correct spelling.'],['Choose the correct spelling.','people',['peeple','peopel','people'],'People is the correct spelling.'],['Which word describes the dog in “The small dog ran”?','small',['dog','small','ran'],'Small tells us what the dog is like.'],['Which word is an action in “Lily jumps over the log”?','jumps',['Lily','jumps','log'],'Jumps tells us what Lily does.'],['Which word names a thing in “The cat sleeps”?','cat',['The','cat','sleeps'],'Cat is a noun.'],['Choose the missing word: Yesterday, I ___ to the park.','walked',['walk','walked','walking'],'Walked tells us it happened in the past.'],['Choose the missing word: I was tired ___ I went to bed.','so',['so','but','or'],'So joins an event to its result.'],['Which mark ends a question?','?',['.','?','!'],'A question ends with a question mark.'],['Which word needs a capital letter: “We play on monday”?','monday',['play','on','monday'],'Names of days begin with a capital letter.'],['Choose the missing word: The bird ___ singing.','is',['is','are','am'],'One bird is singing.'],['Which sentence is a command?','Close the door.',['Close the door.','Is it cold?','The door is blue.'],'A command tells someone what to do.'],['Choose the word meaning “not kind”.','unkind',['kindly','unkind','kindness'],'The prefix un- can mean not.'] ] as const)add('English',p,a,e,{options:[...options]});
const stories=[
 {text:'Mia planted a seed in a pot. She put it by the window and watered it each day. A week later, a tiny green shoot appeared. Mia smiled and called her dad.',qs:[['Where did Mia put the pot?','by the window',['by the window','in a cupboard','under her bed']],['What colour was the shoot?','green',['red','green','blue']],['Why did Mia smile?','Her seed was growing.',['Her seed was growing.','She lost the pot.','It was bedtime.']],['Who did Mia call?','her dad',['her mum','her dad','her teacher']]]},
 {text:'Ben and his sister took a kite to the park. At first, the air was still. Then the wind blew and the kite rose high. They held the string tightly and laughed.',qs:[['Where did Ben take the kite?','the park',['the park','the shop','the beach']],['Who went with Ben?','his sister',['his brother','his sister','his friend']],['What helped the kite rise?','the wind',['the rain','the sun','the wind']],['Why did they hold the string tightly?','To stop the kite flying away.',['To stop the kite flying away.','To make it rain.','To hide the kite.']]]},
 {text:'A hedgehog has spines on its back. When it feels unsafe, it can curl into a ball. Hedgehogs often look for food at night. They eat insects and other small animals.',qs:[['What is on a hedgehog’s back?','spines',['feathers','spines','shells']],['When does a hedgehog often look for food?','at night',['at night','only at noon','only in the morning']],['What can a hedgehog do when it feels unsafe?','curl into a ball',['fly away','curl into a ball','climb into a shell']],['Which food does the text mention?','insects',['apples','bread','insects']]]},
 {text:'It began to rain as Sam walked home. He saw Jo standing without a coat. Sam opened his big umbrella and asked Jo to walk beside him. They both arrived home dry.',qs:[['What was the weather like?','rainy',['sunny','rainy','snowy']],['Who had no coat?','Jo',['Jo','Sam','both children']],['What did Sam share?','his umbrella',['his coat','his umbrella','his lunch']],['Which word best describes Sam?','kind',['kind','selfish','angry']]]}
];
for(const story of stories)for(const [p,a,options] of story.qs)add('English',p as string,a as string,`Read the passage again: ${a}`,{passage:story.text,options:options as string[],rewardGroup:'standard'});
for(const [word,opposite] of [['hot','cold'],['big','small'],['up','down'],['wet','dry'],['happy','sad'],['fast','slow'],['open','closed'],['day','night'],['old','new'],['full','empty']])add('Verbal reasoning',`Write the opposite of ${word}.`,opposite,`${opposite} is the opposite of ${word}.`);
for(const [p,a,opts,e] of [
 ['Which word does not belong?','car',['apple','banana','car'],'Apple and banana are fruit.'],['Which word does not belong?','chair',['cat','dog','chair'],'Cat and dog are animals.'],['Which word does not belong?','spoon',['red','blue','spoon'],'Red and blue are colours.'],['Which word does not belong?','sock',['bus','train','sock'],'Bus and train are transport.'],['Which word rhymes with cat?','hat',['hat','cup','dog'],'Cat and hat end with the same sound.'],['Which word rhymes with sun?','fun',['fish','fun','sit'],'Sun and fun rhyme.'],['Which word rhymes with cake?','snake',['snake','cat','cup'],'Cake and snake rhyme.'],['Bird is to nest as bee is to ___.','hive',['pond','hive','kennel'],'A nest is a bird’s home; a hive is a bee’s home.'],['Hand is to glove as foot is to ___.','shoe',['hat','shoe','scarf'],'A shoe goes on a foot.'],['Day is to light as night is to ___.','dark',['warm','dark','green'],'Night is usually dark.'],['Which word comes first in the alphabet?','ant',['dog','cat','ant'],'A comes before C and D.'],['Which word comes last in the alphabet?','zoo',['apple','zoo','moon'],'Z comes after A and M.'],['Join “rain” and “bow” to make one word.','rainbow',null,'Rain + bow = rainbow.'],['Put these letters in order to name a pet: d o g','dog',null,'The letters make dog.'],['Put these letters in order to name a pet: t a c','cat',null,'The letters make cat.'] ] as const)add('Verbal reasoning',p,a,e,opts?{options:[...opts]}:{});
const shapes=['●','■','▲','★','◆'];
for(let i=0;i<5;i++)for(let j=0;j<5;j++)if(i!==j){const a=shapes[i],b=shapes[j];add('Non-verbal reasoning',`What comes next? ${a} ${b} ${a} ${b} ${a} ___`,b,`The pattern repeats ${a} then ${b}.`,{options:[a,b,'○']});}
for(const [p,a,opts,e] of [
 ['Which shape has no corners?','circle',['circle','square','triangle'],'A circle has a curved edge and no corners.'],['Which shape has 4 equal sides?','square',['triangle','square','circle'],'A square has 4 equal sides.'],['What comes next? ↑ → ↓ ___','←',['↑','←','→'],'The arrow turns a quarter turn clockwise each time.'],['What comes next? → ↓ ← ___','↑',['↑','↓','→'],'The arrow turns a quarter turn clockwise each time.'],['Which arrow points the opposite way to ↑?','↓',['↓','←','→'],'Down is opposite to up.'],['Which shape is different? ● ● ■ ●','■',['●','■','▲'],'The square is different from the circles.'],['What comes next? ● ● ■ ● ● ■ ● ● ___','■',['●','■','▲'],'Two circles and a square repeat.'],['How many stars are here? ★ ★ ★ ★','4',['3','4','5'],'Count the four stars.'],['Which group has more shapes? A: ● ● ●   B: ■ ■','A',['A','B','same'],'Group A has 3; group B has 2.'],['Which shape is a ball most like?','sphere',['cube','sphere','cone'],'A sphere is round like a ball.'] ] as const)add('Non-verbal reasoning',p,a,e,{options:[...opts]});
