import {user,json,readWorld,mutate,requireOrigin,type World} from '@/lib/world';
import {questionById,publicQuestion,answerMatches,revealsAnswer,readAnswer,toCanonical} from '@/lib/questions';
import {matchesYear,roundStatus,QUESTION_REST,ROUND_SIZE} from '@/lib/question-policy';
import {checkMessage} from '@/lib/chat-filter';
import {HINTS_PER_QUESTION,OPEN_HELP_REQUESTS,HINT_MIN,HINT_MAX,HELP_REST,helpStatus,liveHints,penaliseAnswer,isStuck} from '@/lib/friend-help';
import {schoolLockResponse} from '@/lib/school-lock-guard';
// Hints follow the class chat rules, without its warnings and fines: a blocked hint is simply not sent.
const UNSAFE_HINT={rude:'Keep hints kind. Rude or unkind words are not allowed.',link:'Hints cannot include links to other websites.',personal:'Keep phone numbers and email addresses private.'};
// A help request lives on the asker's private mistake record. Only the question, what the asker finds tricky and the hints are shared, never answers.
function requests(w:World){return Object.entries(w.players).flatMap(([owner,p])=>Object.entries(p.mistakes??{}).flatMap(([qid,m])=>{const q=m.help&&questionById.get(qid);return q&&m.help?[{owner,name:p.name,q,m,help:m.help}]:[]}));}
export async function GET(req:Request){try{const closed=schoolLockResponse();if(closed)return closed;const uid=await user(req);if(!uid)return json({error:'Sign in to help your friends.'},401);const {w}=await readWorld(),now=Date.now(),all=requests(w);
if(uid==='teacher'){const last=(r:typeof all[number])=>Math.max(r.help.at,...r.help.hints.map(h=>h.at));return json({isTeacher:true,requests:all.filter(r=>r.help.hints.length||helpStatus(r.m)==='open').sort((a,b)=>last(b)-last(a)).slice(0,50).map(r=>({id:r.help.id,name:r.name,question:publicQuestion(r.q),at:r.help.at,stuck:r.help.stuck??null,status:helpStatus(r.m),hints:r.help.hints.map(({owner,...h})=>h)})),serverNow:now});}
const p=w.players[uid];if(!p)return json({error:'Sign in again.'},401);const open=all.filter(r=>helpStatus(r.m)==='open');
// The asker's side: hints on questions still to solve (for the Mistakes dot and toasts), and hinted questions that can be retried now.
const unsolved=all.filter(r=>r.owner===uid&&!r.m.correctedAt&&!p.history[r.q.id]?.correct&&liveHints(r.help).length),rested=unsolved.filter(r=>now-r.m.lastWrongAt>=QUESTION_REST&&matchesYear(p,r.q)),round=rested.length?roundStatus(p,now):null;
return json({myHints:unsolved.flatMap(r=>liveHints(r.help).map(h=>({id:h.id,name:h.name,subject:r.q.subject,at:h.at}))).sort((a,b)=>b.at-a.at).slice(0,20),retry:rested.filter(r=>round![r.q.subject].completed<ROUND_SIZE).sort((a,b)=>a.m.lastWrongAt-b.m.lastWrongAt).map(r=>({id:r.q.id,subject:r.q.subject,hints:liveHints(r.help).length})),
requests:open.filter(r=>r.owner!==uid).sort((a,b)=>liveHints(a.help).length-liveHints(b.help).length||a.help.at-b.help.at).map(r=>{const check=p.helpChecks?.[r.q.id],sent=r.help.hints.find(h=>h.owner===uid),own=p.mistakes?.[r.q.id];return{id:r.help.id,name:r.name,question:publicQuestion(r.q,undefined,uid),at:r.help.at,stuck:r.help.stuck??null,hints:liveHints(r.help).length,sent:sent&&!sent.removed?sent.text:null,lost:sent?.gaveAnswer?sent.gaveAnswer.coins:null,status:sent?'sent':own&&!own.correctedAt?'own':p.active?.id===r.q.id?'active':check?.correct?'unlocked':check&&now-check.at<HELP_REST?'resting':'ready',retryAt:check&&!check.correct?check.at+HELP_REST:null}}),mine:open.filter(r=>r.owner===uid).length,sentHints:all.flatMap(r=>r.help.hints.filter(h=>h.owner===uid).map(h=>({id:h.id,name:r.name,subject:r.q.subject,text:h.text,at:h.at,status:h.gaveAnswer?'answer':h.removed?'removed':h.paidAt?'paid':'waiting',lost:h.gaveAnswer?.coins}))).sort((a,b)=>b.at-a.at).slice(0,10),serverNow:now});}catch{return json({error:'The help board is unavailable. Please try again.'},503)}}
export async function POST(req:Request){try{const closed=schoolLockResponse();if(closed)return closed;requireOrigin(req);const uid=await user(req);if(!uid)return json({error:'Sign in to help your friends.'},401);const b:any=await req.json();return json(await mutate(w=>{
if(b.action==='remove'||b.action==='gave_answer'){if(uid!=='teacher')throw Error('Only your teacher can remove hints.');const hint=requests(w).find(r=>r.help.id===b.id)?.help.hints.find(h=>h.id===b.hint);
 // A hint that gave the answer away keeps its text for the teacher and the helper; the asker never sees it again.
 if(b.action==='gave_answer'){if(hint?.gaveAnswer)return{ok:true,already:true,name:hint.name,coins:hint.gaveAnswer.coins};if(!hint||hint.removed)throw Error('That hint has already been removed.');return{ok:true,name:hint.name,coins:penaliseAnswer(w.players,hint)};}
 if(!hint)throw Error('That hint has already been removed.');if(!hint.gaveAnswer){hint.removed=true;hint.text='';}return{ok:true};}
const p=w.players[uid];if(!p)throw Error('Please sign in again.');
if(b.action==='ask'||b.action==='withdraw'){const m=p.mistakes?.[b.question];if(!questionById.has(b.question)||!m||m.correctedAt||p.history[b.question]?.correct)throw Error('Choose a question you are still solving in your mistake notebook.');if(b.action==='withdraw'){if(m.help)m.help.closed=true;return{ok:true};}
const stuck=isStuck(b.stuck)?b.stuck:undefined,status=helpStatus(m);if(status==='open'){if(stuck)m.help!.stuck=stuck;return{ok:true,already:true};}if(status==='full')throw Error(`You already have ${HINTS_PER_QUESTION} hints for this question. Read them in your mistake notebook.`);if(Object.values(p.mistakes!).filter(x=>helpStatus(x)==='open').length>=OPEN_HELP_REQUESTS)throw Error(`You can ask for help with ${OPEN_HELP_REQUESTS} questions at a time. Take one off the help board first.`);m.help={id:m.help?.id??crypto.randomUUID(),at:Date.now(),hints:m.help?.hints??[],...(stuck?{stuck}:{})};return{ok:true};}
const r=requests(w).find(r=>r.help.id===b.id),sent=r?.help.hints.find(h=>h.owner===uid);if(b.action==='hint'&&sent&&sent.id===b.hint)return{ok:true,duplicate:true};
if(!r||helpStatus(r.m)!=='open')throw Error('This question is no longer on the help board.');if(r.owner===uid)throw Error('This is your own question. Look for hints in your mistake notebook.');if(sent)throw Error('You have already sent a hint for this question.');const own=p.mistakes?.[r.q.id];if(own&&!own.correctedAt)throw Error('This question is in your mistake notebook too. Solve it there first.');if(p.active?.id===r.q.id)throw Error('Finish this question in Earn coins first.');p.helpChecks??={};const check=p.helpChecks[r.q.id];
if(b.action==='answer'){if(check?.correct)return{correct:true};if(check&&Date.now()-check.at<HELP_REST)throw Error('You can try this question again 24 hours after your last try.');const correct=answerMatches(r.q,toCanonical(r.q,uid,readAnswer(r.q,b.answer)));p.helpChecks[r.q.id]={correct,at:Date.now()};return{correct,retryAt:correct?null:Date.now()+HELP_REST};}
if(b.action!=='hint')throw Error('That help action is not available.');if(!check?.correct)throw Error('Answer the question correctly before you write a hint.');if(typeof b.hint!=='string'||!/^[a-zA-Z0-9-]{16,64}$/.test(b.hint))throw Error('Refresh and try again.');const text=typeof b.text==='string'?b.text.trim():'';if(text.length<HINT_MIN||text.length>HINT_MAX)throw Error(`Write a hint of ${HINT_MIN}–${HINT_MAX} characters.`);const unsafe=checkMessage(text);if(unsafe)throw Error(UNSAFE_HINT[unsafe]);if(revealsAnswer(r.q,text))throw Error('That gives the answer away. Try a clue instead, such as a first step or where to look.');r.help.hints.push({id:b.hint,owner:uid,name:p.name,text,at:Date.now()});return{ok:true};}));}catch(e){return json({error:e instanceof Error?e.message:'Could not save. Try again.'},400)}}
