import {json,user,mutate,view,readWorld,finish,power,target,TYPES,requireOrigin,beginBattle} from '@/lib/world';
import {questions,publicQuestion,normalise} from '@/lib/questions';
import {isBuildable} from '@/lib/battle';
export async function GET(req:Request){try{const uid=await user(req);let{w}=await readWorld();if(w.battle&&Date.now()-w.battle.start>=w.battle.duration)return json(await mutate(s=>view(s,uid)));return json(view(w,uid))}catch(e){console.error(e);return json({error:'The class world is unavailable. Please try again.'},503)}}
export async function POST(req:Request){try{requireOrigin(req);const uid=await user(req);if(!uid)return json({error:'Sign in to join your class.'},401);const b:any=await req.json();const result=await mutate(w=>{if(b.action==='battle'&&uid==='teacher'){beginBattle(w);return{world:view(w,uid)}}const p=w.players[uid];if(!p)throw new Error('Please sign in again.');
if(b.action==='question'){const subject=String(b.subject??'Maths');if(!['Maths','English','Verbal reasoning','Non-verbal reasoning'].includes(subject))throw new Error('Choose a subject.');if(p.active){const active=questions.find(q=>q.id===p.active!.id);if(active?.subject===subject)return{question:publicQuestion(active),token:p.active.token};p.history[p.active.id]={correct:false,at:Date.now()};delete p.active;}
const candidates=questions.filter(q=>q.subject===subject&&!p.history[q.id]);const retries=questions.filter(q=>q.subject===subject&&p.history[q.id]&&!p.history[q.id].correct&&Date.now()-p.history[q.id].at>=86400000);const list=candidates.length?candidates:retries;const q=list[Math.floor(Math.random()*list.length)];if(!q)return{question:null,message:'You have explored all the available questions in this subject. Try another subject. Missed questions return after 24 hours.'};p.active={id:q.id,token:crypto.randomUUID(),at:Date.now()};return{question:publicQuestion(q),token:p.active.token};}
if(b.action==='answer'){if(!p.active||p.active.token!==b.token)throw new Error('This question has already been answered. Get your next question.');const q=questions.find(q=>q.id===p.active!.id)!;const answer=String(b.answer??'').trim();if(!answer||answer.length>300)throw new Error('Type your answer first (up to 300 characters).');const correct=q.answers.some(a=>normalise(a)===normalise(answer));p.history[q.id]={correct,at:Date.now()};delete p.active;p.subjects[q.subject]??={correct:0,incorrect:0};p.subjects[q.subject][correct?'correct':'incorrect']++;let reward=0;if(correct){p.correct++;reward=20;p.coins+=reward;p.waveAnswers++;}else p.incorrect++;return{correct,reward,answer:q.answers[0],explanation:q.explanation,world:view(w,uid)};}
if(b.action==='recruit'){const type=Number(b.type);if(!Number.isInteger(type)||!TYPES[type])throw new Error('Choose a defender.');if(p.coins<TYPES[type].price)throw new Error('Answer a few more questions to earn enough coins.');if(w.defenders.filter(d=>d.owner===uid).length>=3)throw new Error('Your three defenders are ready. Upgrade one to add more power.');const cell=Number(b.cell);if(!isBuildable(cell))throw new Error('Choose a grass square beside the path.');if(w.defenders.some(d=>d.cell===cell))throw new Error('A classmate just took that square. Choose another.');p.coins-=TYPES[type].price;w.defenders.push({id:crypto.randomUUID(),owner:uid,type,level:1,cell});}
else if(b.action==='move'){if(w.battle)throw new Error('Wait for the shared wave to finish before moving heroes.');const d=w.defenders.find(d=>d.id===b.id&&d.owner===uid);const cell=Number(b.cell);if(!d)throw new Error('Choose one of your own heroes.');if(!isBuildable(cell))throw new Error('Choose a grass square beside the path.');if(w.defenders.some(o=>o.id!==d.id&&o.cell===cell))throw new Error('That square is already occupied.');d.cell=cell;}
else if(b.action==='upgrade'){const d=w.defenders.find(d=>d.id===b.id&&d.owner===uid);if(!d)throw new Error('Choose one of your own defenders.');const cost=40*d.level;if(p.coins<cost)throw new Error(`An upgrade costs ${cost} coins.`);p.coins-=cost;d.level++;}
else if(b.action==='hero'){if(![0,1,2].includes(b.hero))throw new Error('Choose a hero.');p.hero=b.hero;}
else if(b.action==='outfit'){const prices:Record<string,number>={classic:0,moonlight:80,sunset:80,royal:120};if(!(b.outfit in prices))throw new Error('Choose an outfit.');if(!p.owned.includes(b.outfit)){if(p.coins<prices[b.outfit])throw new Error('Earn more coins to unlock this outfit.');p.coins-=prices[b.outfit];p.owned.push(b.outfit);}p.outfit=b.outfit;}
else if(b.action==='battle'){beginBattle(w);}
else throw new Error('That action is not available.');return{world:view(w,uid)};});return json(result)}catch(e){return json({error:e instanceof Error?e.message:'Unable to save. Try again.'},400)}}
