import {ITEMS,itemUpgradeCost,slotCost} from '@/lib/builds';
import {CLOTHING,CLOTHING_SLOTS,wear} from '@/lib/clothing';
import {EQUIPMENT} from '@/lib/equipment';
import {TEAM_COLOURS,assignedColours} from '@/lib/colours';
import {HEROES,HERO_CHANGE_COST,SELECTABLE_HERO_IDS,upgradeCost,spawnCost} from '@/lib/heroes';
import {json,user,mutate,view,readWorld,finish,power,target,TYPES,requireOrigin,beginBattle} from '@/lib/world';
import {questions,publicQuestion,normalise} from '@/lib/questions';
import {isBuildable} from '@/lib/battle';
export async function GET(req:Request){try{const uid=await user(req);let{w}=await readWorld();if(w.battle&&Date.now()-w.battle.start>=w.battle.duration)return json(await mutate(s=>view(s,uid)));return json(view(w,uid))}catch(e){console.error(e);return json({error:'The class world is unavailable. Please try again.'},503)}}
export async function POST(req:Request){try{requireOrigin(req);const uid=await user(req);if(!uid)return json({error:'Sign in to join your class.'},401);const b:any=await req.json();const result=await mutate(w=>{if(b.action==='battle'&&uid==='teacher'){beginBattle(w,b.battleVersion);return{world:view(w,uid)}}const p=w.players[uid];if(!p)throw new Error('Please sign in again.');
const transactional=['recruit','move','weapon','upgrade','hero','clothing','undress','item_buy','item_equip','item_unequip','item_upgrade','item_slot'].includes(b.action);
const body=JSON.stringify({...b,requestId:undefined});if(transactional){if(typeof b.requestId!=='string'||b.requestId.length>100||b.requestId.length<8)throw new Error('Refresh the page and try again.');const old=p.receipts?.find(r=>r.id===b.requestId);if(old){if(old.body!==body)throw new Error('This transaction reference was already used.');return{world:view(w,uid),duplicate:true};}}
if(b.action.startsWith('item_')){if(w.battle)throw new Error('Manage items between waves.');p.itemInventory??={};p.equippedItems??=[];p.itemSlots??=2;const item=ITEMS.find(i=>i.id===b.item);const spend=(n:number)=>{if(!p.unlimitedCoins&&p.coins<n)throw new Error(`Save ${n} coins by answering questions.`);if(!p.unlimitedCoins)p.coins-=n;};
if(b.action==='item_slot'){const cost=slotCost(p.itemSlots);if(cost===null)throw new Error('All four item slots are open.');spend(cost);p.itemSlots++;}
else{if(!item)throw new Error('Choose an item.');const level=p.itemInventory[item.id]??0;
if(b.action==='item_buy'){if(level)throw new Error('You already own this item.');spend(item.price);p.itemInventory[item.id]=1;}
else if(b.action==='item_upgrade'){const cost=itemUpgradeCost(item.id,level);if(cost===null)throw new Error('Buy this item first, or it is already level 3.');spend(cost);p.itemInventory[item.id]=level+1;}
else if(b.action==='item_equip'){if(!level)throw new Error('Buy this item first.');if(p.equippedItems.includes(item.id))throw new Error('Already equipped.');if(b.replace){if(!p.equippedItems.includes(b.replace))throw new Error('Choose an equipped item to replace.');p.equippedItems=p.equippedItems.filter(id=>id!==b.replace);}if(p.equippedItems.length>=p.itemSlots)throw new Error('All slots are full. Choose an item to replace or take one off.');p.equippedItems.push(item.id);}
else if(b.action==='item_unequip'){p.equippedItems=p.equippedItems.filter(id=>id!==item.id);}else throw new Error('Unknown item action.');}
p.receipts=[...(p.receipts??[]),{id:b.requestId,body}].slice(-64);return{world:view(w,uid)};}
if(b.action==='retry_question'){const mistake=p.mistakes?.[b.id],q=questions.find(q=>q.id===b.id);if(!mistake||!q||mistake.correctedAt||p.history[b.id]?.correct)throw new Error('Choose an unresolved question from your mistake notebook.');if(Date.now()-mistake.lastWrongAt<86400000)throw new Error('This question rests for 24 hours before another attempt.');if(p.active&&p.active.id!==b.id)throw new Error('Finish your current question in Earn coins first.');p.active??={id:q.id,token:crypto.randomUUID(),at:Date.now()};return{question:publicQuestion(q),token:p.active.token,world:view(w,uid)};}
if(b.action==='question'){const subject=String(b.subject??'Maths');if(!['Maths','English','Verbal reasoning','Non-verbal reasoning'].includes(subject))throw new Error('Choose a subject.');if(p.active){const active=questions.find(q=>q.id===p.active!.id);if(active?.subject===subject)return{question:publicQuestion(active),token:p.active.token};p.history[p.active.id]={correct:false,at:Date.now(),attempted:false};delete p.active;}
const candidates=questions.filter(q=>q.subject===subject&&!p.history[q.id]);const retries=questions.filter(q=>q.subject===subject&&p.history[q.id]&&!p.history[q.id].correct&&Date.now()-p.history[q.id].at>=86400000);const list=candidates.length?candidates:retries;const preferChoices=Math.random()<.5;const formatPool=list.filter(q=>Boolean(q.options?.length)===preferChoices);const pool=formatPool.length?formatPool:list;const q=pool[Math.floor(Math.random()*pool.length)];if(!q)return{question:null,message:'You have explored all the available questions in this subject. Try another subject. Missed questions return after 24 hours.'};p.active={id:q.id,token:crypto.randomUUID(),at:Date.now()};return{question:publicQuestion(q),token:p.active.token};}
if(b.action==='answer'){if(!p.active||p.active.token!==b.token)throw new Error('This question has already been answered. Get your next question.');const q=questions.find(q=>q.id===p.active!.id)!;const answer=String(b.answer??'').trim();if(!answer||answer.length>300)throw new Error('Type your answer first (up to 300 characters).');const correct=q.answers.some(a=>normalise(a)===normalise(answer));p.history[q.id]={correct,at:Date.now(),attempted:true};p.mistakes??={};if(!correct){const old=p.mistakes[q.id];p.mistakes[q.id]={attempts:(old?.attempts??0)+1,lastWrongAt:Date.now(),lastAnswer:answer};}else if(p.mistakes[q.id])p.mistakes[q.id].correctedAt=Date.now();delete p.active;p.subjects[q.subject]??={correct:0,incorrect:0};p.subjects[q.subject][correct?'correct':'incorrect']++;let reward=0;if(correct){p.correct++;reward=20;p.coins+=reward;p.waveAnswers++;}else p.incorrect++;return{correct,reward,answer:q.answers[0],explanation:q.explanation,world:view(w,uid)};}
if(b.action==='recruit'){if(w.battle)throw new Error('Deploy heroes between waves.');const type=Number(b.type);if(!Number.isInteger(type)||!TYPES[type])throw new Error('Choose a defender.');if(!p.heroLocked)throw new Error('Choose your hero in My hero first.');if(type!==p.hero)throw new Error('You can only recruit your chosen hero.');const count=w.defenders.filter(d=>d.owner===uid).length;const cost=spawnCost(count);if(!p.unlimitedCoins&&p.coins<cost)throw new Error('Answer a few more questions to earn enough coins.');const cell=Number(b.cell);if(!isBuildable(cell))throw new Error('Choose a grass square beside the path.');if(w.defenders.some(d=>d.cell===cell))throw new Error('A classmate just took that square. Choose another.');if(!p.unlimitedCoins)p.coins-=cost;w.defenders.push({id:crypto.randomUUID(),owner:uid,type,level:0,weapon:'none',weapons:[],cell});}
else if(b.action==='move'){if(w.battle)throw new Error('Wait for the shared wave to finish before moving heroes.');const d=w.defenders.find(d=>d.id===b.id&&d.owner===uid);const cell=Number(b.cell);if(!d)throw new Error('Choose one of your own heroes.');if(!isBuildable(cell))throw new Error('Choose a grass square beside the path.');if(w.defenders.some(o=>o.id!==d.id&&o.cell===cell))throw new Error('That square is already occupied.');d.cell=cell;}
else if(b.action==='weapon'){if(w.battle)throw new Error('Equip weapons between waves.');const d=w.defenders.find(d=>d.id===b.id&&d.owner===uid);if(!d)throw new Error('Choose one of your own heroes.');const item=EQUIPMENT.find(e=>e.id===b.weapon);if(!item)throw new Error('Choose a weapon.');d.weapons??=d.level>0?['standard']:[];d.weaponLevels??={};if(d.level>0)d.weaponLevels[d.weapon??'standard']=d.level;if(!d.weapons.includes(item.id)){if(!p.unlimitedCoins&&p.coins<item.price)throw new Error(`This weapon costs ${item.price} coins.`);if(!p.unlimitedCoins)p.coins-=item.price;d.weapons.push(item.id)}d.weapon=item.id;d.level=d.weaponLevels[item.id]??1;d.weaponLevels[item.id]=d.level;}
else if(b.action==='upgrade'){const d=w.defenders.find(d=>d.id===b.id&&d.owner===uid);if(!d)throw new Error('Choose one of your own defenders.');if(w.battle)throw new Error('Upgrade between waves so the whole class sees the same heroes.');if(d.level===0)throw new Error('Buy a weapon first.');const cost=upgradeCost(d.type,d.level);if(cost===null)throw new Error('This hero has reached its final upgrade.');if(!p.unlimitedCoins&&p.coins<cost)throw new Error(`An upgrade costs ${cost} coins.`);if(!p.unlimitedCoins)p.coins-=cost;d.level++;d.weaponLevels??={};d.weaponLevels[d.weapon??'standard']=d.level;}
else if(b.action==='hero'){if(!Number.isInteger(b.hero)||!SELECTABLE_HERO_IDS.includes(b.hero))throw new Error('Choose a hero.');if(w.battle)throw new Error('Change heroes between waves.');if(p.heroLocked){if(p.hero===b.hero)throw new Error('You already have this hero.');if(!p.unlimitedCoins&&p.coins<HERO_CHANGE_COST)throw new Error(`Changing hero costs ${HERO_CHANGE_COST} coins. Keep answering questions to save up.`);if(!p.unlimitedCoins)p.coins-=HERO_CHANGE_COST;for(const d of w.defenders)if(d.owner===uid)d.type=b.hero;}if(!['boy','girl'].includes(b.gender))throw new Error('Choose boy or girl.');p.hero=b.hero;p.gender=b.gender;p.outfit='none';p.uniform='none';p.uniforms??=[];p.heroLocked=true;}
else if(b.action==='uniform'){throw new Error('Buy individual clothes in SHUS.');}
else if(b.action==='clothing'){const item=CLOTHING.find(c=>c.id===b.item);if(!item)throw new Error('Choose a clothing item.');p.clothingOwned??=[];if(!p.clothingOwned.includes(item.id)){if(!p.unlimitedCoins&&p.coins<item.price)throw new Error('Answer more questions to earn this item.');if(!p.unlimitedCoins)p.coins-=item.price;p.clothingOwned.push(item.id);}p.clothing=wear(p.clothing??{},item.id);}
else if(b.action==='undress'){if(!CLOTHING_SLOTS.some(s=>s.id===b.slot))throw new Error('Choose a clothing slot.');if(p.clothing)delete p.clothing[b.slot as keyof typeof p.clothing];}

else if(b.action==='outfit'){throw new Error('Decorations are no longer available. Visit SHUS to buy a uniform.');}
else if(b.action==='battle'){beginBattle(w,b.battleVersion);}
else throw new Error('That action is not available.');if(transactional)p.receipts=[...(p.receipts??[]),{id:b.requestId,body}].slice(-64);return{world:view(w,uid)};});return json(result)}catch(e){return json({error:e instanceof Error?e.message:'Unable to save. Try again.'},400)}}
